### ISSUE TITLE
Updated instructions for installing the plugin

### ISSUE THREAD

**Issue by Bobrm2k3** [amzn/amazon-payments-magento-2-plugin#1]
I have an existing Magento 2 project that I'm trying to add Amazon payments plugin with composer.  The document I have with instructions is outdated and I can't find anything more recent.  What do I need to add to my composer repositories and requirements to get it installed?  The M2 project is on version 2.0.7.

**Comment by danielneu** [comment]
Hi,

this module is intended for Magento 2.1+
There is an older version with less functionality available in the branch _mage206_, however this version comes with no support.

Installation via composer should work as before, simply replace the branch name from your guide with the new one above.

Best wishes
Daniel

**Comment by Bobrm2k3** [comment]
Thank you for the help.  Looks like we'll be upgrading to 2.1+.
