### ISSUE TITLE
Migration from Amazon Pay plugin V1 to V2

### ISSUE THREAD

**Issue by Naftula70** [amzn/amazon-payments-magento-2-plugin#1005]
Hello, I am trying to switch from version V1 to version V2, but I am not clear about the installation.

#### What I expected

That Plugin is working after upgrade the package dev-V2checkout-1.2.x

Starting point is a Magento 2.3.5-p2 Enterprise installtion with a Composer based Amazon Pay Plugin installation in the version amzn/amazon-pay-v2-magento-2-module 3.*.

If I replace the package amzn/amazon-payments-magento-2-plugin with the version dev-V2checkout-1.2.x as described in the readme for the branch, the plugin seems broken in the settings configuration in the backend, and in the frontend the cart where Amazon Pay Button is integrated is broken.

After several composer installation attempts I saw that composer recognizes the package amzn/amazon-payments-magento-2-plugin as "abandoned" and suggests to install the package amzn/amazon-pay-v2-magento-2-module instead, which apparently also contains only a part of the payment module.
Both packages installed together at least show a clean configuration view again, and the frontend is no longer broken, but after activating the V2 version, e.g the Amazon Pay button in the shopping cart is no longer displayed.

Questions: 

1.Am I correct in thinking that if I have a composer installtion, the Amazon Pay Module V2 will not work correctly without the V1 package, so the V2 package is a supplement to the V1 package, or is that a bug?
2.And is the documentation at https://amzn.github.io/amazon-payments-magento-2-plugin/ still valid. In particular the part on Frontend Customisation?

#### Steps to reproduce the issue

composer require amzn/amazon-payments-magento-2-plugin:dev-V2checkout-1.2.x

in a setup where amzn/amazon-payments-magento-2-plugin 3.*  is integrated.

#### Your setup

Setup
Magento ver. 2.3.5-p2
Magento Edition: Enterprise

Best regards
Thank you for help.

**Comment by jajajaime** [comment]
Hi @Naftula70,

1. You are correct in assuming that, but V2 is not a supplemental package. It is just using some of the V1 elements. We are currently working on a version that will separate them completely, which will be released in 2021.
2. Sadly, settings configuration can be referenced from there, but not the frontend customizations.

Please let me know if you need any help with specifics on customizing the frontend.

**Comment by Naftula70** [comment]
Hello @jajajaime , 
thank you very much for your answer and sorry for replying so late, but all the holidays and stuff :-). 

In your opinion, does it make sense to wait with a changeover to the new V2 version, is there already a release date for the new package?
And a second question, here i need a little help: 
What is the best way to integrate the payment button on the shopping cart in V2? Because if I'm right, the old PaymentLink block from v1 doesn't work anymore in V2, does it?

best regards and thank you.

**Comment by jaybeckr** [comment]
Hi @Naftula70 - there is no reason to wait on the standalone release, it will effectively be what is already in V2checkout (and 1.2.x variant) but separated further from V1 in the config section etc. We will have instructions for moving from the current to standalone version when it is released.

As you already clarified, for your existing installation you must have both V1 and the module from V2checkout-1.2.x branch. The button should be added to cart/checkout automatically, but if you have customized the cart then it may need some theming updates to show the button. You are correct that the PaymentLink block is no more, but you may be able to replicate how the button is added from the file: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/V2checkout-1.2.x/src/PayV2/view/frontend/templates/minicart-button.phtml
