### ISSUE TITLE
Data validation on loginPost causes Fatal Error

### ISSUE THREAD

**Issue by stkrelax** [amzn/amazon-payments-magento-2-plugin#1006]
#### What I expected
When validating loginPostData no Fatal Errors occur
#### What happened instead
Data validation causes Fatal Error
#### Steps to reproduce the issue

```
[20-Dec-2020 22:43:38 UTC] PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, null given in /var/www/app/tags/0.2.77/vendor/magento/framework/Encryption/Encryptor.php:323
Stack trace:
#0 /var/www/app/tags/0.2.77/vendor/magento/framework/Encryption/Encryptor.php(323): explode(':', NULL, 3)
#1 /var/www/app/tags/0.2.77/vendor/magento/framework/Encryption/Encryptor.php(275): Magento\Framework\Encryption\Encryptor->explodePasswordHash(NULL)
#2 /var/www/app/tags/0.2.77/vendor/magento/framework/Encryption/Encryptor.php(266): Magento\Framework\Encryption\Encryptor->isValidHash('bobbyNR1', NULL)
#3 /var/www/app/tags/0.2.77/vendor/amzn/login-with-amazon-module/Controller/Login/ValidatePost.php(89): Magento\Framework\Encryption\Encryptor->validateHash('bobbyNR1', NULL)
#4 /var/www/app/tags/0.2.77/vendor/magento/framework/App/Action/Action.php(108): Amazon\Login\Controller\Login\ValidatePost->execute()
#5 /var/www/app/tags/0.2.77/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(O in /var/www/app/tags/0.2.77/vendor/magento/framework/Encryption/Encryptor.php on line 323
[20-Dec-2020 22:44:02 UTC] PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, null given in /var/www/app/tags/0.2.77/vendor/magento/framework/Encryption/Encryptor.php:323
```

#### Your setup

*  Magento ver. 2.3.5-p2

*  "amzn/amazon-pay-and-login-with-amazon-core-module": "3.4.1-p2",
                "patches_applied": "3.4.1-p2->3.6.2": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.4.1-p2-3.6.2.patch"
*  "amzn/amazon-pay-module": "3.4.1-p2",
                "patches_applied": "3.4.1-p2->3.6.2": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-module/3.4.1-p2-3.6.2.patch"
*  "amzn/login-with-amazon-module": "3.4.1-p2"
                "patches_applied": "3.4.1-p2->3.6.2": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/login-with-amazon-module/3.4.1-p2-3.6.2.patch"

* Magento Edition: Community

**Comment by jajajaime** [comment]
Hi @stkrelax,

I tested this on a vanilla Magento 2.3.5-p2 with Amazon Pay 3.6.2, but I could not replicate the issue with a normal setup.
I was only able to get your error if I manually put a NULL on the `password_hash` column for the customer I was trying to pay/use Amazon Login with.
Is this the case with your database?
Maybe you have other 3rd party login extensions that do not create a password_hash?

Amazon Pay is using Magento core methods to grab and verify the hash, which they themselves rely on a hash being present.

**Comment by stkrelax** [comment]
Hello, 

yes this is partwise the case in our database thus these are imported customers from an older system.
no there is no other third party extension

thank you for your input

i will investigate this issue and fix the empty passwordhash
