### ISSUE TITLE
Amazon.Pay is undefined

### ISSUE THREAD

**Issue by Dren7755** [amzn/amazon-payments-magento-2-plugin#1010]
I have installed "amzn/amazon-payments-magento-2-plugin": "dev-V2checkout" on my Magento 2.4 with custom one step checkout. 

#### What I expected

Everything should work ok

#### What happened instead
Steps to Reproduce:
- add product to cart
- go to checkout
- fill all required fields
- click 'amazon pay' button
- login into amazon buyer account
- click submit
- (there is redirect back to checkout)
- see following error in console

There is console error
![image](https://user-images.githubusercontent.com/19759530/102988743-11cdcc00-451d-11eb-8e8f-5121521d2171.png)

In the same time when first loading of checkout I can see that amazon.Pay is not undefined.

After some debug I found that src/PayV2/view/frontend/web/js/view/payment/method-renderer/amazon-payment-method.js in bindEditPaymentAction uses amazon.Pay object which is undefined for me.
![image](https://user-images.githubusercontent.com/19759530/102989229-ef887e00-451d-11eb-8077-dced9f9ee9be.png)

Could you please explain for me from which place amazon.Pay should be loaded?
Note: Also I have amazon.Login, which is loaded from https://static-eu.payments-amazon.com/OffAmazonPayments/de/sandbox/lpa/js/Widgets.js?nomin

#### Your setup

* Magento version: 2.4.1
* Amazon Pay Extension Version: "amzn/amazon-payments-magento-2-plugin": "dev-V2checkout"
* Magento Edition: Community

**Comment by jajajaime** [comment]
Hi @Dren7755,

Do you see a request to get https://static-eu.payments-amazon.com/checkout.js? And if so, does it fail for any reason?
This is the script that defines amazon.Pay object. It is required by checkout-address.js in here
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/V2checkout/src/PayV2/view/frontend/web/js/view/checkout-address.js#L42

If nothing shows up, we can internally get in touch to take a look at your environment to further debug.

**Comment by Dren7755** [comment]
ok, I have merged amazon's checkout_index_index with our custom checkout layout and it works ok. Thank you and excuse for troubling
