### ISSUE TITLE
Magento Commerce [Enterprise] RMA Feature Not Working on Amazon Pay Orders

### ISSUE THREAD

**Issue by amcguireweb** [amzn/amazon-payments-magento-2-plugin#1015]
#### What I expected

I expect customers to be able to use the built in RMA Request form for Magento Commerce by submitting an RMA request from the frontend. This works as expected for all other orders placed with a different payment method, as well as from inside the order in the Magento admin.

#### What happened instead

The customer receives an error "You entered incorrect data. Please try again.".

#### Steps to reproduce the issue

Enable RMA on Magento Commerce, configure Amazon Pay, receive an order from a customer using Amazon Pay as the payment method, complete the order, and then attempt to submit an RMA request from the frontend.

#### Your setup

* Magento version: 2.3.5-p2
* Amazon Pay Extension Version: Module version: 3.7.1
* Magento Edition: Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process - I'm not sure what to provide you here.

**Comment by RayAnaya** [comment]
Hi @amcguireweb ,

Thank you for bringing this issue to our attention.  I'll need to look into this issue a bit further, as we have not been building our extension for the Enterprise Edition (i.e. for its specific feature sets!)  just yet.  With that said, we absolutely want to ensure our plugin "works" and I've gotten a few other requests or comments now, about some of the things (pricing rules for instance) that are Enterprise Edition features, which we just happened to overlook.

Let me take this back to the team and I'll update this issue once I have an idea of when we'll be able to address it.  Please note, it will have to be for our latest code branches and product (it currently shows up as V2Checkout here, but that will change in the near future, so please stay tuned).

**Comment by jajajaime** [comment]
Hi @amcguireweb,

I tested out the RMA process on a 2.3.5-p2 instance and with our latest Marketplace plugin and did not have any issues. The process succeeds as expected on all steps. Another details is that the return process is separate from the order, and refund actions have to be done manually.

Given that you have 3.7.1 installed, I will recommend to still update to the newest Marketplace Amazon Pay plugin 5.0.1 or newer, https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html.
This version is in active development. All previous ones have been deprecated and/or are in end of life.

Let us know if you have any other questions regarding this.

**Comment by christianzichichi** [comment]
Hi @amcguireweb,

as suggested above, please install the markeplace plugin to solve this issue: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html.
you can also find Installation and Configuration guide for the new marketplace plugin here: https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html

Thanks
Regards

Christian
