### ISSUE TITLE
Error when running a cron job - Call to a member function getAmazonOrderReferenceId() on null at Model/PaymentManagement/Authorization.php:483

### ISSUE THREAD

**Issue by amcguireweb** [amzn/amazon-payments-magento-2-plugin#1033]
#### What I expected

Module function without exceptions

#### What happened instead

Exception being continuously thrown: 
report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:367, Error(code: 0): Call to a member function getAmazonOrderReferenceId() on null at vendor/amzn/amazon-pay-module/Model/PaymentManagement/Authorization.php:483)"} []

#### Steps to reproduce the issue

Magento 2.4.2 - we recently updated Magento from 2.3.5-p2 briefly to 2.3.6-p1, then to 2.4.2. I have been tailing the exception.log while testing things, and just general navigation of the site, and i noticed it was thrown several times after I looked back at the terminal.

I am also on staging environment, and all customers have been deleted. Is this trying to complete orders somehow or is it related to the customer data no longer being present? The Amazon Pay module is also configured with our sandbox environment, perhaps that's related?

#### Your setup

* Magento version: 2.4.2
* Amazon Pay Extension Version: 4.2.0
* Magento Edition: Enterprise Cloud
* JavaScript Console: Nothing related to provide
* Shop URL : Willing to share privately

**Comment by jajajaime** [comment]
Hi @amcguireweb,

I went ahead and tested on 2.4.2 with Marketplace plugin with Charge on Shipment + Automatic mode, and with CaptureInitiated card, single invoice+shipment, multiple invoice+shipment, multiple invoice+shipment with CaptureInitiated simulation string. The cronjob never ran into an issue.
My guess is that the order got created on 2.3.5-p2 with 3.4.1-p2 version of the plugin, but now 4.2.0 is expecting something else.

In either case, both versions above have been deprecated and are at EOL. I recommend upgrading to the Marketplace plugin
https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html.
Instructions for installing and configuring can be found in https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html.

**Comment by amcguireweb** [comment]
I'm not sure I follow. Are you saying that Amazon Pay Extension Version: 4.2.0 is not the most recent version? In either case, I cannot upgrade using Marketplace, I'm using Magento Commerce Cloud, how can I upgrade/patch 4.2.0 with Magento 2.4.2?

**Comment by jaybeckr** [comment]
Hi @amcguireweb - you can use the Marketplace module with Commerce Cloud. The process (from https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#composer-install-method) is:

1. "Purchase" (for free) the module under the same Adobe account that holds the Commerce license - https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html
(if this is not possible, it's also available on packagist via the same package name so you can skip this step)
2. `composer require amzn/amazon-pay-magento-2-module:5.*`
3. `bin/magento module:enable Amazon_Pay --clear-static-content`

This will update the `composer.json`, `composer.lock`, and `app/etc/config.php` files, which you can commit and deploy to your staging site for testing. During the `composer require` section it will automatically remove the in-core versions so there will be no conflicts.

**Comment by amcguireweb** [comment]
Hi @jaybeckr, we're updated to 5.6.0 and still experiencing the error.

[2021-08-23 06:15:04] report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /app/xxxxxxxxxxxxx/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:367, Error(code: 0): Call to a member function getAmazonOrderReferenceId() on null at /app/xxxxxxxxxxxxx/vendor/amzn/amazon-pay-module/Model/PaymentManagement/Authorization.php:483)"} []
[2021-08-23 06:20:03] report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /app/xxxxxxxxxxxxx/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:367, Error(code: 0): Call to a member function getAmazonOrderReferenceId() on null at /app/xxxxxxxxxxxxx/vendor/amzn/amazon-pay-module/Model/PaymentManagement/Authorization.php:483)"} []

**Comment by jaybeckr** [comment]
Hi @amcguireweb - Is it showing 5.6.0 in the admin under Advanced > Module Version? 
![image](https://user-images.githubusercontent.com/20869477/130514943-83c5745b-f869-4035-ab61-e521dc9ae84e.png)

The class referenced in the error message is no longer present - https://github.com/amzn/amazon-payments-magento-2-plugin/tree/master/Model doesn't have a "PaymentManagement" directory any more, that is from the old version of the module. Please double check that the module is upgraded successfully.

**Comment by amcguireweb** [comment]
Yeah, I'm seeing 5.6.0 in the admin console, and in the json files.

![image](https://user-images.githubusercontent.com/8235324/130515401-149e3ec1-659b-4ea2-aef5-68271d7f2e05.png)

I will double check some things and update shortly. Thanks for the reply!

**Comment by amcguireweb** [comment]
Something isn't right for sure, even the module name has changed and the error is showing the old module name. Maybe something with Fastly, I'll update once I figure it out. Thank you again.
