### ISSUE TITLE
Total off after Amazon Pay login on mobile

### ISSUE THREAD

**Issue by aholovan** [amzn/amazon-payments-magento-2-plugin#104]
#### Steps to reproduce the issue

Hello, 

On mobile after successful order log out from the site. Then add some product and logging back in via Amazon again. Sometimes login freezes on the "You will be redirected shortly" step. But even if You got on checkout there is cart total issue - totals shows 0$.
Looks like for some circumstances quote is not calculated after login. Likely this is because after log out new empty quote is saved. And later after log in new one is created. 
So, these quotes are being merged by loadCustomerQuote() function [Magento\Checkout\Model\Session class] because $this->getQuoteId() != $customerQuote->getId(). After that grand_total, subtotal, etc are still equals 0.0000.
As result the part of the code where collectTotals() is not used and quote is not calculated.
I've fixed this issue by running $this->checkoutSession->loadCustomerQuote() again after login function in Amazon\Login\Helper\Session class. Next iteration of this action calculates quote as expected.
Please, investigate it. Maybe you are able to find root problem in logic which causes this issue.

Thanks.

**Comment by aholovan** [comment]
Hello @danielneu,

Please, review the issue and check the fix in 
https://github.com/amzn/amazon-payments-magento-2-plugin/pull/105

Thanks.

**Comment by danielneu** [comment]
Will hand this over for review.

Thanks for spotting and providing the PR.

Best wishes 
Daniel

**Comment by prayagr** [comment]
Closing after fix was applied in #237 , please reopen in case you face this issue
