### ISSUE TITLE
Error in raising a StateException in the Amazon\Pay\Mode\Alexa::apiCall 

### ISSUE THREAD

**Issue by a-litvin** [amzn/amazon-payments-magento-2-plugin#1046]
#### What I expected

_Amazon\Pay\Mode\Alexa::apiCall_, line 93: https://i.imgur.com/fY6So07.png
An exception is created if an API call is unsuccessful.

#### What happened instead

An exception will never be raised, because _\Magento\Framework\Exception\StateException_ expects an object of type _\Magento\Framework\Phrase_ as parameter. A _string_ is always given instead.

#### Steps to reproduce the issue

Make any API call which will return not 200 status.

#### Your setup

* Magento version: 2.3.4
* Amazon Pay Extension Version: 5.2.0
* Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @a-litvin ,

thanks for reaching out. This issue has been already solved in the newest release, 5.3.0, that will soon be published in the Magento Marketplace: https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/5.3.0

Thanks
Best

Christian
