### ISSUE TITLE
Bad user experience when user's Amazon address is missing a phone number

### ISSUE THREAD

**Issue by shilpsauce** [amzn/amazon-payments-magento-2-plugin#1050]
#### What I expected
When the selected Amazon Pay address does not have a phone number, the user is able to add a phone number to their shipping address easily.

#### What happened instead
User is redirected to the cart page saying telephone is required, but there's no place to put the phone number on the cart page. When the Amazon Pay button is clicked, you can't modify the address to add a phone number, you have to enter a whole new address. There is also no place in Magento to just add the phone number to the shipping address.

The customer was confused after this experience and abandoned checkout.

#### Steps to reproduce the issue
1. Sign in
2. add item to cart and checkout with amazon pay
3. select an address that does not have a phone number
4. try to place order
5. order is not placed, and user is placed on the cart page with an error saying telephone is required.

#### Your setup

* Magento version: 2.3.7
* Amazon Pay Extension Version: 5.3.0
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : https://www.banyanbotanicals.com

**Comment by lbalebg** [comment]
Hello @shilpsauce 

We tested the scenario on a clean Magento 2.3.7 with version 5.3.0 of the module and were able to verify that the phone field is displayed in the correct place:

![image-20210527-190941](https://user-images.githubusercontent.com/85237216/120489894-5bed9000-c38e-11eb-89dc-ed22d0f04bc4.png)

Do you have a customization on your checkout flow ? Any third party extensions that could be conflicting with AP ?
If possible try to remove any extensions from the checkout and validate if the error still occurs.

**Comment by shilpsauce** [comment]
You have to be a signed in customer, then that field isn't there.

**Comment by lbale** [comment]
We also tested it with a user who is logged in and it works the same way.

![image](https://user-images.githubusercontent.com/5631666/120498909-fdc4ab00-c395-11eb-88ed-f8dea8b60fc6.png)

**Comment by joshbourke** [comment]
This is definitely not in the latest release of the module.
We still encounter customers who do not have a phone number in their old Amazon address.
It leads to a very confusing experience for customers.

Phone is required but nowhere to provide it.

Honestly the PaySDK should just allow a merchant to specify the field is required. But that's asking too much I guess.
