### ISSUE TITLE
AmazonPay Button not loading in Onepage-Checkout when button in Minicart is ON ( Can not find element #ui-id-3 for amazon.Pay.renderButton. checkout.js:1:1721)

### ISSUE THREAD

**Issue by aurel5542** [amzn/amazon-payments-magento-2-plugin#1052]
Hello, I installed the new 5.4.0 AmazonPay Extension on Magento 2.3.6-p1.
The button is endless loading (loader is spinning and not showing the button) in Onepage-Checkout. The button is working in Minicart (when not in Onepage-Checkout but other page f.e. home or article page) and working in cart.

The error shows: "Uncaught AmazonPay: Can not find element #ui-id-3 for amazon.Pay.renderButton. checkout.js:1:1721". I tested this on several computers with Chrome and Mozilla.

When I refresh the page several times, sometimes it works and sometimes it does not. Sometimes the button even works the first time and when I refresh the page its not working again. When the button is not working at the checkout and the error appears then its also not working in minicart. When I then go back to home or some other page its working again in minicart.

When I deactivate "Show Amazon Pay button in minicart" ("No") its working fine in Onepage-Checkout so I guess it has something to do with the button loading twice on Onepage Checkout (1. in Minicart and 2. on Checkout Shipping page).

Steps to reproduce:
Install AmazonPay plugin, activate "Show in Minicart", add items to cart, checkout with onepage-checkout. (If button is working refresh page or go to home and go the onepage checkout again)

* Magento version: 2.3.6-p1
* Amazon Pay Extension Version: 5.4.0
* Magento Edition: Community

**Comment by jaybeckr** [comment]
Hi @aurel5542  - do you have a customization that shows the minicart when in the checkout flow? Typical onepage checkout doesn't have it included, however there are other pages (e.g. cart) that show the button in both the minicart and the page.

**Comment by aurel5542** [comment]
Hello @jaybeckr thanks for your answer. Yes we have a custom checkout (only design changes) which still has the header with minicart so I guess the issue is not reproducable for most people. I guess we will just leave it like it is now without AmazonPay in Minicart. If anybody still has a fix for this I would of course be glad!

**Comment by jaybeckr** [comment]
Ok, thanks for confirming. We'll look into it more, as the two should not interfere with each other but since that is not the standard checkout so we don't typically test with that layout. Please use the workaround (no minicart button) for now and we'll let you know what we find.

**Comment by aurel5542** [comment]
ok @jaybeckr thank you so much for your quick reply!

**Comment by jaybeckr** [comment]
Hi @aurel5542 - we weren't able to replicate the behavior with a simple environment where we re-added the header, however we fixed a similar issue for a different situation. Are you able to test applying a particular commit on a local or staging environment? If so, please apply https://github.com/BearGroup/amazon-payments-magento-2-plugin/commit/a4cded3d96afc706977032787eab9d50b417c93b and see if it allows you to have the button in the minicart.

**Comment by jaybeckr** [comment]
@aurel5542 - this fix has been included in version 5.5.1 which is live on Magento Marketplace now. Please update and let us know if it resolves your issue, thanks!
