### ISSUE TITLE
JS error in safari browser

### ISSUE THREAD

**Issue by SukimaSwitch** [amzn/amazon-payments-magento-2-plugin#1053]
JS error in safari browser

#### What I expected

Don't have any exception when render the checkout page in Safari browser

#### What happened instead

Throw exception message "undefined is not an object (evaluating 'l().Login')" in the browser console window.
![image](https://user-images.githubusercontent.com/48080750/120584327-5e211e80-c462-11eb-9fd1-9c0f14776398.png)

#### Steps to reproduce the issue

1. Add any product into the shopping cart.
2. Check out the shopping cart.
3. Proceed to Review & Payment page.

#### Your setup

* Magento version: 2.4.2
* Amazon Pay Extension Version: 4.2.0
* Magento Edition: Community

**Comment by jaybeckr** [comment]
Hi @SukimaSwitch - I am not able to trigger this on my environment, do you have a site where I can observe the behavior?

A couple other points/clarifications:
* does this happen when entering standard Magento checkout, or Amazon Pay checkout?
* this error is coming from the Amazon hosted js, separate from this Magento module. Obviously we may be triggering it based on how we are initializing the Amazon Pay library
* there is a much improved version of the module available on Marketplace or packagist, if possible please upgrade to the current version there (5.4.0 at the moment) - https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html

**Comment by SukimaSwitch** [comment]
@jaybeckr, thank you very much for your reply, based on more investigation, this issue only happens on our shopping cart page, and it seems to be closely related to the network status. This issue is caused by that widget.js used an empty object, which has not been returned by login.js when it is used. I put our website url in the below for your reference. Maybe upgrading to the latest version would be a good choice, Thanks again.
https://www.currentcatalog.com/

**Comment by jaybeckr** [comment]
@SukimaSwitch - have you been able to try the marketplace release of the module yet?

**Comment by drabikowy** [comment]
Hello @SukimaSwitch @jaybeckr 
Were you able to track down the cause of this issue or solution for it? 
I have the same issue, happening 2.5k times a day logged in stentry.io. 
I'm wondering if there is any solution for that or if the update to v5 helps. 
I would appreciate any feedback.

**Comment by jaybeckr** [comment]
Hi @drabikowy - we certainly recommend upgrading to 5.x as there have been many improvements made to a whole bunch of aspects of the module. If you are able to upgrade and still see the issue, please don't hesitate to open a new issue and we will investigate!
