### ISSUE TITLE
Orders not being created in M2 admin but payment is successful.

### ISSUE THREAD

**Issue by pavitrapapiofficial** [amzn/amazon-payments-magento-2-plugin#1062]
Hi,
I am facing the same issue on Magento Version : 2.3.5 Plugin Version : 3.4.1. Orders not being created in M2 admin but payment is successful.
Additionally, I have got an error <Code>OrderReferenceNotModifiable</Code>
`[2021-06-25 17:08:58] amazonClientLogger.DEBUG: POST
mws.amazonservices.com
/OffAmazonPayments/2013-01-01
AWSAccessKeyId=ACCESS_KEY_OF_MY_ACCOUNT&Action=SetOrderReferenceDetails&AmazonOrderReferenceId=P01-0714261-7849312&OrderReferenceAttributes.OrderTotal.Amount=63.2&OrderReferenceAttributes.OrderTotal.CurrencyCode=USD&OrderReferenceAttributes.PlatformId=AUGT0HMCLQVX1&OrderReferenceAttributes.SellerOrderAttributes.CustomInformation=Magento%20Version%20%3A%202.3.5%20Plugin%20Version%20%3A%203.4.1&OrderReferenceAttributes.SellerOrderAttributes.StoreName=STOERE_NAME&SellerId=SELLER_ID&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-06-25T17%3A08%3A58.000Z&Version=2013-01-01 [] []
[2021-06-25 17:08:59] amazonClientLogger.DEBUG: amazon-pay-sdk-php/3.7.1 (PHP/7.3.28; Linux/x86_64/3.10.0-1160.21.1.el7.x86_64) [] []
[2021-06-25 17:08:59] amazonClientLogger.DEBUG: <ErrorResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <Error>
    <Type>Sender</Type>
    <Code>OrderReferenceNotModifiable</Code>
  </Error>
  <RequestId>a5bdf99b-76c8-45a4-aac8-419547116f02</RequestId>
</ErrorResponse>
 [] []`

I hope this info will help you

_Originally posted by @pavitrapapiofficial in https://github.com/amzn/amazon-payments-magento-2-plugin/issues/191#issuecomment-872710674_

**Comment by christianzichichi** [comment]
Hi @pavitrapapiofficial ,
thanks for reaching out. There was a specific issue related to version 3.4.1 and magento 2.3.5, that you can find here: https://support.magento.com/hc/en-us/articles/360042646332-Patch-for-Amazon-Pay-checkout-issue-in-Magento-2-3-5-p1
i believe the error you are facing is one of the causes. 
You can patch that amazon pay module to the latest version for that branch using this patch: https://gist.github.com/christianzichichi/7d0d76b541070c3cdea77554c391c571
I would recommended however to move to our new marketplace module, as the in-core module is not maintained anymore: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html
https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html

Thanks
Best

Christian
