### ISSUE TITLE
Amazon Pay Magento 2.18 Error

### ISSUE THREAD

**Issue by mitellio** [amzn/amazon-payments-magento-2-plugin#107]
#### What I expected

Amazon Pay module to work correctly when installed

#### What happened instead

When the developer switched it to production site, the admin panel was no longer visible in Magento back-end

#### Steps to reproduce the issue

Unable to reproduce error in staging environment. Do not want to reproduce on production site for obvious reasons

#### Your setup

* Magento version: 2.18
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : dinopc.com

**Comment by manuelfdo** [comment]
Your backend looks like this? #96

**Comment by danielneu** [comment]
Sounds exactly like #96 @mitellio can you confirm?

I will review the fix provided there.

**Comment by danielneu** [comment]
#108 was merged which should solve this issue.

**Comment by danielneu** [comment]
closing as duplicate, feel free to open if you think this is not the same issue as #96
