### ISSUE TITLE
GraphQL Support 

### ISSUE THREAD

**Issue by larsroettig** [amzn/amazon-payments-magento-2-plugin#1077]
#### What I expected

As a Developer, I expected also the support of GraphQL the REST API from Magento2 is deprecated and PWAStudio only supportsGraphQL a mix of REST and GraphQL is technical not possibly and leads to session issues. 

Here you can find a Blogpost how to created an Endpoint for Magento 
[ow to create a GraphQL Mutation Endpoint for Magento](https://larsroettig.dev/how-to-create-a-graph-ql-mutation-endpoint-for-magento-2-3)

A workflow diagram like https://devdocs.magento.com/guides/v2.4/graphql/payment-methods/klarna.html would be great. 

If you any question you can find my  at Twitter or Magento Community Slack 

- https://twitter.com/LarsRoettig
- https://join.slack.com/t/magentocommeng/shared_invite/zt-mje5x2ye-3VGeNoaNxDGYMDle6qLuXA

 
#### Your setup

* Magento version: 2.x.x
* Amazon Pay Extension Version: 
* Magento Edition: Community / Enterprise / Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by tlundgr** [comment]
Thank you! We are currently looking into scoping and scheduling this functionality. I will keep this ticket open until we decide a course of action.

**Comment by christianzichichi** [comment]
Hi @larsroettig ,
GraphQL support has been introduced in version 5.13.0: https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/5.13.0 
https://amzn.github.io/amazon-payments-magento-2-plugin/customisation.html#docs

feel free to provide any feedback and reopen this issue in case you have any problems!

Thanks
Best
Christian
