### ISSUE TITLE
Magento Swagger crashes due to parameter notation in API interface

### ISSUE THREAD

**Issue by ebaschiera** [amzn/amazon-payments-magento-2-plugin#1078]
Hi,
it looks like a parameter type notation in https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/Api/CheckoutSessionManagementInterface.php doesn't get along with Magento Swagger.
I don't know if anything else is crashing too, but a Swagger crash is a blocker when working with APIs.

The fix is very simple and I am providing a PR.

Thanks!

#### Steps to reproduce the issue

Open Magento Swagger UI, by visiting http://<magento_url>/swagger
See that it reports the following error message: `Internal Server Error https://<magento_url>/rest/all/schema?services=all`

#### Your setup

* Magento version: 2.4.2
* Amazon Pay Extension Version: 5.7.1
* Magento Edition: Enterprise
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by sgabhart22** [comment]
Hello @ebaschiera ,

Thanks for picking up on this and providing the PR! We're currently testing this internally and initially all looks good. Once our QA passes, we'll include the fix in our workflow to go out in the next release. For now we'll close the PR without accepting it, but this issue will remain open until the release goes out.

**Comment by christianzichichi** [comment]
Hi @ebaschiera , 

thanks for your contribution. The new release has been published: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html

Thanks
best

Christian

**Comment by ebaschiera** [comment]
Thanks!
