### ISSUE TITLE
numeric cart_id not handled correctly in API endpoints

### ISSUE THREAD

**Issue by ebaschiera** [amzn/amazon-payments-magento-2-plugin#1081]
Hi!

#### What I expected

When calling the API endpoints that have `{cart_id}` as argument, if we pass a numeric `cart_id`, the module can't find the quote, because it assumes that `cart_id` is a masked cart id.
The problem lies here: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/5.8.0/Model/CheckoutSessionManagement.php#L337
There should be a logic that handles numeric `$cartId`, so that a simple `$this->cartRepository->get($cartId);` would work.

#### What happened instead

Empty response or `['success' => false]`

#### Steps to reproduce the issue

Call one of the API endpoints that accept a cart_id as argument and pass an existing numeric cart_id:

- `/V1/amazon-checkout-session/config/{cartId}`
- `/V1/amazon-checkout-session/{amazonSessionId}/update/{cartId}`
- `/V1/amazon-checkout-session/{amazonSessionId}/complete/{cartId}`

The response will be `[]` or `['success' => false]`

#### Your setup

* Magento version: 2.4.2
* Amazon Pay Extension Version: 5.8.0
* Magento Edition: Enterprise
* JavaScript Console: -
* Shop URL : -

Thanks!

**Comment by jaybeckr** [comment]
Hi @ebaschiera - this is behaving as intended, the API endpoints are typically used in a headless frontend where it would be utilizing the masked cart ID anyhow.

What is the use case where you could have a numeric card ID on the frontend but making REST calls to the API?

**Comment by haelbichalex** [comment]
@jaybeckr I'm facing the same issue on a headless frontend. When a user is logged in, there is no masked cart ID anymore as far as I understand.

**Comment by ebaschiera** [comment]
Hi @jaybeckr ,
we use a custom frontend layer that handles numeric cart IDs for both authenticated and anonymous users.
I understand my request is be a bit too specific to my use case. I don't know if it may hurt anyone.

**Comment by jaybeckr** [comment]
@haelbichalex - hmm, I thought the masked cart ID was still available even for logged in users. We did see something where the cart can be loaded out of the authentication context though, so possibly we could make a change to where you could leave the cart id off entirely for authenticated requests.

@ebaschiera - do you verify the numeric cart ID that is passed in? The trouble we saw with using the numeric ID is that it is easily guessable, so an attacker could theoretically get data about someone else's cart.

**Comment by haelbichalex** [comment]
Looks like Magento decided to split this into multiple requests, one for guests and one for logged in users: https://github.com/magento/magento2/blob/2.3/app/code/Magento/Checkout/etc/webapi.xml#L12 & https://github.com/magento/magento2/blob/2.3/app/code/Magento/Checkout/etc/webapi.xml#L20

Maybe this can be applied here as well. Another idea would be to check if the cart ID passed is numeric and load the real ID if it's not numeric.

**Comment by ebaschiera** [comment]
> @ebaschiera - do you verify the numeric cart ID that is passed in? The trouble we saw with using the numeric ID is that it is easily guessable, so an attacker could theoretically get data about someone else's cart.

That's right, they are guessable. But our headless stack is custom and Magento is hidden behind the frontend layer, so it's impossible to query Magento APIs directly. That's why I say our use case is very specific.

**Comment by jaybeckr** [comment]
@haelbichalex - one thing that we could do is if no cart is found, then load from the API context. This is what the `/carts/mine` endpoint uses, does that sound like a reasonable approach for your implementation? See https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/Webapi/ParamOverriderCartId.php#L50

@ebaschiera - I've investigated this some more and I don't know that we can safely make a change to support numeric cart ID. With your custom API layer, do you know if the context is available to get the cart from? If not, then you may need to patch the `getQuoteFromIdOrSession()` call to get the cart directly instead of doing the mask lookup first - https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/Model/CheckoutSessionManagement.php#L331

**Comment by haelbichalex** [comment]
@jaybeckr That would probably work yes, since we are already using the `/carts/mine` endpoint, we can inherit the logic for the endpoints from this package.
