### ISSUE TITLE
Private Key Required On Each Save, Preventing Saving OTHER Payment Method Configurations.

### ISSUE THREAD

**Issue by amcguireweb** [amzn/amazon-payments-magento-2-plugin#1083]
#### What I expected

To be able to save the payment methods configuration without being required to reenter the private key for Amazon Pay.

#### What happened instead

Unfortunately this problem is compounded by multistore configurations. We currently have the module disabled at the default level, and then enabled and configured at a specific store level. When we attempt to make a change to the default configuration of the Payment Methods, the configuration won't save. It's just jumps the page a little bit like it's trying to scroll to an error, however there are no errors. If I disable Amazon_Pay, the default payment methods configuration saves as expected.

#### Steps to reproduce the issue

1. Enable Amazon_Pay module
2. Configure Magento for multiple stores, we have three.
2. Leave Amazon_Pay module disabled by default, and change the scope to one of the other stores.
3. Configure the module for the specific store, including pasting the private key as text (because upload also doesn't work, but that's a different "issue" I suppose).
4. Save configuration at the store level.
5. Return to default configuration and attempt to save.

#### Your setup

* Magento version: 2.4.3
* Amazon Pay Extension Version: 5.6.0
* Magento Edition: Enterprise Cloud
* JavaScript Console: Console was clean
* Shop URL : Cannot share publicly

**Comment by jaybeckr** [comment]
Hi @amcguireweb - Thank you for the detailed repro steps! As you may have seen, we have made a change to simply allow blank values for that field which should resolve the issue you have with the module not being enabled at the Default level but still trying to validate that config. This will be included in the next release, likely live this week.

I am interested in the upload not working as well, as you said it's a separate issue that I'll investigate independently. Assuming you're not too bothered by that at this point since you have already pasted in the necessary values.

**Comment by amcguireweb** [comment]
Hey @jaybeckr, thanks for the reply. I had not noticed that a change was coming in an upcoming release. Where can I keep up on that? I looked around and didn't see anything obvious.

As for the upload, maybe it does work? It was just never there the next time.

**Comment by jaybeckr** [comment]
@amcguireweb - the only place is on this issue, "lbale added a commit ..." The change was added for this issue, sorry for the confusion!

For upload, we'll give it a quick test anyhow. It should put asterisks in the config field if it has a value saved, but also should give you a notice if it fails to validate the credentials via a basic api call to Amazon. I'd expect if it didn't save properly then it would have been more obvious.
