### ISSUE TITLE
Signature Error on "Pay Now" Button when Umlaut contained

### ISSUE THREAD

**Issue by HenKun** [amzn/amazon-payments-magento-2-plugin#1086]
### Description

When using an umlaut in name or address the Amazon Pay Now button (the button that is shown amongst the other payment methods) does not work. When redirected to Amazon hosted page, a signature validation error is shown.

#### What I expected

Umlauts can be used without any error.

1. Address without Umlaut

![Adresse-No-Umlaut](https://user-images.githubusercontent.com/18382633/138292484-c55da485-4b0e-432c-870c-ad38f0ec215d.png)

2. `paynow_payload`:

```json
{"webCheckoutDetails":{"checkoutMode":"ProcessOrder","checkoutResultReturnUrl":"https://stage.nebelkind.powered-by-rackspeed.de/de/amazon_pay/checkout/completeSession/","checkoutCancelUrl":"https://stage.nebelkind.powered-by-rackspeed.de/de/checkout/cart/"},"storeId":"amzn1.application-oa2-client.3a2e64f09e7c41289bec9ec6febde05f","paymentDetails":{"paymentIntent":"Authorize","canHandlePendingAuthorization":true,"chargeAmount":{"amount":29,"currencyCode":"EUR"},"presentmentCurrency":"EUR"},"merchantMetadata":{"merchantReferenceId":null,"merchantStoreName":"Nebelkind","customInformation":"Magento Version: 2.4.1, Plugin Version: 5.8.0"},"addressDetails":{"name":"Test Test","city":"Leipzig","postalCode":"01069","countryCode":"DE","stateOrRegion":"SAS","addressLine1":"Musterstrasse 2","phoneNumber":"0"}}
```
3. Success

![Adresse-Umlaut-Signature-Success](https://user-images.githubusercontent.com/18382633/138292946-142084c0-02c5-4f5f-8176-208a9f719d56.png)

#### What happened instead

Amazon shows "Signature Validation fails Error".

#### Steps to reproduce the issue

1. Address (Name) with Umlaut (ü)

![Adresse-Umlaut](https://user-images.githubusercontent.com/18382633/138293040-53a39315-670a-4b23-b6a4-931c5cb6c52b.png)

2. `paynow_payload`:

```json
'{"webCheckoutDetails":{"checkoutMode":"ProcessOrder","checkoutResultReturnUrl":"xxx/amazon_pay/checkout/completeSession/","checkoutCancelUrl":"xxx/checkout/cart/"},"storeId":"xxx","paymentDetails":{"paymentIntent":"Authorize","canHandlePendingAuthorization":true,"chargeAmount":{"amount":29,"currencyCode":"EUR"},"presentmentCurrency":"EUR"},"merchantMetadata":{"merchantReferenceId":null,"merchantStoreName":"xxx","customInformation":"Magento Version: 2.4.1, Plugin Version: 5.8.0"},"addressDetails":{"name":"Test\u00fc Test","city":"Leipzig","postalCode":"01069","countryCode":"DE","stateOrRegion":"SAS","addressLine1":"Musterstrasse 2","phoneNumber":"0"}}'
```

3. `paynow_signature`:

```
cf5Sk2JfCF4W4xHu/AkzP2/ssLpdvJWhCf7osFtqaYSmm2xeykBoLodcBRT+Q5bAeINw4HWEx+fME7OPb3jMWq9pCZIuhP9oxBGMo0q1LgX+WoW4zx1tKzTZsNJYVxxVY8DgOppKahx1faUFHoP7Bd6TLnov82HDwwpI+5KgqUs6TOjqhrITyUnWygnD4IfUMt76Z8usJnvhqqK/mTC+7Y5nneqRGX+M6EuOgWyanhPlmRDBrqhabcaKCb/mbh1ldyyfnRNYiq+tCNxx4Asz00tOaXZerjw80Hx2nELcPiRKTiL1uQjIcxEC7K2wDsrEmy5QB3Ix/yA0ftAkbWGelw==
```

4. Signature Validation Error
5. 
![Adresse-Umlaut-Signature-Error](https://user-images.githubusercontent.com/18382633/138293230-41bd3b52-7a3e-44ff-9000-b90b2cf0b340.png)

#### Your setup

* Magento version: 2.4.1
* Amazon Pay Extension Version: 5.8.0
* Magento Edition: Community

**Comment by christianzichichi** [comment]
new release containing fix for this issue: https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/5.9.1
