### ISSUE TITLE
Amazon pay not working with downloadable products

### ISSUE THREAD

**Issue by clickdigitalinteractive** [amzn/amazon-payments-magento-2-plugin#109]
#### What I expected
Module to work for downloadable products, not just products with shipping.

#### Steps to reproduce the issue
install module, try to purchase a downloadable product (i.e. a product with no shipping)

#### Your setup

* Magento version: 2.1
* Magento Edition: Community
* error messages:
1. we receive are normal amazon payment method box but it says "you cannot change the payment method for this order. Please contact the seller for assistance." 
2. sometimes the payment info from amazon will show up with the correct info, but the page will start off with an error that flashes up top that says "Amazon Pay could not process your request. Please try again."

Here are the logs:
[2017-08-22 20:50:21] main.DEBUG: POST
mws.amazonservices.com
/OffAmazonPayments_Sandbox/2013-01-01
AWSAccessKeyId=KEYREMOVED&Action=GetOrderReferenceDetails&AddressConsentToken=Atza%7CIwEBIIp5NqbIOsQDcyjG4a-xJ5qjnHcA4htsUTYJlSkQhnQhwDq3lOgn99CqJxoYOsdBiQeDjj5Q_-V3mAH9wxFpvPmXEmcDWfhpRApgl6HGT6cCOVjHCArVVfo1rszSUIgCnUUjT3JId5vi-3Wvykp-dmK6uSeU8BkzU30MyrvybjY-IW-Atas4MXwWAErF-w3LW17tEBx2Or_gEgLVCIGay0Dm7VI4CIvOMKQPkgBrYBhmCJ1HqNKmULBKypDTy7F5H9b9lIkPM3DOO0fEKSG42L3NpMr5Wt52TEMYOGV2ai8E3HF3qrZSRBYr4OzdYShZ8iWUUQk1-iBVajO_6JbysVbu0ROfH5jF9wUXZAdqH2Z9dUanO3_7BtkJ-UqA4uPgCTLVA0K3jh9_gXceQjvecJgzwrkz_77r01Fth16q_GVcpP_tqB-gxsWfiD7fNioD_UmwK3-FNBcYM0a_0CwN5hC629n2lFrDILGzpQ8T_4O4A00yIsjlKgn2MWz1Tx7KQro&AmazonOrderReferenceId=%3AamazonOrderReference&SellerId=A3O8SIN3FV056C&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2017-08-22T20%3A50%3A21.000Z&Version=2013-01-01 {"is_exception":false} []
[2017-08-22 20:50:21] main.DEBUG: / (Language=PHP/7.0.22; Platform=Linux/x86_64/2.6.32-642.6.2.el6.x86_64; MWSClientVersion=2.1.0) {"is_exception":false} []
[2017-08-22 20:50:21] main.DEBUG: <ErrorResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidOrderReferenceId</Code>
    <Message>The OrderReferenceId :amazonOrderReference is invalid.</Message>
  </Error>
  <RequestId>6eb6b7ad-df38-42bf-93a5-5c8a1a545caf</RequestId>
</ErrorResponse>
 {"is_exception":false} []

**Comment by danielneu** [comment]
Hi,

can you specify the exact Magento and Amazon Pay module version you are using?
This used to work and I'm surprised it does not anymore.

Best wishes 
Daniel

**Comment by clickdigitalinteractive** [comment]
amazon module 1.1.3 and magento 2.1.7. It's thinking amazon module is wanting a shipping method and wanting to go into the step 2 shipping box and not populate in the first.

**Comment by danielneu** [comment]
@clickdigitalinteractive 

The issue is not reproducible for us, are you able to share staging access with the agency?

Best wishes 
Daniel

**Comment by danielneu** [comment]
@clickdigitalinteractive any chance to get back to us? I would like to get you in touch with our agency to discuss this in more detail. As I said, this is working just fine for us and must be related to your instance.

Best wishes 
Daniel

**Comment by clickdigitalinteractive** [comment]
@danielneu I've learned it was downloadable products with the one step checkout we used, when we used amazon core checkout, downloadable works. I will test a few other one step checkouts to see if I can narrow down why amazon gives that error.

**Comment by danielneu** [comment]
@clickdigitalinteractive 

While not yet 100% accepted in QA, the PR #106 could resolve this. May be worth checking if this is something we will get rid of as well, as soon as we can accept this PR.

Best wishes 
Daniel

**Comment by clickdigitalinteractive** [comment]
@danielneu thanks. we'll check once we get the merge.

**Comment by aholovan** [comment]
Hi guys,

We have got likely the same problem but with Gift cards purchased with Amazon Pay.  
If capture is enabled in both these cases order is in complete status already during execution of Amazon\Payment\Observer\CompleteOrder. 
So, code on line 58
$order->getStoredData()[OrderInterface::STATE] != Order::STATE_COMPLETE gets an error because order object is new and array $order->getStoredData() is empty in that case.
As result there is error message and order is not placed in Magento. 
PR #106 does not fix this issue.

**Comment by aholovan** [comment]
@danielneu, I've added some fixes in https://github.com/amzn/amazon-payments-magento-2-plugin/pull/125 PR.

It works well with all my local tests but I'm not fully sure that we have to run it for just-created order because it does not contain any references to other and closeOrderReference() function does nothing.
Seems You are able to discuss it with your's Magento devs. 

Thanks.
