### ISSUE TITLE
credit memo

### ISSUE THREAD

**Issue by AliakseiSafronenka** [amzn/amazon-payments-magento-2-plugin#1094]
Cannot create credit memo

#### What I expected

I can create credit memo for order

#### What happened instead

There are no credit memo button and i cannot create credit memo

#### Steps to reproduce the issue

1) pay order using amazon payment
2) go to admin - there are: invoice created and paid, transaction status = capture, order status = review payment, no credit memo button (issue reproduced for some amazon payed orders and no problems with other. I suppose its because of "payment review " status, because correct orders have "processing" status)

#### Your setup

* Magento version: 2.4.1
* Amazon Pay Extension Version: 5.9.0
* Magento Edition: Community

**Comment by sgabhart22** [comment]
Hello @AliakseiSafronenka ,

Can you tell me the values you have for Payment Action and Authorization Mode in the configuration options for the module? It might be helpful to see a screenshot of the order history notes if you are able to supply one:
![gh-credit-memo](https://user-images.githubusercontent.com/13084014/142284621-88d71fe7-64e0-4b51-a5c3-0d24d118fe7a.png)

We will create an internal ticket if we're able to reproduce this issue. Thanks for reaching out!

**Comment by AliakseiSafronenka** [comment]
@sgabhart22 
Payment action: Charge on order
Authorization Mode: authomatic
history for bad order:
![image](https://user-images.githubusercontent.com/47207997/142287654-af019241-cc20-4f19-82ba-d4d65ba88b44.png)

history for good order:
![image](https://user-images.githubusercontent.com/47207997/142287614-5bc98190-231c-4407-8285-e54ee4438da6.png)

(it may seems that  order for 2 and 3 entries on screenshots matters , but no - it can be both for good orders)

**Comment by AliakseiSafronenka** [comment]
@sgabhart22 translated history:

bad order:

The amount of € 79.98 is recorded after it has been approved in the payment gateway. Transaction ID: "c39c0c9a-a8d6-4e4c-a023-6c860132fc25"
Comment added Nov 8, 2021 11:43:03 AM
Cannot create invoice for Order # D-99890
Comment added Nov 8, 2021 11:43:04 AM
Recorded amount of € 79.98 online. Transaction ID: "P02-2815433-6054571-C078787"
Comment added Nov 8, 2021 11:43:05 AM


good order:

The amount of € 29.99 is recorded after it has been approved in the payment gateway. Transaction ID: "cd2187b1-4062-4264-bcde-126fc49b05c1"
Comment added Nov 17, 2021 12:23:54 AM
Recorded amount of € 29.99 online. Transaction ID: "P02-2786758-7015307-C045535"
Comment added Nov 17, 2021 12:23:55 AM
Cannot create invoice for Order # D-100051
Comment added Nov 17, 2021 12:23:55 AM

**Comment by sgabhart22** [comment]
Thank you for that, I think we'll go ahead and ticket this for now. Something looks strange in the timing of those transactions.

In the meantime, I would suggest an upgrade of the Amazon Pay module if that is possible for you at this time. We are currently on version 5.9.1, and have made some significant improvements from the version you are running.

Please let us know if you are able to upgrade, and if it resolves the issue.

**Comment by AliakseiSafronenka** [comment]
@sgabhart22  we had had same issue previously and upgrated module to last version 5.9.0 but it havent solved the problem

**Comment by sgabhart22** [comment]
@AliakseiSafronenka Are you able to provide an email address we can use to include you on our internal ticket? We'll likely request some additional information there (logs, access to a staging site perhaps) and continue the discussion.

So for clarity, are you using version 2.9.0, or 5.9.0 of the module?

**Comment by AliakseiSafronenka** [comment]
5.9.0,

aliakseisafronenka@gmail.com
