### ISSUE TITLE
Amazon Login Button rendering

### ISSUE THREAD

**Issue by stkrelax** [amzn/amazon-payments-magento-2-plugin#1102]
#### What I expected

button looks pretty

#### What happened instead

it doesn´t

#### Steps to reproduce the issue

activate amazon login 

#### Your setup

* Magento version: 2.4.2 -p1
* Amazon Pay Extension Version: 5.9.1
* Magento Edition: Community 

https://m.media-amazon.com/images/G/02/AmazonPay/Maxo/Button-SignIn-ProductPg-es_ES.svg

![Bildschirmfoto von 2022-01-24 10-55-28](https://user-images.githubusercontent.com/48922246/150762563-88793ad8-ceb5-4bf0-9105-66659851e831.png)
![Bildschirmfoto von 2022-01-24 11-05-57](https://user-images.githubusercontent.com/48922246/150762672-395f039d-fd6d-4667-9588-bf05bf1a6ef2.png)
![Bildschirmfoto von 2022-01-24 11-05-47](https://user-images.githubusercontent.com/48922246/150762675-1a392856-48cd-47d3-b676-99c3ceafb3a1.png)
![Bildschirmfoto von 2022-01-24 11-05-42](https://user-images.githubusercontent.com/48922246/150762677-58a0db24-2e86-4bdd-9212-6c0909d2874a.png)
![Bildschirmfoto von 2022-01-24 11-05-36](https://user-images.githubusercontent.com/48922246/150762680-67e9aff4-0f3a-4e95-8417-6eaad4687a4f.png)

**Comment by christianzichichi** [comment]
Hi @stkrelax ,
thanks for reaching out. Can you provide more information about the environment such as OS and browser used?

Thanks
Best

Christian

**Comment by stkrelax** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal


Firefox 96.0

**Comment by christianzichichi** [comment]
Hi @stkrelax ,
the issue is due to Amazon Ember font not being available on Ubuntu. Can you try from a different OS or by making the font available in the OS ?

Christian

**Comment by stkrelax** [comment]
Hi @christianzichichi 
In windows it works. 
How am i supposed to change a customers OS by adding the font in there system? I don't think this would be possible..

**Comment by christianzichichi** [comment]
Hi @stkrelax ,
the issue should be solved now on amazon pay side. Can you doublecheck?
Thanks
Christian

**Comment by tqbert** [comment]
Yes i checked and no i did not work
![Bildschirmfoto von 2022-05-30 13-33-37](https://user-images.githubusercontent.com/106157215/170984022-d04c4dbb-44bb-45c1-b41c-24cba90f6136.png)
![Bildschirmfoto von 2022-05-30 13-33-20](https://user-images.githubusercontent.com/106157215/170984023-80cdc0d2-ca5f-4f46-8b48-3013cc687a89.png)

**Comment by christianzichichi** [comment]
@tqbert can you doublecheck now? 
Thanks a lot
Best
Christian

**Comment by christianzichichi** [comment]
new url for the image: 

https://m.media-amazon.com/images/G/02/AmazonPay/Maxo/Button-SignIn-ProductPage-es_ES.svg

**Comment by tqbert** [comment]
![Bildschirmfoto von 2022-06-13 10-26-08](https://user-images.githubusercontent.com/106157215/173311775-939f4720-087c-434b-bc2c-b9f5bf16aa6a.png)

this one works
