### ISSUE TITLE
Closing an order using MSI, reservations are not cleared

### ISSUE THREAD

**Issue by ganeddact** [amzn/amazon-payments-magento-2-plugin#1109]
#### What I expected

When an order paid through Amazon Pay is closed, if Magento is configured to use MSI, the inventory reservation for the items purchased should be cleared.

#### What happened instead

The Inventory Reservation line(s) stay in the database table, potentially preventing sales

#### Steps to reproduce the issue

Place an order through Amazon Pay then cancel it.
Order should then be marked with status "closed".
Check inventory_reservation table, it will have a line (or more) reserving the items

#### Your setup

* Magento version: 2.4.3
* Amazon Pay Extension Version: 4.2.1
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : 

Using Braintree replicating the same scenario, for example, reservations are being cleared.

**Comment by sgabhart22** [comment]
Hello @ganeddact ,

Unfortunately, I'm unable to reproduce this on a 2.4.3 installation with multiple inventory sources. When I cancel an order placed with Amazon Pay, the order status becomes 'Canceled', not 'Closed', and a corresponding line is added to the inventory_reservation table with a quantity to offset the quantity of the order.

Would you be willing to test this scenario with the up-to-date version of the Amazon Pay module and see if this resolves your issue? You can find upgrade/installation instructions [here](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#composer-install-method).

If you believe you are still seeing incorrect behavior, please let us know, and we may request access to a staging/dev environment where we can see this happening.

Thanks,
Spencer

**Comment by ganeddact** [comment]
My apologies, what I meant with "then cancel it" was to refund entirely the order. That should put the order on "closed" status

**Comment by sgabhart22** [comment]
I am still unable to reproduce when refunding; whether I complete the refund online or offline. If the order status is not changing to 'Closed' once the refund id complete, it sounds like something is interfering with the order processing. Are you using any extensions to manage your inventory sources, or any custom order statuses? Also, did you get a chance to test with version 5.10.0 of the Amazon Pay module?

**Comment by ganeddact** [comment]
Thanks for trying again.
So you can't see any line in the table inventory_reservations?
It's odd, there shouldn't be any other extensions that may interfere, and issuing an online refund moved the status of the order to "Closed".

We'll have a look at the 5.10.0 version of the module asap. Is 5.10.0 going to be added to the upcoming version 2.4.4 of Magento?

Thank you

**Comment by christianzichichi** [comment]
Hi @ganeddact ,
do you still need assistance with this issue? Version 5.11.1 of our extension is available on Magento Marketplace.

Thanks
Best

Christian

**Comment by ganeddact** [comment]
Hi Christian, not at the moment, it can be closed for now
