### ISSUE TITLE
Amazon_Pay

### ISSUE THREAD

**Issue by rosialix** [amzn/amazon-payments-magento-2-plugin#1134]
I have magento 2.3.5 installed with php7.1 and composer 1, how would I install Amazon_Pay. Thanks for the support

**Comment by sgabhart22** [comment]
Hello @rosialix ,

For detailed installation instructions, you can visit the [module documentation](https://amzn.github.io/amazon-payments-magento-2-plugin/), specifically the Installation page discussing [installation with Composer](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#composer-install-method). With your setup, I don't think you should have any major problems.

It is important to note that, if you have previously processed any transactions on your installation using the legacy/bundled version of the Amazon Pay module, you should make sure those transactions are settled before the upgrade. Please let us know if you have any issues with the installation!

Spencer
