### ISSUE TITLE
side-col missing in Stores => Configuration

### ISSUE THREAD

**Issue by Briedisk** [amzn/amazon-payments-magento-2-plugin#114]
"amzn/amazon-pay-and-login-magento-2-module": "1.1.3",
installed via composer (deployed via deploy HQ)
Magento CE 2.1.7

After installing 
side-col missing in Stores => Configuration

https://github.com/amzn/amazon-payments-magento-2-plugin/pull/108/files
did not resolve the issue

**Comment by danielneu** [comment]
Handing this over for review. I will put you and your Amazon Pay business contact in cc,

Best wishes 
Daniel

**Comment by Briedisk** [comment]
This may help:
![image](https://user-images.githubusercontent.com/22744621/29710268-7b6c7a3a-8987-11e7-90c4-cf784bba04de.png)
by checking the difference in generated html found this
comparing version with and without amazon module

**Comment by RayAnaya** [comment]
I am going to go ahead and mark this issue as resolved for now, as there have been numerous upgrades and new versions since the initial report.  Please feel free to re-open this issue if you continue to experience problems with the newest versions of Magento 2 and the Amazon Pay plugin.
