### ISSUE TITLE
Cannot change order status from "Processing" to custom status

### ISSUE THREAD

**Issue by sprayground** [amzn/amazon-payments-magento-2-plugin#115]
#### What I expected

Any order with a status of "Processing" (and state of processing, though this is not as relevant to our situation) to be changed to "Fulfillable" by the warehouse. "Fulfillable" is a status that is equivalent to "Processing" for all intents as far as Magento is concerned.

Every order minus an odd one here and there has no problem with this status change. The status is reflected in the commandline and in the CMS.

If "paid using Amazon Pay" - the order status cannot be changed from Processing to other custom status.

setStatus() and productRepository->save(product) run with nothing unusual but status is not saved. All orders with payment method Amazon Pay are affected.

However the new status history IS created. If I print out the history of the order I can see the first item (latest) status is the correct one. It just isn't reflected as the "current status" when using $order->getStatus()

#### Steps to reproduce the issue

Change status of order from Processing to anything else in the Processing family of custom orders in the CMS or through code with `$order->setStatus()` or `$order->addStatusHistory("whatever", "comment", false);`

#### Your setup

* Magento version: 2.1.7
* Magento Edition: Community

**Comment by danielneu** [comment]
Hi @sprayground 

does this configuration option help?
https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#new-order-status

Best wishes 
Daniel

**Comment by sprayground** [comment]
This might be helpful but I'm wondering, does the plugin, when set to either update mechanism option, overwrite any custom order status that we set manually, on the next iteration (ie if polling for changes)?

**Comment by aholovan** [comment]
Hello guys, 

We've got the same issue. Currently CompleteOrderStatus observer which runs by sales_order_save_before event sets the status in wrong way to equal New Order Status.
This bug does not allow to set Order Status from admin panel or after export.

**Comment by danielneu** [comment]
Thanks, this makes sense and I will pass this on to get a fix.

Best wishes 
Daniel

**Comment by aholovan** [comment]
@danielneu ,
Please, check https://github.com/amzn/amazon-payments-magento-2-plugin/pull/118 asap. Thanks.

**Comment by danielneu** [comment]
looking good, will be part of the next release, hopefully next week.
