### ISSUE TITLE
amazonCheckoutSessionId is missing

### ISSUE THREAD

**Issue by alex-kaigorodov** [amzn/amazon-payments-magento-2-plugin#1161]
#### What I expected

amazonCheckoutSessionId get parameter is returned with amazon_pay/checkout/completeSession request after a successful transaction.

#### What happened instead

If we initiate an Amazon Pay process with a button from a cart page, then on the last step a customer is redirected to amazon_pay/checkout/completeSession without amazonCheckoutSessionId parameter. That leads to a situation when an order is not placed due to an error ([CheckoutSessionManagement lines 657-663](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/5.14.1/Model/CheckoutSessionManagement.php#L657)), but a transaction in Amazon Pay is created and an amount is authorized.
Important to note, that if we select Amazon Pay as a payment method on a payment step of a checkout then customer returns with a amazonCheckoutSessionId as expected.

#### Setup

* Magento version: 2.4.4
* Amazon Pay Extension Version: 5.14.1
* Magento Edition: Enterprise

My question is: In which cases a customer can be redirected to the amazon_pay/checkout/completeSession after a transaction that looks like a successful one? I haven't found any information about such a case on the web and the [official Amazon Pay documentation](https://developer.amazon.com/docs/amazon-pay-recurring-checkout/verify-and-complete-checkout.html) also states that a customer should return to the checkoutResultReturnUrl with a session id parameter.
Is this a normal situation or an edge case not covered by the extension?

**Comment by lbale** [comment]
Hello Alex,

The amazonSessionId parameter is mandatory and is needed to be able to finish the transaction correctly, so it is not possible to continue the execution without having that information.
Those lines of code are there to ensure that the execution of the method does not throw unexpected errors in the event that for some reason all the corresponding data is not received. There should be no valid case where that instance is reached without the corresponding session id parameter.
If for some reason you have experienced cases where a scenario like this occurs, please provide us with information on how we could reproduce the error.
Thanks

**Comment by alex-kaigorodov** [comment]
Thanks for the information.
