### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by mvenghaus** [amzn/amazon-payments-magento-2-plugin#1173]
Hey folks,

since today there is magento 2.4.6 with the possibility to use php 8.2.

I tested my integration I i didn't have any problems with 8.2. The only thing is the dependency to php 8.1 in your composer.json.

Are there any plans when a new version will be available?

Regards
Marcus

**Comment by sgabhart22** [comment]
Hello @mvenghaus ,

Thanks for raising this point, we are actually in the process of addressing a couple of other small compatibility issues with 2.4.6 (removal of Zend libraries, mostly), and will include the composer changes as well. We'll probably want to get this out somewhat quickly as I'm sure more more users will move to 2.4.6, so I'd say a new version should be available in the next couple of weeks.

Thanks again,
Spencer

**Comment by Abbey-Lubber** [comment]
I'm pretty sure that bringing down the entire front end of a website running 2.4.6/php 8.1 with this error 
`require (['uiRegistry'], function(registry) { registry.set('amazonPay', An error has happened during application run. See exception log for details.`
is a little more than just a 'small compatibility issue'... +1 on removing zend libraries so we can re-enable and use this module again...

exception log says 'Error: Class "Zend_Json" not found in .../public_html/vendor/amzn/amazon-pay-magento-2-module$'

**Comment by mvenghaus** [comment]
@Abbey-Lubber .. yeah .. i've made a pull request for the issues i found

https://github.com/amzn/amazon-payments-magento-2-plugin/pull/1175

**Comment by sgabhart22** [comment]
Thanks for that @mvenghaus , I think that PR should cover all of the necessary changes. Until we can get a new release available in the Marketplace (hopefully later this week), these commits can be applied to restore functionality. Clearly this should have been included before the general availability of 2.4.6, and your contribution is appreciated.

Thank you,
Spencer

**Comment by Abbey-Lubber** [comment]
@mvenghaus #1175 applied to our web store; seems to work beautifully again. Thanks!

**Comment by sgabhart22** [comment]
Hello all,

Version 5.14.2 of the module is now available on the Marketplace and addresses the 12.4.6/PHP 8.2 compatibility problems. We'll go ahead and close this issue, and thanks again @mvenghaus for the interim fixes!

Spencer
