### ISSUE TITLE
Delivery information in the amazon pay address

### ISSUE THREAD

**Issue by rajeev-k-tomy** [amzn/amazon-payments-magento-2-plugin#1176]
Amazon pay interface address creation section contains delivery information. It asks for additional information about the delivery address and also ask for the delivery preference. Please see the screen shot below:

![Screenshot 2023-03-24 at 11 34 33 AM](https://user-images.githubusercontent.com/7589113/227438640-a4622eca-2baf-459f-8369-ce5b251f5370.png)

I would like to know how is this delivery details handled in the Magento side.

#### What I expected
When we collect delivery information from the customer, it needs to be shown in the order details in the admin side at least. Otherwise, there is no way we could know about the customer preferences.

It will also make sense to show this in the checkout page as well, in case the customer needs a different preference. But this is debatable.

#### What happened instead

I cannot find any details related to the delivery information in the order created.  

#### Steps to reproduce the issue

1. Add a product to the cart.
2. Go to the checkout page.
3. Choose amazon pay express. Click on the amazon pay button
4. In the redirected amazon pay interface, choose an address with delivery setting or create a new address with delivery preference.
5. Come back to checkout page and complete the order.
6. Delivery information is not present in the order.

#### Your setup

* Magento version: 2.4.5
* Amazon Pay Extension Version: 5.14.0
* Magento Edition: Community

**Comment by sgabhart22** [comment]
Hello @rajeev-k-tomy ,

I don't believe that Magento CE includes any built in functionality to handle special delivery instructions/dates. Since this isn't a standard checkout field, the plugin does not make accommodations for returned Amazon address data that includes these delivery instructions. There do appear to be other third-party extensions that provide this, one of which I found on the Marketplace here: https://marketplace.magento.com/scommerce-deliveryinstruction.html

If you choose to explore this route, it's possible you may be able to auto-populate those fields from Amazon address information by adding a mixin or two to the Amazon Pay frontend code (likely checkout-address.js).

Thanks,
Spencer

**Comment by rajeev-k-tomy** [comment]
@sgabhart22 Thank you for your response. It is good to know  such feature is possible with at least, other third party modules. So this is something we can get via Amazon Pay API? If yes, can you give me some relevant links that will allow to fetch these details?

**Comment by rajeev-k-tomy** [comment]
@mvenghaus @sgabhart22 Yes, I also roughtly went through the API documentation and could not find any way to fetch these details from Amazon Pay API. Now I am curious to know how these third party extensions managed to do this!

**Comment by mvenghaus** [comment]
@rajeev-k-tomy i tested a real response via api .. none of your needed information are included .. i don't think other 3rd party extensions can do this .. they only provide the ability to save this kind of information

**Comment by rajeev-k-tomy** [comment]
@mvenghaus Hmm.. then if the customer provide some delivery information via there, then there is no way the host know about it! This is bad i would say.

**Comment by mvenghaus** [comment]
@rajeev-k-tomy i see no way to get these information from the api .. but i would be happy if you can prove me wrong :)

**Comment by rajeev-k-tomy** [comment]
@sgabhart22 Thanks for checking. Let us know once you get any information on this.
