### ISSUE TITLE
Amazon\Pay\Model\Config\KeyUpgrade::getPublicKeyId(): Argument #3 ($accessKey) must be of type string, null given

### ISSUE THREAD

**Issue by steve-caponetto** [amzn/amazon-payments-magento-2-plugin#1188]
#### What I expected

Ran composer update to pull in latest package versions. Expected newest version to install with no issues.

#### What happened instead

Running `bin/magento setup:upgrade` gave the following error:

`Amazon\Pay\Model\Config\KeyUpgrade::getPublicKeyId(): Argument #3 ($accessKey) must be of type string, null given, called in /var/www/magento/vendor/amzn/amazon-pay-magento-2-module/Setup/Patch/Data/PerformKeyUpgrade.php on line 88#0 /var/www/magento/vendor/amzn/amazon-pay-magento-2-module/Setup/Patch/Data/PerformKeyUpgrade.php(88): Amazon\Pay\Model\Config\KeyUpgrade->getPublicKeyId('default', 0, NULL)`

#### Steps to reproduce the issue

Previously running Amazon Pay module 5.14.1

composer update
bin/magento setup:upgrade

#### Your setup

* Magento version: 2.4.5-p1
* Amazon Pay Extension Version: 5.15.0
* Magento Edition:  Enterprise
* PHP Verison: 8.1.13

**Comment by p24-max** [comment]
+1 - Facing the same issue

**Comment by NisiPasa** [comment]
The issue was addressed in the latest release available now on the Marketplace (5.16.0)

Thanks
