### ISSUE TITLE
Wrong svg file is loaded in the checkout from the amazon site

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#121]
A wrong svg file path is implanted by the extension in the checkout.
The extension tries to call a svg file which is not there:

https://images-na.ssl-images-amazon.com/images/G/01/EP/offAmazonPayments/de/live/prod/image/lwa/lightgray/svg/PwA.svg

**Comment by andidhouse** [comment]
![bildschirmfoto 2017-08-31 um 10 18 18](https://user-images.githubusercontent.com/16196483/29913849-9efec634-8e36-11e7-86a0-590ea9c80986.png)

**Comment by danielneu** [comment]
Thanks, 

I will investigate where this is coming from.

Best wishes 
Daniel

**Comment by prayagr** [comment]
Hi @andidhouse, we are unable to replicate the issue on our end. Can you point us to a page where you are seeing this issue? You can also email us at payments-cp-devel@amazon.com

**Comment by andidhouse** [comment]
i did send the info to then mentioned address a view days ago...

**Comment by danielneu** [comment]
And I replied yesterday or today.
I was not able to reproduce this, unfortunately. Are you sure this is still an issue?

**Comment by danielneu** [comment]
Hi @andidhouse ,

is this still an issue you are facing? We have no other contacts for this and are not able to reproduce?
