### ISSUE TITLE
Style issues in amazon pay in custom theme

### ISSUE THREAD

**Issue by kilis** [amzn/amazon-payments-magento-2-plugin#122]
#### What I expected

1. Have custom theme for shop (that does not use less).
2. Add module and creds
3. Try to checkout
4. See module in checkout
Use also css files also for styling

#### What happened instead
1. Have custom theme for shop (that does not use less).
2. Add module and creds
3. Try to checkout
4. Styles are missing for module and it can't be found

#### Steps to reproduce the issue

1. Have custom theme without less

#### Your setup

* Magento version: 2.1.7
* Magento Edition: Community
* Use custom theme wihtout less

Fix:
Use also plain css files

**Comment by danielneu** [comment]
Thanks,

handed over to our experts. Could be similar to #10

**Comment by kilis** [comment]
Thanks! 
Also found issues that some module by 3rd party callled Magecomp_Multiflatrate somehow affect how module works for us.
If you can investigate please do.

**Comment by danielneu** [comment]
Hi,

are you able to share access to a staging server (frontend, backend and ssh, if possible) where we could have a look at this?
You can share details via payments-cp-devel@amazon.com , no need to post them on github.

Thanks
Daniel

**Comment by danielneu** [comment]
Hi @kilis ,

sorry, forgot to "@" you in the question above. In case you missed it for this reason, are you bale to send us access details to have a look at this?

Best wishes 
Daniel

**Comment by kilis** [comment]
I need to confirm first with our PMs then i will contact you

pirmd., 2017. g. 4. sept. plkst. 12:20 — Daniel Neu <
notifications@github.com> rakstīja:

**Comment by danielneu** [comment]
@kilis 

Is there any update you can share with us?

Best wishes 
Daniel

**Comment by kilis** [comment]
Not yet. I heve no confirmation what to do next on it.

**Comment by danielneu** [comment]
hi @kilis 

any update here? Are you able to share access (or a theme to replicate this) with us?
You can share details via payments-cp-devel@amazon.com , no need to post them on github.

Best wishes 
Daniel

**Comment by kilis** [comment]
Regerding access no clue. Poke our PM about that issue.

**Comment by danielneu** [comment]
I am closing this for now, feel free to re-open as soon as you are able to share details.
We are not able to investigate this at this time.

General question about custom themes is noted down in #10

**Comment by kilis** [comment]
Hey! @danielneu.
Send more details in email.
