### ISSUE TITLE
[GRAPHQL] Add payment/amazon_payment/payment_region option in StoreConfig

### ISSUE THREAD

**Issue by dimitriBouteille** [amzn/amazon-payments-magento-2-plugin#1222]
It's possible to add `payment/amazon_payment/payment_region` option in StoreConfig ?

**Comment by sgabhart22** [comment]
Hi @dimitriBouteille ,

Your PR proves that it's very possible :slightly_smiling_face: I can't think of a reason off the top of my head why we would be opposed to exposing this, but I'll double check with our Amazon contacts just in case. And FYI, if we do decide to include this, we won't merge your PR directly but will cherry pick your original commits in.

Thanks again for all the attention to our GraphQL API!
Spencer

**Comment by sgabhart22** [comment]
Hello again @dimitriBouteille ,

Just letting you know that version 5.17.0 of the module is now live and includes these changes! We'll be closing this issue shortly (along with #1218 ).

**Comment by dimitriBouteille** [comment]
Hi @sgabhart22 

Perfect 👌
