### ISSUE TITLE
Amazon_Pay/js/amazon-product-add.min.js 404 (Not Found)

### ISSUE THREAD

**Issue by tim-breitenstein-it** [amzn/amazon-payments-magento-2-plugin#1240]
#### What I expected

Working PDP.

#### What happened instead

Browser Console shows Error:

```
 https://m246.example.com/static/versionXYZ/frontend/Test/Theme/Amazon_Pay/js/amazon-product-add.min.js net::ERR_ABORTED 404 (Not Found)
```

#### Steps to reproduce the issue

- Install latest (v5.17.0 ) Amazon Pay Extension.
- Enable Amazon Pay Payment Method (Sandbox).
- Go to PDP.

#### Your setup

* Magento version: 2.4.6-p5
* Amazon Pay Extension Version: 5.17.0
* Magento Edition: Community 
* JavaScript Console: 
```
 https://m246.example.com/static/versionxyz/frontend/Test/Theme/Amazon_Pay/js/amazon-product-add.min.js net::ERR_ABORTED 404 (Not Found)
```

I think it is related to this Commit: https://github.com/amzn/amazon-payments-magento-2-plugin/commit/48e5bea0d81ca829948b33b74f8111cbb1177bed

The `view/frontend/web/js/amazon-product-add.js` file is removed but still exists in [requirejs-config.js](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/view/frontend/requirejs-config.js#L53) `map` section in v5.17.0!

**Comment by sgabhart22** [comment]
Thanks @tim-breitenstein-it ! We'll look to get this folded into the 5.17.1 patch release. I saw you opened a PR for the fix; FYI, we won't merge that into the repo directly, but will cherry pick your commit into the next release branch to retain the author information.

Thanks again,
Spencer

**Comment by sgabhart22** [comment]
Hi @tim-breitenstein-it ,

5.17.1 is now live on the Marketplace! We'll go ahead and close this issue, but feel free to open any new issues or PRs for future problems. Thanks again!

- Spencer
