### ISSUE TITLE
JavaScript errors thrown in checkout

### ISSUE THREAD

**Issue by Chevskis** [amzn/amazon-payments-magento-2-plugin#129]
Hello,

We have installed Amazon Payments 1.1.4 module on our Magento CE 2.1.8 store. Customers can successfully log in via Amazon Login, but once they proceed to the checkout page it is loaded in broken state:
![image](https://user-images.githubusercontent.com/15198469/30322849-86e0d646-97c3-11e7-9a87-5ab083c82ec5.png)

As you can see the loading wheel over shipping methods is spinning forever and it is not possible to proceed further. Chrome dev tools console reports following error:
![image](https://user-images.githubusercontent.com/15198469/30322907-bc5e6aea-97c3-11e7-86e0-5d3684751bd5.png)

After investigating this we have discovered that the issue is present because of the default PayPal Express Checkout module that Magento 2 provides. If the Pay Pal is disabled, then Amazon Payments works as expected and the checkout is successful.

There has been similar issue opened already - https://github.com/amzn/amazon-payments-magento-2-plugin/issues/22 In our case we don't use "i-ways/magento2-paypal-plus", but the default "module-paypal" that ships with Magento 2. Since the error is thrown in Amazon external script, this seems like an  issue on Amazon side.

Expected result - It is possible to finish checkout via Amazon Payments if Pay Pal is enabled.

Thanks

**Comment by danielneu** [comment]
Thanks for raising this, I'm handing this over to our experts.

Best wishes 
Daniel

**Comment by danielneu** [comment]
Hi @Chevskis ,

we are not able to replicate this on a standard Magento 2.1.8 with both Amazon Pay and PayPal enabled.
Are you using an additional checkout extension, which could be causing this?

Best wishes 
Daniel

**Comment by Chevskis** [comment]
Hi @danielneu,

Looks like it was a mistake on our end. After investigating this deeper we found out that our testing environment contained incorrect composer.lock file which resulted into Amazon Payments 1.1.3 on the server. After updating module to 1.1.4 everything is working as expected.

Thanks!
