### ISSUE TITLE
Error after installing extension

### ISSUE THREAD

**Issue by jfain189** [amzn/amazon-payments-magento-2-plugin#130]
#### What I expected
Install extension with no errors.

#### What happened instead
Error being throw whenever you visit the website through a browser. See Below:
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Amazon_Core schema: current version - 1.1.4, required version - 1.0.1
Amazon_Core data: current version - 1.1.4, required version - 1.0.1

#### Steps to reproduce the issue
Upload extension files.
Run these 3 commands:
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:flush

Visit site in browser.

#### Your setup

* Magento version: 2.1.8
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by danielneu** [comment]
HI,

I am not able to reproduce the same.
With version 1.1.4, we increased the setup_version of the Core module to 1.1.4.
This requires running _magento setup:upgrade_ after the update.

Can you make sure this was really done? The error message indicates this step might be missing.

In which mode are you running the shop? Developer, default or production?

Thanks
Daniel

**Comment by jfain189** [comment]
Hi,

Thank you for the reply. I poked around a bit and realized it was the composer library that was messed up, not the extension. I changed the version number in amzn/amazon-pay-and-login-with-amazon-core-module/etc/module.xml and now the error is gone. I have yet to test if the extension is working though so I will follow up if I run into any other issues.

**Comment by danielneu** [comment]
Thanks for the info.

Please create a new issue, if you find a different problem, feel free to reopen, if you think this is still an issue on our side.

Best wishes 
Daniel
