### ISSUE TITLE
Amazon API rest put issues

### ISSUE THREAD

**Issue by kilis** [amzn/amazon-payments-magento-2-plugin#131]
Use Amazon Pay version 1.1.4 and Magento 2.1.7 with module Magecomp_Multiflatrate.
1. Add to cart a product
2. Go to Cart
3. Login with Amazon Pay to checkout
4. Amazon Pay checkout trows and REST api error

#### What I expected
4. Go to checkout without issues

#### What happened instead
4. Amazon Pay checkout trows and REST api error
http://prntscr.com/gkzndk
http://prntscr.com/gkzoqf

#### Steps to reproduce the issue
Use amazon pay version 1.1.4
Use Magento 2.1.7
Use Magecomp_Multiflatrate extension

#### Your setup

* Magento version:2.1.7
* Magento Edition: Community 
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process

**Comment by danielneu** [comment]
Hi @kilis 

thanks for raising this.
Can you share:

* more information (e.g. link to the 3p extension) about  Magecomp_Multiflatrate
* logs (even more essential than the link to the extension)

Best wishes 
Daniel

**Comment by kilis** [comment]
Send in mail!

**Comment by danielneu** [comment]
Thanks, handing this over for review.

Best wishes 
Daniel

**Comment by RayAnaya** [comment]
Hello,

We are going to mark this issue as closed, as there have been a number of upgrades and new versions since it was initially reported.  Please feel free to re-open this issue if you continue to experience the issue with newer versions.
