### ISSUE TITLE
Notice: Undefined property Email.php on line 77

### ISSUE THREAD

**Issue by clickdigitalinteractive** [amzn/amazon-payments-magento-2-plugin#134]
Found this in report logs:
a:4:{i:0;s:173:"Notice: Undefined property: Amazon\Payment\Helper\Email::$coreHelper in /home/vendor/amzn/amazon-payments-magento-2-plugin/src/Payment/Helper/Email.php on line 77";i:1;s:12136:"#0 /home/vendor/amzn/amazon-payments-magento-2-plugin/src/Payment/Helper/Email.php(77): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/home/..', 77, Array)

It's happening every hour on the :50 min mark. + or -.

line 77 is:
 $storeName = $this->coreHelper->getStoreName(ScopeInterface::SCOPE_STORE, $order->getStoreId());

**Comment by danielneu** [comment]
Thanks for reporting, I found the issue and am preparing a PR for this.

**Comment by danielneu** [comment]
This is now available in version 1.1.5
