### ISSUE TITLE
Remove "invalid_grant" message in the browser console

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#14]
Remove "invalid_grant" message in the browser console which is written to the console, if a customer has not yet signed-in with Amazon

**Comment by EmilyPepperman** [comment]
Thanks Daniel... overall it seems Amazon "phones home" more than it needs to and hurts site performance a bit. thanks for all your help!

**Comment by danielneu** [comment]
Hi @EmilyPepperman 

the module only "phones home" for one reason, making the customer experience as smooth as possible.
There is no data transmitted to Amazon which is not related and needed to place an order with us.

The only communication not related to the checkout is a quick check, if a session with Amazon Payments already exists, thus saving the customers precious clicks, which will benefit the completion rate for merchants on the other hand as well.
