### ISSUE TITLE
amazon_config error in var/report 

### ISSUE THREAD

**Issue by salikahmed** [amzn/amazon-payments-magento-2-plugin#145]
Hello

I have installed magento2 ECE 2.1.6 installed amazon pay, with multi-websites, I keep observing one error in var/reports  amazon_config, when migrated customer try to log in its keep generate error report and cloud go 503 , I have setup backend setting website level on both sites and disable the config settings from global configuration didn't get why it's not loading the amazon config settings also i have installed fastly module with VCL upload on the backend, 

additional if I try with a new customer and try to place order its works order successfully 

a:4:{i:0;s:37:"Object DOMDocument should be created.";i:1;s:12118:"#0 /app/lnyj4fqgvkney/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
#1 /app/lnyj4fqgvkney/vendor/magento/module-ui/Model/Manager.php(258): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 /app/lnyj4fqgvkney/vendor/magento/module-ui/Model/Manager.php(166): Magento\Ui\Model\Manager->prepare('amazon_config')
#3 /app/lnyj4fqgvkney/vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('amazon_config')
#4 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('amazon_config', NULL, Array)
#5 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'amazon_config', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /app/lnyj4fqgvkney/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /app/lnyj4fqgvkney/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /app/lnyj4fqgvkney/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()

Please any solution to resolve this issue very helpful for me 

Thanks
Salik

**Comment by danielneu** [comment]
Hi @salikahmed,

I am not exactly sure if I understand the complete issue.

Can you explain what you mean with "migrated customer"?
Where do you get the 503? For the customer trying to log in, meaning the shop is than broken for this customer?
Can you share screenshots, where the URL the customer receives the error is visible and the browser console as well?

I also don't understand this part:  
"I have setup backend setting website level on both sites and disable the config settings from global configuration didn't get why it's not loading the amazon config settings also i have installed fastly module with VCL upload on the backend,"

Are you able to re-phrase to help me understand all details of your issue?

Thanks,
Daniel
