### ISSUE TITLE
Non-numeric value, composer update

### ISSUE THREAD

**Issue by gewaechshaus** [amzn/amazon-payments-magento-2-plugin#153]
Hey guys,

today we are facing the following issue while doing a composer update to the latest dev version

   [ErrorException]
   A non-numeric value encountered

Greetings
Jan

**Comment by danielneu** [comment]
@gewaechshaus can you share more details?

Please update composer: `php composer.phar self-update `
Please run composer in verbose mode `php composer.phar update -vvv`
Please share the require section for Amazon Pay of your composer.json

Thanks,
Daniel

**Comment by gewaechshaus** [comment]
Hi @danielneu,

can be closed as it was related to the composer version. After self-updating the issue was gone.

Greetings,
Jan
