### ISSUE TITLE
Performance taken a step backwards in 1.2.0

### ISSUE THREAD

**Issue by EmilyPepperman** [amzn/amazon-payments-magento-2-plugin#155]
I expected performance to stay the same if not better in 1.2.0

After updating to 1.2.0 we have added a second to our load time with this file... is this new? Is this minicart?
URL: https://www.divegearexpress.com/customer/section/load/?sections=cart&update_section_id=false&_=1509403715655

* Magento version: M 2.1.9
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : www.divegearexpress.com

**Comment by danielneu** [comment]
Hi Emily,

changes from 1.1.5 to 1.2.0 concentrated on compatibility (composer) and the removal of some options.
See for yourself: https://github.com/amzn/amazon-payments-magento-2-plugin/compare/1.1.5...1.2.0

No changes that could cause any additional delays.

Best wishes 
Daniel

**Comment by EmilyPepperman** [comment]
Hi @danielneu Can you help me with explaining what this file is? Is it part of the Amazon Pay extension or something else?

 https://www.divegearexpress.com/customer/section/load/?sections=cart&update_section_id=false&_=1509403715655

This is what is causing a longer load time. 

thanks!

**Comment by danielneu** [comment]
Hi @EmilyPepperman 

this all looks like mini cart.
Did you investigate deeper what is causing the additional delays? I also see PayPal/ Braintree in there.
Did you check with deactivating both, Amazon pay and PayPal and then checking the load time and compare it to the time needed when the one, the other or both are active?

As I said, we introduced nothing which can impact the load time from 1.1.5 to 1.2.0.

If you agree, I would close this issue, as I don't see how we could be causing this for you.
However, we can keep the issue to discuss and I'm happy to help where I can.

Best wishes 
Daniel

**Comment by EmilyPepperman** [comment]
ok you can close for now... we can't for sure determine where this issue is coming from and are still investigating.
