### ISSUE TITLE
Amazon payment widget  missing in checkout page

### ISSUE THREAD

**Issue by adarshedi** [amzn/amazon-payments-magento-2-plugin#156]
Hello,
I have installed the module and set all configuration, in the backend as well as in the Sellercentral. When i test in the sandbox mode, I get in the second step no way to select Amazon payment widget.

Payment with Amazon and login with Amazon is activated. i didn't installed iWays PayPal Plus. But symilar problem like #22  

**Step 1:** 
![larsson jennings - checkout](https://user-images.githubusercontent.com/33274491/32260267-aac02f6c-beec-11e7-9060-fa1be69c9190.png)

**Step 2:**

![screenshot from](https://user-images.githubusercontent.com/33274491/32261980-fd2b68f6-bef7-11e7-80db-f1b8512b1784.jpg)

No script error found in chrome console. Can you help me?

Thanks and regards

Adarsh

#### Your setup

* Magento version: 2.1.7
* Magento Edition: Community 
* Amazon pay extension version : 1.2.0
* Shop URL :

**Comment by danielneu** [comment]
Hi,

are you using any kind of checkout extension?

Best wishes 
Daniel

**Comment by adarshedi** [comment]
HI

No I didn't install checkout extension

Thanks

**Comment by adarshedi** [comment]
Hi

Disabled and checked

![larsson jennings checkout 2](https://user-images.githubusercontent.com/33274491/32426398-19d0e51c-c2e0-11e7-8dd7-aed2d940cd80.png)

Thanks
Adarsh

**Comment by adarshedi** [comment]
Hi,

When i check on paywithamazon.log file i found this
```xml
<GetOrderReferenceDetailsResult>
    <OrderReferenceDetails>
      <OrderReferenceStatus>
        <State>Draft</State>
      </OrderReferenceStatus>
      <OrderLanguage>en-GB</OrderLanguage>
      <Destination>
        <DestinationType>Physical</DestinationType>
        <PhysicalDestination> REMOVED </PhysicalDestination>
      </Destination>
      <ExpirationTimestamp>2018-05-05T04:15:55.481Z</ExpirationTimestamp>
      <IdList/>
      <PlatformId>A2ZAYEJU54T1BM</PlatformId>
      <Constraints>
        <Constraint>
          <ConstraintID>PaymentPlanNotSet</ConstraintID>
          <Description>The buyer has not been able to select a Payment method for the given Order Reference.</Description>
        </Constraint>
      </Constraints>
      <SellerOrderAttributes>
        <StoreName>English</StoreName>
        <CustomInformation>Magento Version : 2.1.7 Plugin Version : 1.2.0</CustomInformation>
        <SellerOrderId>2000018095</SellerOrderId>
      </SellerOrderAttributes>
      <OrderTotal>
        <CurrencyCode>GBP</CurrencyCode>
        <Amount>765.00</Amount>
      </OrderTotal>
      <Buyer> REMOVED </Buyer>
      <ReleaseEnvironment>Sandbox</ReleaseEnvironment>
      <AmazonOrderReferenceId>S02-5520126-7932985</AmazonOrderReferenceId>
      <CreationTimestamp>2017-11-06T04:15:55.481Z</CreationTimestamp>
      <RequestPaymentAuthorization>false</RequestPaymentAuthorization>
    </OrderReferenceDetails>
  </GetOrderReferenceDetailsResult>
  <ResponseMetadata>
    <RequestId>2a1e76a7-1e5d-4962-ba2f-5b4639012a6d</RequestId>
  </ResponseMetadata>
</GetOrderReferenceDetailsResponse>

**Comment by danielneu** [comment]
Hi @adarshedi 

to be sure I get this right:
Disabling the Adyen extension still leaves Amazon Pay in a non-functional state?

The log entry is normal in your situation, it simply means you did not select a payment instrument using our widget. As the widget is not surfacing, this is no surprise and to expect.

Can you share access to a staging environment? You can share it with us via email: payments-cp-devel@amazon.com

Best wishes 
Daniel

**Comment by adarshedi** [comment]
Hi @danielneu 

I found the issue.  We have installed a Magebright extension called  SHIPPING AND PAYMENT METHOD BY CUSTOMER GROUP. I enabled amazon pay from options and it's working fine.

Thanks
Adarsh
