### ISSUE TITLE
Need update for Magento 2 CE 2.2.*

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [amzn/amazon-payments-magento-2-plugin#157]
Recently Magento Release new Version of Magento CE 2.2.1 and current version of Amazon Pay is only support Magento CE 2.1.* 
So please update extension as per Magento New release and support Macento CE 2.1.* and 2.2.* 

#### Your setup

* Magento version:
* Magento Edition: Community / Enterprise / Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by danielneu** [comment]
Hi,

version 1.2.0 of our extension is compatible with Magento 2.2.x.
You can update to the newest version using composer, please see the guide for more information.
https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#manual-composer-install-method

Best wishes 
Daniel
