### ISSUE TITLE
[Discussion] [Support needed] Workaround to place multiple Amazon Pay buttons on same page

### ISSUE THREAD

**Issue by hellboy81** [amzn/amazon-payments-magento-2-plugin#161]
All the amazon payment elements are referenced with `id`. Is there shop sample with this plugin or may be with another plugin provided by `best it` for Oxid which can crack this issue.

**Comment by danielneu** [comment]
Hi,

can you elaborate on the actual use case you are trying to solve?
Ids in this extension are created dynamically, it is e.g. possible to have an Amazon Pay button in the mini cart and the cart at the same time. This was introduced in #123 

What is the reference to best it about? Please add more information on the issue you are facing and the relation to Magento 2.

Thanks
Daniel

**Comment by hellboy81** [comment]
Use case: another self made shop (Magento- and  Oxid-free ;-) )

Issue: In most standard e-commerce solutions `Pay with Amazon` button should be placed usually **with** standard shop button `Pay`.

I have unusual case: it should be placed `Pay with Amazon` button _instead of standard Pay button_ in **multiple places** .

**Comment by hellboy81** [comment]
See screenshot:

![3 Buttons should be replaced](http://i.imgur.com/FE3ADAz.png "This buttons are black")

**Comment by danielneu** [comment]
Hi,

I personally would solve this using css classes and in JS collect all divs that should be Amazon Pay buttons via getElementsByClassName and iterate over the returned set and get the ids of the elements to create the buttons.

In the end, you will need an id for the HTML element - no other possibility.

Closing this issue now as unrelated to Magento 2.
Hope the information helps to get you going.

Best wishes 
Daniel
