### ISSUE TITLE
Amazon pay button is not visible

### ISSUE THREAD

**Issue by balwant20** [amzn/amazon-payments-magento-2-plugin#162]
In case of Non-Us country, Amazon pay button is not displayed on Cart page.
means onec user come on my website and change country from US to another like spain, then the Amazon pay button is not visible on cart page.
i am using Amazon module-1.2.0 & magento 2.1.7

**Comment by danielneu** [comment]
Hello,

if the currency changes as well, this is the intended behavior.
In order to also offer Amazon Pay for Europe, you will need an account for the desired currency and configure it in the matching store view.

Best wishes 
Daniel

**Comment by balwant20** [comment]
thanks @danielneu ...!!!!!

**Comment by balwant20** [comment]
hello @danielneu ,
now we change our  website from magento 1.7 to magento 2.1.7 and i use your extension Amazon pay for payment. i have 3 diffrent diffrent merchant account in US,UK,canada. but in admin panel setting we can only select one region .so in this case how can i manage other country user payments.
in fact in magento 1 my website accept payment from all over user.so i didn't understand what's going on?can you plz help me out this problem?

thanks @danielneu

**Comment by danielneu** [comment]
hi @balwant20 

I guess you have different stores, store fronts, ... configured in Magento 2.
The Amazon Pay configuration can be done per configuration scope.

You will have to set the configuration (https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#payment-region) of the payment-region to the locale your account is registered in.
If the store accepts GBP and you set the payment region to United Kingdom, then the button will be surfaced.

If this does not help or answer all questions, let me know, and I will out you in touch with our support agency.

Best wishes 
Daniel
