### ISSUE TITLE
return to standard checkout 

### ISSUE THREAD

**Issue by balwant20** [amzn/amazon-payments-magento-2-plugin#163]
when user click "return to standard checkout" link on onestepcheckout page and it redirect to the standard checkout page but there is no payment options see in the payment option.when user refresh the current page ,in this case only user can see payment option like COD,Braintree,Paypal otherwise these mehtod not shown.
anyone can help me out this problem?
Thanks in advance...!!!!!!

**Comment by danielneu** [comment]
Hi,

please update to version 1.2.1. 
This was resolved by #159 

Best wishes 
Daniel

**Comment by balwant20** [comment]
thanks @danielneu .how can i update from version 1.2.0 to 1.2.1.
amazon pay 1.2.1 is available on https://marketplace.magento.com or not?

**Comment by danielneu** [comment]
Hi,

version 1.2.1 is currently on it's way to the marketplace. If you cannot get it vi a usual update procedure, you can also simply change the version in the composer.json file to 1.2.1 for our extensions.

More help can be found here: https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html

Best wishes 
Daniel

**Comment by balwant20** [comment]
thanks @danielneu
