### ISSUE TITLE
Is is possible to change the pay button style?

### ISSUE THREAD

**Issue by sambolek** [amzn/amazon-payments-magento-2-plugin#168]
#### What I expected

Button is displayed in accordance to Amazon API documentation https://pay.amazon.com/us/developer/documentation/lpwa/201953980 http://prntscr.com/hn63x0

#### What happened instead

The button that gets displayed always has "old" amazon style https://prntscr.com/hn63gh

#### Your setup

* Magento version: 2.2.1
* Magento Edition: Community
* JavaScript Console: not relevant
* Shop URL : 

Is it even possible to get a new button style displayed? Since buttons are always pulled via amazon service (presume that can't/shouldn't be changed to our own images), believe we should have some sort of option where we can choose the button style (not only color/size).

Is there any option we can change? If not, how would we pull a different image for "Pay" button?

**Comment by danielneu** [comment]
Hi,

this is no issue, this is the intended button image for now. I'm sorry it is not inline with our documentation currently. 

There is currently no option to request a different image, I'm afraid.

Best wishes 
Daniel

**Comment by sambolek** [comment]
Hi Danijel,

thanks for a quick response. Can we expect this to be configurable in the near future? 

Also, if we find a way to change this image to the one from documentation via some other way, would such practice be legal?
