### ISSUE TITLE
pay with amazon button is not displayed on cart page for country switch

### ISSUE THREAD

**Issue by balwant20** [amzn/amazon-payments-magento-2-plugin#172]
when user came  on my website,if user selected US country then user can see apmazon pay button on cart page because of i selected US in admin panel setting.if they switch another country then they can not find amazon pay button on cart page.can anyone figure out the soluation?

thanks in advance...!!!!!!!!

**Comment by danielneu** [comment]
Hello,

I answered this to you in #162 .

If you want to offer Amazon Pay for other currencies, you will need accounts for those currencies (EUR, GBP) and configure the extension accordingly.

Best wishes 
Daniel

**Comment by balwant20** [comment]
hello @danielneu ,
now we change our website from magento 1.7 to magento 2.1.7 and i use your extension Amazon pay for payment. i have 3 diffrent diffrent merchant account in US,UK,canada. but in admin panel setting we can only select one region .so in this case how can i manage other country user payments.
in fact in magento 1 my website accept payment from all over user.so i didn't understand what's going on?can you plz help me out this problem?

thanks @danielneu
