### ISSUE TITLE
Uncaught TypeError: The checkout page is not loading on Magento 2.2.2

### ISSUE THREAD

**Issue by lizenial** [amzn/amazon-payments-magento-2-plugin#173]
The checkout page is not loading after enabling Amazon Pay extension. The blank page got Uncaught TypeError.

![amazonpay-ultimo-checkuot-error](https://user-images.githubusercontent.com/19967294/34483688-8f9a954a-f003-11e7-887e-5a168129bc15.JPG)

Uncaught TypeError: Cannot read property 'after' of null (in the case of Ultimo theme)

    at Object.insert (eval at require.load (static.min.js:9), <anonymous>:7:48)

    at eval (eval at require.load (static.min.js:9), <anonymous>:4:97)

    at Array.map (<anonymous>)

    at UiClass.insertChild (eval at require.load (static.min.js:9), <anonymous>:4:7)

    at eval (eval at require.load (static.min.js:9), <anonymous>:28:103)

    at Registry._resolveRequest (eval at require.load (static.min.js:9), <anonymous>:17:439)

    at Array.forEach (<anonymous>)

    at Registry._updateRequests (eval at require.load (static.min.js:9), <anonymous>:17:235)

    at later (eval at require.load (static.min.js:9), <anonymous>:42:255)

Uncaught TypeError: Cannot read property 'after' of null (in the case of Luma theme)

    at Object.insert (arrays.js:122)

    at collection.js:94

    at Array.map (<anonymous>)
 
    at UiClass.insertChild (collection.js:91)

    at layout.js:404

    at Registry._resolveRequest (registry.js:418)

    at Array.forEach (<anonymous>)

    at Registry._updateRequests (registry.js:400)

    at later (underscore.js:821)

#### What I expected

The checkout page is working and the user can pay with Amazon pay.

#### What happened instead

Tested in the sandbox mode. Actually, Amazon login was working, but the checkout page went blank after logging in. The page was not loading, got Uncaught TypeError.

#### Steps to reproduce the issue

I installed Amazon Pay extension 1.2.4 via composer and configured the module according to this [guide](https://amzn.github.io/amazon-payments-magento-2-plugin/index.html).
Tested on Ultimo theme and Luma theme. However, Amazon Pay did not work on the both of themes.
The checkout page started to work again after disabling Amazon Pay extension in both cases.

#### Your setup

* Magento version: 2.2.2
* Magento Edition: Community
* PHP: 7.1

cd path/to/magento installed root
php composer.phar require amzn/amazon-payments-magento-2-plugin:^1.2.4
php bin/magento module:enable Amazon_Core Amazon_Login Amazon_Payment
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
php bin/magento cache:clean
php bin/magento cache:flush

At first, I assumed Amazon Pay extension is not compatible with Ultimo theme. However, I tested on Luma theme with clean installed Magento 2.2.2 and got the very similar error.
Could you please check again the compatibility with Magento 2.2.2 version?

**Comment by danielneu** [comment]
HI @lizenial ,

thanks for the detailed error description. I will hand this over to our experts.

Can we get access to your staging system? This seems to be the best and fastest way to get this resolved.
If so, can you please share details to access the system via payments-cp-devel@amazon.com and mention this issue please?

Best wishes 
Daniel

**Comment by clarah31** [comment]
A big problem is the definition of "isFormInline" as observable.
In the basis method, this is defined as a normal variable.
In shipping. html it is also used as variable 
<! -- ko if:  (! isFormInline) -->


Basis method Magento 2.2.2:
vendor\magento\module-checkout\view\frontend\web\js\view\shipping.js
Line: 69
isFormInline: addressList().length === 0,

Please check the definition and use of "isFormInline"
Commit 8c040d9
amazon-payments-magento-2-plugin/src/Payment/view/frontend/web/js/view/shipping.js
Line 29: isFormInline: ko.observable(addressList().length == 0),
Line 58: this.isFormInline(true);
Line 91:if (this.isFormInline()) {

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
