### ISSUE TITLE
Issue when upgrading store in Magento 2.2.2

### ISSUE THREAD

**Issue by jfain189** [amzn/amazon-payments-magento-2-plugin#174]
#### What I expected
No errors when running upgrade processes.

#### What happened instead
Error when running upgrade processes.

#### Steps to reproduce the issue
upload files from src directory from github to app/code/Amazon on my magento website.
Run these 2 lines in command line:
php bin/magento setup:upgrade (no error)
php bin/magento setup:di:compile (error attached)

#### Your setup

* Magento version: 2.2.2
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : 

![amazon](https://user-images.githubusercontent.com/12579419/34500226-d28d50e4-efd7-11e7-878c-5c61b423cdb3.JPG)

Please let me know what I can do to fix this!

**Comment by prayagr** [comment]
Hi @jfain189 , thanks for reaching out. This issue seems similar to issue #67 

Please review Daniel's response in #67 and let us know if that helped in resolving the issue.

**Comment by danielneu** [comment]
Hi @jfain189 

are yous till facing this? Have you checked Prayag's suggestion above?

Best wishes 
Daniel

**Comment by jfain189** [comment]
No, your guide worked. Thank you Daniel. You can close this ticket.
