### ISSUE TITLE
Missing required province/state blocks orders

### ISSUE THREAD

**Issue by ebaschiera** [amzn/amazon-payments-magento-2-plugin#175]
Hello,
in our setup we have configured several countries with required state/province in shipping/billing address.
Amazon apparently doesn't require its customers to save state/province in their address, so the order cannot be placed. The customer gets the following error: 

`Please check shipping address information. Please enter the state/province.`

Please see the attached screenshot.

![manila - wallet widget page](https://user-images.githubusercontent.com/5667462/34723646-a7b03782-f54b-11e7-9860-6bbf6d33f0ac.png)

In my opinion, the module should deal with this case, asking the customer to enter the state/province if it's missing from his/her Amazon address and if it's required.

I cannot contribute with a fix, but I wanted to make developers aware of this issue.

Thank you.

Best regards.

**Comment by lemked** [comment]
Re-opened as we reverted this fix in 1.2.6 as it was potentially breaking the standard checkout of M2. Investigating alternatives.

**Comment by lemked** [comment]
As described in #242 , this issue should not occur anymore with Magento 2.2.4 or higher. The problem was actually in the Magento core, so we will not provide a bug fix in our extension.

Closing.

**Comment by ebaschiera** [comment]
Hi,
apologies for reopening the issue, but we are having the same issue on Magento 2.3.2.
This time the issue is even worse, because Magento crashes badly on order placement, when visiting the following url: /amazonpayments/payment/completecheckout/?AuthenticationStatus=Success

The error reported is `Please check the shipping address information. "regionId" is required. Enter and try again.`

The payment is registered, but the order fails to be saved. So that's a pretty bad situation.

Would you mind doing another check?

Thanks. Regards.

**Comment by christianzichichi** [comment]
Hi @ebaschiera,

thanks for reporting this. We'll look into it with priority and report back here

Thanks
Regards

Christian

**Comment by christianzichichi** [comment]
@ebaschiera 

can you please provide merchant details like merchant Id, orderIds and relevant Amazon Pay and Magento logs for the issue at hand (and amazon pay plugin version) at payments-cp-devel@amazon.com?

Thank you
Christian

**Comment by christianzichichi** [comment]
Hi @ebaschiera,

My apologies for the delay, but we wanted to make sure we had the right fix for your issue.  this patch will solve it.

This work around will disable required-field validation on shipping addresses for Amazon Pay orders:

https://github.com/BearGroup/amazon-payments-magento-2-plugin/commit/e7027c3f8e688881fa950a216dbda2ad8269f0f6.patch

In the next plugin releases, we'll include a way to collect the additional required fields during the Shipping Address step.  (We already have this for the Telephone Number field;  we will generalize it to apply to all required fields).

Thanks
Regards

Christian

**Comment by ebaschiera** [comment]
Hi @christianzichichi ,
thanks, your patch works and Magento doesn't crash anymore.

Collecting the additional fields would be awesome, so I am looking forward to test the new release :)

Thanks.
Best regards.

Ermanno
