### ISSUE TITLE
System -> IPN Triggers 404

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#178]
#### What I expected

Clicking the ***IPN*** link under the ***System*** menu triggers the download of the IPN log.

#### What happened instead

I am redirected to a 404 error page.

#### Steps to reproduce the issue

* Setup a clean instance of M2. 
* Install Amazon Pay extension
* Click the IPN Log link

#### Your setup
Magento 2.2.2 Community
JavaScript Console: 
![ipnlogerror](https://user-images.githubusercontent.com/1476371/35029594-86a98122-fb10-11e7-84c1-51918f877069.png)

**Comment by islandskater43** [comment]
Need to confirm behavior when IPN log doesn't exist yet due to not yet receiving any IPNs. Perhaps this is expected?

**Comment by islandskater43** [comment]
Confirmed that this is behaving properly, albeit in an unexpected manner. Will create a feature request to improve the behavior.

**Comment by islandskater43** [comment]
Confirmed that w/ the latest version of the extension (2.0.3) on Magento 2.2.4, the IPN log download feature works when the `{magento_root}/var/log/amazonipn.log` file exists. However, when the file does not exist (ie, no IPNs have been logged), the 404 error is displayed. Rather than going through the process of getting the IPNs setup and triggering one, you can see the behavior work as expected by executing the following:

`$ echo test > {magento_root}/var/log/amazonipn.log`

Clicking the IPN link in the system menu now will successfully download the file. Deleting the same file and then trying to click the link again will reintroduce the 404 behavior.

Two changes will be made to address this issue:
- The *Client* and *IPN* log download links will be moved from the System menu to the Amazon Pay advanced tab
- The download functionality will be disabled when a file does not exist to avoid 404 errors and improve the merchant experience

**Comment by prayagr** [comment]
Removed the links from the menu and then added a dynamic list of available logs (based on file being there or not) to developer log section in 3.x (master)

**Comment by prayagr** [comment]
We will close this issue when the fix is included in a release

**Comment by prayagr** [comment]
Closing this since 2.2.6 is released.
