### ISSUE TITLE
v2.1.10 Mini-Cart Amazon Pay button does not appear:

### ISSUE THREAD

**Issue by tadhgbowe** [amzn/amazon-payments-magento-2-plugin#183]
Magento v2.1.10.

#### What I expected

Added something to basket. Go to home page. The mini cart overlay in the header should display the Amazon Pay button.

#### What happened instead

The Amazon Pay button does not display. This only happens on page cached pages i.e. CMS, Category & Product pages.

#### Steps to reproduce the issue

Add something to basket. Go to home page. Click on header basket icon. The mini-cart overlay displays no Amazon Pay button.

#### Your setup

* Magento version: 2.1.10
* Magento Edition: Commerce ( Enterprise )
* JavaScript Console: All works fine on non page cached pages e.g. basket page, account login page. So it's just a page caching issue.
* Shop URL: I've contacted you via email directly with URLs.

I think the above explains it all quite well. 

The version of the Amazon Pay module installed is:
amazon/module-login-and-pay - "version": "1.0.9"

We have another client who has also been upgraded to 2.1.10 and their site works fine. The only differences are they are Open Source (community) and the extension version installed is "version": "1.1.1"

So we're wondering if we upgrade our problem site to 1.1.1 perhaps this will fix it?

Thanks,
Tadhg

**Comment by prayagr** [comment]
Hi @tadhgbowe , I don't think I have seen this issue before but we have made a host of changes from v1.0.9 to our current v1.2.4. The minicart functionality has been improved and I would recommend upgrading to the latest version. 

Please let us know if that helps fix your problems.

Thanks,
Prayag

**Comment by prayagr** [comment]
Closing this for now, please reopen if required
