### ISSUE TITLE
Compatibility with 2.2 branch of Magento

### ISSUE THREAD

**Issue by korostii** [amzn/amazon-payments-magento-2-plugin#185]
#### What I expected

I expected that this module is compatible with Magento's 2.2.x branch

#### What happened instead

There are reports saying it's not compatible with Magento 2.2.0 CE: https://github.com/magento/magento2/issues/11400

#### Question

Please clarify whether the plugin is ready for Magento 2.2 and\or tested on 2.2.x releases
It would also be helpful if you could also announce the earliest module version which is compatible (or planned to be compatible, if it's a future version) with Magento 2.2

**Comment by islandskater43** [comment]
Resolving this, as we've patched the issue referenced in magento/magento2#11400.
