### ISSUE TITLE
'An error occurred on the server.  Please try to place the order again'

### ISSUE THREAD

**Issue by wittness87** [amzn/amazon-payments-magento-2-plugin#186]
#### What I expected

Select Amazon Pay button, log in to Amazon, then place order and see order success page

#### What happened instead

Select Amazon Pay button, log in to Amazon, hit place order button and server error appears.

#### Steps to reproduce the issue

1.  Select any product on the website
2.  Hit 'pay with Amazon' button
3.  Successfully redirected to Amazon to log in to Amazon account
4.  Redirected to website to checkout page
5.  Amazon pay is selected as payment by default but no address details appear.
6.  Hit the 'place order' button and error message 'An error occurred on the server.  Please try to place the order again'.    Screenshot below:
    https://gyazo.com/549c35002b6c239abf54a39393aba6e3

Javascript console errors are as follows:
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
(index):108 Uncaught SyntaxError: Invalid or unexpected token
/pub/static/frontend/ControllerModz/ControllerModz/en_GB/jquery/jquery-migrate.js:21 JQMIGRATE: Logging is active
/pub/static/frontend/ControllerModz/ControllerModz/en_GB/jquery/jquery-migrate.js:41 JQMIGRATE: jQuery.browser is deprecated
migrateWarn @ /pub/static/frontend/ControllerModz/ControllerModz/en_GB/jquery/jquery-migrate.js:41
/pub/static/frontend/ControllerModz/ControllerModz/en_GB/jquery/jquery-migrate.js:43 console.trace
migrateWarn @ /pub/static/frontend/ControllerModz/ControllerModz/en_GB/jquery/jquery-migrate.js:43
/rest/default/V1/guest-carts/23cb952dcad9bda9dcb664af5a7397ce/payment-information Failed to load resource: the server responded with a status of 400 ()

https://gyazo.com/4ce0be4f3e6d04fc0c66407165cca425

#### Your setup

* Magento version: 2.1.8
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by danielneu** [comment]
Hi,

thanks for getting in touch and the detailed information.

Looking at the provided screenshot, our widget is not being displayed, I guess this is the same for the address.

This is usually the case, if the theme used is not based on Blank or Luma. Are you by any chance using a custom theme?
Can you check in our guide's FAQ section, if that helps you to get the required CSS created and loading?

https://amzn.github.io/amazon-payments-magento-2-plugin/faq.html

Best wishes 
Daniel

**Comment by prayagr** [comment]
Closing this ticket as it seems the problem is due to a custom theme and can be addressed by reviewing https://amzn.github.io/amazon-payments-magento-2-plugin/faq.html. Please reopen if the issue is related to the core extension.
