### ISSUE TITLE
Cannot use login with Amazon Pay on Surface or Android browsers

### ISSUE THREAD

**Issue by MicheleBeargroup** [amzn/amazon-payments-magento-2-plugin#188]
#### What I expected
Went to http://www.helmpublishing.com and attempted to log in with Amazon account using a Win 10 Surface Edge, FireFox and Chrome and Amazon Fire Silk browser.

#### What happened instead
Received a 404 with no popup and in some cases indication that site's return URL was not whitelisted even though there is no such error in other operating systems and browsers.

#### Steps to reproduce the issue

Attempt to log into an a site using M2 extension on a Windows Surface browser or Android browser.

#### Your setup

2.1
Any version
http://www.helmpublishing.com
 (will add screenshots from Surface in updated tickets)

**Comment by islandskater43** [comment]
@MicheleBeargroup - can you confirm if this was an issue on Android devices, or just Fire devices that use the Silk browser? 

Login logic used to determine authentication flow is here: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/58fa9f89ad539d58036ee78fc7515b60d7a6536d/src/Payment/view/frontend/web/js/amazon-button.js#L98

**Comment by prayagr** [comment]
Tested ap2 and ap3 login with Android and Surface device and was not able to repeat the issue we were seeing back when this ticket was logged initially.
