### ISSUE TITLE
Adjust Pop-up / Redirect Logic

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#196]
#### What I expected

When I click the Amazon Pay button and am on a desktop device / browser and the page is served over HTTPS, regardless of the type of page I'm on, I expect to be presented with the pop-up login window.

#### What happened instead

I am presented with the redirect login flow from the PDP.

#### Steps to reproduce the issue

Setup fresh instance, display Amazon Pay on PDP, visit a PDP over HTTPS on a desktop device, and click Amazon Pay.

#### Your setup

* Magento version: 2.2.2
* Amazon Pay Extension version: 1.2.4
* Magento Edition: Community
* JavaScript Console: No JS Errors
* Shop URL : N/A / Reproducible w/ fresh install

#### Current Behavior
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/58fa9f89ad539d58036ee78fc7515b60d7a6536d/src/Payment/view/frontend/web/js/amazon-button.js#L98

The auth flow logic appears flawed; there was an assumption made that the PDP should always experience the redirect flow (`!$('body').hasClass('catalog-product-view')`). However, this was predicated on the idea that the PDP could be served via HTTP; but this is already covered in the first condition - `window.location.protocol === 'https:'`.

#### Recommended Fix
Remove any check around the PDP page. Use the popup flow when the page is served via HTTPS and to a desktop device.

```javascript
return (window.location.protocol === 'https:' && !_this._touchSupported());
```

**Comment by danielneu** [comment]
Hi @islandskater43 

iirc, this was a decision we made during the initial development, not something that slipped through.
No reason to not have it changed, but I'll try to find out what made us go this way.

Best wishes 
Daniel

**Comment by islandskater43** [comment]
@danielneu - @tarishah and I discussed further. I need to modify this ticket. Assigning to myself and flagging for additional investigation.

**Comment by joshdavenport** [comment]
We're seeing that the redirect after login when initiating Amazon Pay checkout from PDP simply doesn't work. Can't work out if that is a side effect of this or if I'm misreading this issue? Do you see no redirect after the (non-popup) login flow @islandskater43 

@danielneu do you know if what I'm describing lines up with anything you've seen/heard?

**Comment by joshdavenport** [comment]
Actually, right now we're actually seeing the redirect not happen at all. From my initial research testing the following on the redirect page (/amazon/login/processAuthHash/) ends up not logging anything:

```
require(['amazonCore'], function (amazonCore) {
    amazonCore.verifyAmazonLoggedIn().then(function (loggedIn) {
        console.log(loggedIn);
    });
});
```

So it looks like [this promise (src/Payment/view/frontend/web/js/amazon-core.js#L100)](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/view/frontend/web/js/amazon-core.js#L100) never resolved, meaning [this is never called (src/Login/view/frontend/web/js/amazon-redirect.js#L51)](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Login/view/frontend/web/js/amazon-redirect.js#L51)

**Comment by jonahellison** [comment]
Using a pop-up instead of the redirect is actually a bit more complicated since the Amazon Pay button also adds the product to the cart, which requires validation (e.g. to make sure customer selected correct options) and an Ajax callback (to make sure product was added to cart). Browsers block any pop-up windows that are not directly triggered by a click event, so a pop-up cannot be created after the product is added to the cart.

A clean user experience is needed for this since the customer is selecting product quantity and options on this page. For example, to use a pop-up it would need to save what the customer has selected, redirect back to the product page after logging in, rebuild the form state, try to add the product to the cart, then redirect to checkout. Using the current redirect flow might be best.

**Comment by prayagr** [comment]
The implementation has since changed. @joshdavenport , I know it's been a while, but do you know if you still see this issue?

**Comment by prayagr** [comment]
No worries @joshdavenport , thanks for the update.

I am closing this issue - the implementation has since changed with the introduction AP2.1.0 and the accompanying payment gateway changes. Please reopen if this is encountered again.
