### ISSUE TITLE
Magento 2.2.2 Varnish issue

### ISSUE THREAD

**Issue by jfain189** [amzn/amazon-payments-magento-2-plugin#200]
#### What I expected
Install and enable amazon pay, website loads with no issues.

#### What happened instead
Error 503 Backend fetch failed
Varnish cache server

#### Steps to reproduce the issue
composer require amzn/amazon-payments-magento-2-plugin:^1.2.5
php bin/magento module:enable Amazon_Core Amazon_Login Amazon_Payment
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento cache:flush

reload website over http (the port varnish is using)

#### Your setup

* Magento version: 2.2.2
* Amazon Pay Extension Version: 1.2.5
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : http://108.175.2.48

I use 1&1 server images created by bitnami which comes with varnish preconfigured. I was trying to build a new server as part of a server migration and I kept getting the 503 error listed above. The website loads over https with no problem. I am sure this is an issue with amazon pay as the error only happens when I enable the extension. If I disable the extensions the 503 error stops.

**Comment by prayagr** [comment]
Hi @jfain189 , sorry for the late response. HTTPS is a requirement for Amazon Pay to work - can you confirm if you were trying to to use Amazon Pay on HTTP?

**Comment by prayagr** [comment]
Closing due to lack of response
