### ISSUE TITLE
String Cleanup Task

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#201]
After 2.0 version, we need to cleanup translations for the following:

- "Get started with account registration"
- "Back"

We also need to update the corresponding strings in the code:

- https://github.com/amzn/amazon-payments-magento-2-plugin/blob/eaa29e6398df1b3156f82f32f87f8c13b8e32fd9/src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml#L32
- https://github.com/amzn/amazon-payments-magento-2-plugin/blob/eaa29e6398df1b3156f82f32f87f8c13b8e32fd9/src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml#L68

**Comment by prayagr** [comment]
Resolved in #229
