### ISSUE TITLE
Widgets.js?nomin:43 Uncaught TypeError: H.indexOf is not a function

### ISSUE THREAD

**Issue by tanolalano** [amzn/amazon-payments-magento-2-plugin#203]
#### What expected
For non login-in with Amazon login
On checkout after address shipping selected go to next checkuot step (payament) 

#### What happened instead
For non login-in with Amazon login
On checkout if amazon-pay is enabled can't go to next checkuot step (payament).
NEXT button donesn't work

#### Steps to reproduce the issue

After install and configure amazon-payments-magento-2-plugin through composer, upgrade, compile and deploy.
Login with customer account, go to checkout proccess select shipping address go to next step. 
If customer login with Amazon Login no issue, after seclecting shipping address go automatically to pay with amazon-pay.

#### Your setup

* Magento version: 2.2.2
* Amazon Pay Extension Version: 1.2.5
* Magento Edition: Community 
* JavaScript Console: 
![error_amz_pay](https://user-images.githubusercontent.com/4384863/36932288-2b0369c0-1ec7-11e8-9017-5d6268a23c85.png)

* Shop URL : www.arancebio.it

**Comment by markusbengel** [comment]
In magento 2.2.3 the console message is a little different, result is similar:

1. Logged in user can choose address, "Next"-button does not work.
2. If user is not logged in or doesn't have an address set already: After klick on "Next"-button all valid address fields magically disappear.

**Hint:** have a look at 
_amazon-payments-magento-2-plugin/src/Payment/view/frontend/web/js/view/shipping.js_
and compare with "original"
_magento2/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js_

**Comment by tanolalano** [comment]
Thanks @markusbengel for your reply,

Is this issue fixed in 1.2.6?

**Comment by tanolalano** [comment]
Updating to 1.2.6 issue seem solved

**Comment by tanolalano** [comment]
Error persist on console, but payment can be processed

**Comment by prayagr** [comment]
Closing due to lack of response
