### ISSUE TITLE
Feature Request: Alternative Button Options

### ISSUE THREAD

**Issue by davidbrandastic** [amzn/amazon-payments-magento-2-plugin#205]
I would like to request an option be added to further adjust the style based on what is available on the Amazon Pay website.  Currently color options exist but only for a rounded button,

#### What I expected

https://pay.amazon.com/us/merchant/tools

![image](https://user-images.githubusercontent.com/20461966/37113513-70bfc6ee-21fa-11e8-9dc4-eef7f19550cc.png)
- The other button formats/sizes would be welcome as well, just chose to highlight the first example.

#### What happened instead

![image](https://user-images.githubusercontent.com/20461966/37112240-b160da52-21f6-11e8-9f3a-d47d6f2d505a.png)

* Magento version: 2.2.3
* Amazon Pay Extension Version:  1.2.6
* Magento Edition: Community / Enterprise / Enterprise Cloud

**Comment by tanolalano** [comment]
Same old style button on Magento 2.2.2 and Exension 1.2.5
instead of https://pay.amazon.com/us/merchant/tools

**Comment by lemked** [comment]
The plugin automatically uses the most current version of the button which is currently the one with the "USE YOUR AMAZON ACCOUNT" hint below the image . The provided button styles on the linked website are in fact outdated and will be updated soon.
