### ISSUE TITLE
M2.1.12CE: Disabled Amazon Pay 1.2.6 break checkout (cannot read property widgetUrl and isSandboxExnabled of undefined)

### ISSUE THREAD

**Issue by urosevic** [amzn/amazon-payments-magento-2-plugin#207]
#### What I expected

When we change options "Enable Amazon Pay" and "Enable Login with Amazon", checkout should not be broken. When "Enable Amazon Pay" is set to "Yes", then checkout working and load fine.

#### What happened instead

In browser console JS error is thrown and rendering checkout page fail.

#### Steps to reproduce the issue

1. Add any product to basket
1. Go to checkout

#### Your setup

* Magento version: 2.1.12
* Amazon Pay Extension Version: 1.2.6
* Magento Edition: Community
* Mageplaza One Step Checkout 2.1.3
* JavaScript Console: https://goo.gl/kKMWSi

**Comment by lemked** [comment]
Please update to version **2.4.2 of the Mageplatza One Step Checkout** extension and see whether the problem persists. There were changed incorporated into this version to improve the compatibility to Amazon Pay.

**Comment by gkic** [comment]
Thanks for follow up @lemked,

I by mistake provided OSC version placed in module.xml instead of version from composer.json (2.4.0). I'll check with Mageplaza team and back here with update.

**Comment by urosevic** [comment]
Thanks for follow up @lemked,

I by mistake provided OSC version placed in module.xml instead of version from composer.json (2.4.0). I'll check with Mageplaza team and back here with update.

**Comment by urosevic** [comment]
Hi again @lemked,

I discussed this issue with Mageplaza support, and we run following test:

1. Mageplaza OSC module disabled through shell `bin/magento module:disable Mageplaza_Osc` (then done setup:upgrade, deploy static content and cache clean).
1. Amazon Pay module is enabled, and both pay and login options disabled in settings (Stores -> Configuration -> Sales -> Payment Methods -> Other Payment Methods -> Amazon Payment -> General -> Options -> Enable Amazon Pay (set to No) and Enable Login with Amazon (set to No))
1. In Magento we have onepage checkout option enabled (Stores -> Configuration -> Sales -> Checkout -> Checkout Options -> Enable Onepage Checkout -> Yes)
1. In Magento we switched to theme Magento Luma

With all that, on (now default Magento onepage) checkout page there is still JS error related to property `widgetUrl` and `isSandboxEnabled` of undefined registry object `amazonPayment`.

You can see Amazon Pay settings on this screenshot https://goo.gl/bgexeB and here is screenshot of JS errors which prevent checkout page to load https://goo.gl/yct6Xe

I know that this is not aimed usage of Amazon Pay module (to be installed and enabled in Magento but both Pay and Login options disabled), but at the moment we need that combination to not break checkout page.

I can provide credentials for this development website by email (If I could send them to your email listed on your profile here on Github?)

I forgot to note, Magento CE v2.1.12 is in developer mode.

Thank you in advance,
Aleksandar

**Comment by lemked** [comment]
Hi Aleksandar,

I confirm that this problem occurs with the configuration that you have outlined. We will investigate the root cause and provide a bug fix on a separate branch that you can install via composer. Once confirmed working, we will incorporate the fix in a future release.

Kind regards,
Daniel

**Comment by urosevic** [comment]
Hi Daniel,

Could you please give me an ETA on when you'll be able to look again on this issue?

Thank you in advance,
Aleksandar

**Comment by lemked** [comment]
Looking into it. Either we'll provide a separate branch with a bug fix (if root cause can be identified quickly) or incorporate it into the upcoming version 3 of the plugin (in-core release for Magento 2).

**Comment by StarCod3** [comment]
Hello,

I've a similar issue with Magento 2.1.4.
On console, the browser report this error: `amazonPayment is undefined`
Do you have found a fix for this problem?

**Comment by ragboyjr** [comment]
@StarCod3 y, you have to update several of the JS files via the app/design theme.

If you just unzip that into your app/design/frontend/{vendor}/{theme} it should work. (at least it did for me)

[amazon-updates.zip](https://github.com/amzn/amazon-payments-magento-2-plugin/files/2124645/amazon-updates.zip)

**Comment by lemked** [comment]
Hi @urosevic ,

This issue was addressed with version 1.2.7. Can you please update the extension and provide feedback whether the problem has been solved?

Kind regards,
Daniel

**Comment by urosevic** [comment]
Hey @lemked,

Thank you for getting back to me. I'm aware of latest released version 1.2.7 ( re issue #312 ).
I can confirm that our issue got resolved with v1.2.7 - when both Pay with Amazon and Login with Amazon are set to No, checkout page load w/o any problem and other  payment methods work as expected.

Now we have to work iwth Mageplaza to tune customized OSC to work with Amazon Payments v1.2.7

Best regards,
Aleksandar
