### ISSUE TITLE
Add Password Help Info to Customer Account Page

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#210]
#### What I expected

As a customer, I expect to be able to create an account using Login with Amazon or Amazon Pay. Once logged in, I should be able to change my password from the Magento customer account page.

#### What happened instead

When trying to change the password, I get "The password doesn't match this account.".

#### Steps to reproduce the issue

1. Create a store account using Login with Amazon.
1. Go to the **My Account** page.
1. Click the **Change Password** link.
1. Try to change the account password.

#### Desired Change

The extension should provide informational messaging to the customer to let them know that if they don't know their password, they can use the reset password feature.

#### Your setup

* Magento version: 2.2.4
* Amazon Pay Extension Version: 2.0.3
* Magento Edition: Community 
* JavaScript Console: N/A
* Shop URL : N/A

**Comment by prayagr** [comment]
The change password functionality has been improved for M2.2.6, closing this.
