### ISSUE TITLE
order status issue with amazon pay

### ISSUE THREAD

**Issue by balwant20** [amzn/amazon-payments-magento-2-plugin#212]
What I expected
1. make payment with amazon pay.
2. Order was initially declined so status of this in Amazon pay was "Payment Review" .
3.  It was cleared on the same day at same time by Amazon Pay but still the status is "Payment Review" on our admin panel.
 
What happened instead
1. The status of order should be changed to Processing once it is cleared by Amazon Pay.
![screenshot-2018-04-12](https://user-images.githubusercontent.com/31465231/38675182-7f2675d4-3e74-11e8-9063-f5e5fbb14427.jpg)

Should i change **Update Mechanism** to **Data polling via Cron Job** ?

Setup
* Magento version: 2.1.7
* Amazon Pay Extension Version: 1.2.4
* Magento Edition: Community

**Comment by lemked** [comment]
Dear Balwant,

Instant Payment Notifications (IPN) is the recommended way for receiving status updates in case of any relevant event for Amazon Pay transactions. For using IPNs, you must however ensure that you have configured the endpoint URL in Seller Central properly, to which the IPN messages are sent and that this endpoint uses a valid SSL certificate.

The endpoint can be configured in Seller Central in Sandbox/Production view (please note that the URL can be configured separately for Sandbox/Production) under Settings > Integration Settings. The URL should be in the format: https://www.example.com/amazonpayments/payment/ipn/

To verify whether an IPN has been received successfully, please ensure that [logging is enabled ](https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#logging) in the plugin configuration. You should then see any IPN message that arrives in the amazonipn.log of the var/logs directory of your Magento 2 installation, e.g.:
/opt/bitnami/apps/magento/htdocs/var/log/amazonipn.log

Kind regards,
Daniel

**Comment by lemked** [comment]
Closing this due to no more further feedback.
