### ISSUE TITLE
Amazon Pay button is absent on checkout page

### ISSUE THREAD

**Issue by balex13** [amzn/amazon-payments-magento-2-plugin#214]
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/9139634f5c3c3ad026df4d02f1819b83a3470b46/src/Payment/Observer/AddAmazonButton.php#L72

`get_class($shortcutButtons)` can return `Magento\Checkout\Block\QuoteShortcutButtons\Interceptor` instead of `Magento\Checkout\Block\QuoteShortcutButtons` in case it have plugin.
It will be better to use `is_subclass_of()`

#### Preconditions
Amazon Pay is correctly configured and Amazon Pay Button is present on cart page 

#### Steps
1. Create plugin to `Magento\Checkout\Block\QuoteShortcutButtons`
2. Clean all caches including generation and DI cache, clean and deploy static content
3. Open Shopping Cart 

#### Expected Result
Amazon Pay Button is present on cart page

#### Actual Result 
Amazon Pay Button is absent on cart page

### Affected version
1. Magento 2.1.6
2. amzn/amazon-pay-sdk-php 3.2.0
3. amzn/amazon-payments-magento-2-plugin 1.2.6

**Comment by prayagr** [comment]
Hi @balex13 , sorry for the late response here. The fix has been merged into master, please reopen the issue if you still face problems.
