### ISSUE TITLE
Order with non-US shipping address placed in Magento Commerce 2.1.9 Cloud - Magento Invoice Amt and Amt Charged on Amazon Pay is different

### ISSUE THREAD

**Issue by skaranam** [amzn/amazon-payments-magento-2-plugin#223]
#### What I expected
When i place an order which has a non-US Shipping Address, Magento Order Total should be same as the amount charged with Amazon Pay.

#### What happened instead
Because we are shipping to non-US destinations, the international shipping charges and duties are calculated by Borderlinx. These amounts are part of the order summary and are reflected in the order total.

As an example:

Order Summary Entry | Amount
-- | --
Subtotal | 195.00
Shipping & Handling | 22.89
Tax | 27.61
Duty | 35.1
Grand Total | 280.6

The Authorized Amount on Amazon Pay is **280.6**

If we check this on Seller Central for this order, we see the following.
**Total 315.70**
**Charged 245.50**

The above entries do not match. However, if we see carefully, we can see a pattern.

charged amount of **245.50** is Grand Total minus duty amount
**280.6 - 35.1 = 245.50**

Also the total amount is Grand total + duty amount
**280.6 + 35.1 = 315.70**

#### Your setup

* Magento version: 2.1.9
* Amazon Pay Extension Version:  1.11.0
* Magento Edition: Enterprise Cloud

**Comment by tarishah** [comment]
@skaranam Resolving this issue.
Issue details - Borderlinx was introducing a new parameter named 'duty' which is not a core magento parameter. By going to Borderlinx settings -> Total Cost Calculator -> Duty Handling -> select either select ‘Included in Tax’ or ‘Included in shipping’ which will resolve the above issue.
Please contact Borderlinx directly if you need to use 'duty' as a separate parameter.

**Comment by prayagr** [comment]
Thanks for the details, closing this issue.
