### ISSUE TITLE
Possible conflict with Paypal Plus module

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#23]
HI,

a merchant contacted us. It seems the module is not compatible with Paypal Plus.
Asked for details and will add them once received.

Best wishes
Daniel

**Comment by markenwirt** [comment]
Hey,
we can confirm the error with PayPal Plus from i-ways - the offical paypal-plugin.
Amazon by itself does work but if u active both modules only PayPal Plus work correctly.

The process if both are activated:
- login with amazon works
- confirm the shipping works
- paymentmethods - does not work. There are no paymentmethods, no iframe from amazon, no errors in the console - nothing.

Is there an easy workaround?

**Comment by danielneu** [comment]
Closing in favor of #22

**Comment by danielneu** [comment]
For anyone fllowing this issue only, this was fixed, resolution and possible dicusssion will happen in #22
