### ISSUE TITLE
After filling login credential in amazon login popup required view is not coming

### ISSUE THREAD

**Issue by BabliDey** [amzn/amazon-payments-magento-2-plugin#231]
#### What I expected
After entering login credential in popup the screen should come as
![desktopaddress_3_1_2_2_1_1_2](https://user-images.githubusercontent.com/24405051/40479930-d985e50a-5f44-11e8-8f4e-b6a2949c283a.png)

####

But this is not coming. Normal checkout page is coming

#### Your setup

* Magento version: 2.1.8
* Amazon Pay Extension Version: 1.2.4
* Magento Edition: Community 
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process

* Shop URL :

**Comment by lemked** [comment]
Dear @BabliDey ,

Can you provide access to a staging environment where we can reproduce the issue? If possible, please update to the latest version of Magento (2.2.4) to see whether the problem still occurs. This Magento version includes the latest version of our extension (bundled version) and provides several bug fixes and new features, which might solve the problem already.

Kind regards,
Daniel

**Comment by BabliDey** [comment]
Hello lemked,
Thank you for your reply. But this problem is solved after disabling the current version of module then after complete removing installing again. But now th eproblem is the amazon login working in desktop but not working in mobile devices.

Thanks

**Comment by lemked** [comment]
Dear @BabliDey , 
Can you please provide details about the problem with the login on mobile devices (steps to reproduce, screenshots, error logs, etc.)?

Kind regards,
Daniel

**Comment by BabliDey** [comment]
Hello @lemked,
Sorry for late reply. Was busy in finding different solution. I am sending you the screen shot in mobile.
![amazon_mobile_logins](https://user-images.githubusercontent.com/24405051/40703341-bc5fec7c-63dc-11e8-8d80-5267e9ee4846.png)

Thanks 
Babli

**Comment by lemked** [comment]
Hi @BabliDey ,

Can you please provide the website URL and steps to reproduce the problem?

Kind regards,
Daniel

**Comment by BabliDey** [comment]
Hello @lemked ,
As amazon payment was not working on magento 2.1.8 and my site maximum payment done with amazon so, I reverted back to magento 1.9.3. So the link is not available to check the error now. But need to upgrade the magento version. So need the solution. 

Steps are: 
Open site . Adding product to cart. In cart page there is amazon pay button. Click on this. A screen was coming where it requests for the amazon userid and password. After entering the details. 
In desktop the page redirects properly
In mobile the above screen is coming that i provided in screen shot.

Thanks 
Babli

**Comment by lemked** [comment]
Thank you @BabliDey ,
We will verify this issue on a Magento 2 instance running version 2.1.8 of Magento 2 and version 1.2.6 of our plugin.

I'll update this issue once we have the results.

**Comment by BabliDey** [comment]
Thank you @lemked

**Comment by BabliDey** [comment]
Hello @lemked, 
i have installed amazon payment magento 2 plugin 1.2.6 also in magento 2.2.3 version. When i am chcking this in desktop its working fin. But when i am checking this in my android mobile redirecting is not working. https://www.blumeidealbeta.de

**Comment by lemked** [comment]
Hi @BabliDey ,

We've been able to reproduce the problem on the website. Would it be possible to gain access for the backend and the filesystem of this server to analyze the issue? Read-only access for the file system on the Magento 2 installation should be suitable.

If possible, please share the access details on payments-cp-devel@amazon.com

Regards,
Daniel

**Comment by BabliDey** [comment]
Hello @lemked ,

I am sending you the credential in mail from babli.citytech@gmail.com Subject: Server credential and login details

Thanks,
Babli

**Comment by lemked** [comment]
Thanks, retrieved it. We will look into this.

**Comment by tomclancy1234** [comment]
Hi,
I got exactly this issue, please help me resolve it.
I'm using magento 2.1.5 and Amazon module 1.2.8. All is fine on desktop but on mobile, after login, it shows page: You will be redirected shortly...

I checked, in verifyAmazonLoggedIn:

amazon.Login.authorize(loginOptions, function (response) {
                if (response.error) {
                    defer.reject(response.error);
                } else {
                    accessToken(response.access_token);
                    defer.resolve(!response.error);
                }
            });

The responses error is always:
error: "invalid_grant"
error_description: "invalid grant"

Can you please share the fix? Thank you.

**Comment by lemked** [comment]
Hi @tomclancy1234 ,

Thank you for your feedback. We can confirm in the meantime that this is a known issue, that will occur in Sandbox mode only however. Anytime when the "redirect authentication" is being used (on all mobile devices and when using the Amazon Pay button on the product detail page for instance), the "invalid_grant" exception will occur, in which case the user is stuck on the "You will be redirected page". It also seems to apply to non-US environments only.

We are currently investigating this problem, you should however *not* encounter it when using Amazon Pay in live mode.

Kind regards,
Daniel

**Comment by lemked** [comment]
Fixed on current master branch, see https://github.com/amzn/amazon-payments-magento-2-plugin/issues/216. Closing this as duplicate.
