### ISSUE TITLE
Klarna Checkout & Amazon Payments

### ISSUE THREAD

**Issue by markenwirt** [amzn/amazon-payments-magento-2-plugin#247]
Hey guys,
first of all we love the Amazon Payments-Module. It works really good and we have 0 problems at all. But our customer wanna switch to the klarna checkout (https://marketplace.magento.com/klarna-m2-checkout.html) so we tested the combination of both. It doesn't work.

In checkout cart is the normal Amazon Pay-Button, u can login, all fine. But after the login it's redirecting to the klarna-checkout (https://example.de/checkout/klarna/) and the klarna-module is shown. Is there a way to change that? Do you think you need to change it or klarna?

Thank you alot.
Felix

* Magento version: 2.1.4
* Amazon Pay Extension Version: 2.1.0
* Magento Edition: Community

**Comment by lemked** [comment]
Hi @markenwirt ,

Are you sure it's version 2.1.0 of the Amazon Pay extension? The most recent version for Magento version 2.1.4 should be version 1.2.6 of our extension.

Kind regards,
Daniel

**Comment by islandskater43** [comment]
@markenwirt - can you confirm the Amazon Pay extension version? We don't have a `2.1.0` version.

**Comment by laura-wagner** [comment]
Hello, we have the same issue under WooCommerce, running both Klarna and Amazon pay. 
Klarna only works while Amazon pay is deactivated. 

WooCommerce Amazon Pay Gateway, Version 1.8.2

**Comment by markenwirt** [comment]
Hey @lemked,
i'm sorry. In the meantime we tried to update the magento2 of our customer and didn't focus on this github-post.

So yeah, i meant login-and-pay-with-amazon-sdk. Thats on 2.1.0.
But you are right, Amazon Payments is only on 1.0.9.

So maybe a module update could help with the klarna-problem. Right? But both are in the core now, so we try to update the hole magento 2. If we find any problems we create a new post.

Thanks a lot.

PS: I am sorry @laura-wagner, but u have to open your own github-post. This post was about magento2 and Amazon/Klarna and not about WooCommerce.
