### ISSUE TITLE
request does not match any route

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#25]
A merchant is getting the following error from the shipping ajax request:

    request does not match any route

This is in response to the following ajax request:
PUT https://domain.com/rest/default/V1/amazon-shipping-address/S01-1234567-7654321

We've tried:

```
# Determine cache status
php bin/magento cache:status
 
# If the cache is enabled
#clean cache
php bin/magento cache:clean
 
# cleanup static folders
rm -rf /opt/bitnami/apps/magento/htdocs/pub/static/*
rm -rf /opt/bitnami/apps/magento/htdocs/var/view_preprocessed/*
```

**Comment by danielneu** [comment]
Additional hints:

The route is defined [here](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/e703ca37fdb7b8ce84a8326e6ef6e5eaab9a838f/src/Payment/etc/webapi.xml#L4)

Calling [this service method](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/e703ca37fdb7b8ce84a8326e6ef6e5eaab9a838f/src/Payment/Model/AddressManagement.php#L110) if successful.

Maybe similar or related: https://github.com/magento/magento2/issues/5542
Did you check if the method was PUT when it happened and not only when it was successful?

Best wishes
Daniel

**Comment by islandskater43** [comment]
This was a merchant-specific error where the web server was blocking PUT requests. Closing issue.
