### ISSUE TITLE
[2.2.4] Back button is now labelled "Back to register or connect an account" everywhere

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#250]
#### What I expected

`Back` string to remain `Back`.

#### What happened instead

Any instance of `Back` is being converted to `Back to register or connect an account`

#### Steps to reproduce the issue

In M2.2.4, switch to en_GB language.

Related issue: https://github.com/magento/magento2/issues/15024

**Comment by mcyrulik** [comment]
When will this be made available as a release?

**Comment by islandskater43** [comment]
@mcyrulik - The change will be included in the 2.2.5 release of Magento.

**Comment by islandskater43** [comment]
Closing as this issue was fixed in 2.2.5.
