### ISSUE TITLE
Undefined offset 2 :  amzn/amazon-payments-magento-2-plugin/src/Core/Domain/AmazonAddressJp.php on line 58

### ISSUE THREAD

**Issue by Taku-Yamashita** [amzn/amazon-payments-magento-2-plugin#267]
#### What I expected

Successfully process  shipping checkout step.

#### What happened instead

I cannot process the step because of below error.

Notice: Undefined offset: 2 in /var/www/xxx-xxx/vendor/amzn/amazon-payments-magento-2-plugin/src/Core/Domain/AmazonAddressJp.php on line 54 in /var/www/xxx-xxx/vendor/magento/framework/App/ErrorHandler.php:61

#### Steps to reproduce the issue

set all of AmazonPay configuration and then process checkout step.

Address of my test account 
-  Test Taro
-  1-17-25 Shinkamata
-  WaniWai apart
-  Ota-ku, Tokyo 144-8588
-  Japan
-  電話番号： 08099999999

#### Your setup

* Magento version: 2.1.13
* Amazon Pay Extension Version: 1.2.6
* Magento Edition: Community

#### Additional Info

AmazonAddressJp.php will use "AddressLine2" & "AddressLine3" 
even though some people don't use "AddressLine2"  and there is not "AddressLine3" on Amazon Account(Only Japan?).

**Comment by lemked** [comment]
Hi @Taku-Yamashita ,

Thank you for filing this issue. We will investigate this internally and provide feedback as soon as possible.

Kind regards,
Daniel

**Comment by lemked** [comment]
Related to issue https://github.com/amzn/amazon-payments-magento-2-plugin/issues/267

**Comment by lemked** [comment]
Fixed in master and 2.x branch. Will be closed once we have released a new version.

**Comment by lemked** [comment]
Fixed with version 3.1.4 that is included in Magento 2.3.1. Also fixed in Magento 2.2.8.

Closing issue. Please re-open if still facing this issue.
