### ISSUE TITLE
Emails Sent w/ No From Address

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#274]
#### What I expected

When using M2.2.4 or M2.2.5, I expected emails sent from my store to have a _From_ address.

#### What happened instead

Received an email with tags as a From address - `{{ getSender(message) }}`

#### Steps to reproduce the issue

See associated Magento issues:
* https://github.com/magento/magento2/issues/11740
* https://github.com/magento/magento2/issues/14952
* https://github.com/magento/magento2/issues/16231
* https://github.com/magento/magento2/pull/16356
* https://github.com/magento/magento2/pull/16461

Specific comments referencing Amazon Pay code:
* https://github.com/magento/magento2/issues/16231#issuecomment-399356440
* https://github.com/magento/magento2/issues/14952#issuecomment-399765502

#### Affects / Fix Needed:

Affected versions: 2.2.4 & 2.2.4
Fix needed on: Master & 1.x Branch

**Comment by prayagr** [comment]
Keeping this issue open until this fix is included in Magento 2.2.6, thanks for your suggestion @jeroenBoersma

**Comment by JeroenBoersma** [comment]
Ah, no need to create a PR anymore ;) didn't even notice I forgot about that :+1:

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
