### ISSUE TITLE
Remove override of shipping.html and payment.html

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#28]
The module currently overrides the shipping.html (file src/Payment/view/web/template/shipping.html).

This was due to limitations of the extensibility of the checkout at the time of writing this module.
Please check whether this can be changed and be handles with an extension now.

This already caused conflicts with a checkout module and merchant integrations.
Thanks
Daniel

**Comment by danielneu** [comment]
Actually, those 4 files should be checked, if we can move away from overriding things:

•	Magento_Checkout/view/frontend/web/js/view/shipping.js
•	Magento_Checkout/view/frontend/web/js/view/payment/list.js
•	Magento_Checkout/view/frontend/web/template/shipping.html
•	Magento_Checkout/view/frontend/web/template/payment.html

**Comment by andidhouse** [comment]
Is this solved? 
We can not install a module which overrides files.

Thanks!

**Comment by danielneu** [comment]
Hello,

unfortunately - like other checkout and payment options - we are currently limited to overriding those files.
However, we are only doing minor modifications to those files which can be merged into any other version, e.g. the one in the theme, without problems.

Best wishes 
Daniel

**Comment by danielneu** [comment]
This was resolved with #106
