### ISSUE TITLE
Amazon Button 403

### ISSUE THREAD

**Issue by snoroozi** [amzn/amazon-payments-magento-2-plugin#299]
No errors on checkout

There is an error in chrome dev console GET https://d2ldlvi1yef00y.cloudfront.net/default/us/live/lwa/lightgray/small/LwA_2x.png 403 ()

However button still appears, yet I'm thinking I should get the newer flat version of the buttons.

Put item in cart and view dev console for checkout.  

Our host claims they do not see this error and believe it must be specific to some CDN that the images should be serving from

* Magento version: 2.2.5
* Amazon Pay Extension Version:  Latest
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : thegreennursery.com

**Comment by tarishah** [comment]
@snoroozi We are looking into this. I will update once we have a fix for this.

Thanks,
Tarini

**Comment by RayAnaya** [comment]
I am going to go ahead and mark this issue as closed as the initial issue was reported several years ago and there have been numerous changes and new versions of both Magento, Amazon Pay's Plugin, and our button code.  Please feel free to re-open this issue if you continue to experience this with newer versions.
