### ISSUE TITLE
Cannot read property 'settings' of undefined when trying to Save Payment Configuration in Magento 2.2.4

### ISSUE THREAD

**Issue by kamilszewczyk** [amzn/amazon-payments-magento-2-plugin#309]
#### What I expected

I wanted to edit other payment method configuration using Magento Admin

#### What happened instead

![image](https://user-images.githubusercontent.com/1061999/44044031-42bf571a-9f1c-11e8-9ecf-81db658c4001.png)
error visible in console once the Save button has been clicked
Debugging the breakpoint shows that it occurs for
![image](https://user-images.githubusercontent.com/1061999/44044266-f7b6394a-9f1c-11e8-8382-932b81ea93ee.png)

#### Steps to reproduce the issue

1. Open Amazon Pay configuration accordiong
2. Click get started with account registration button
3. Close the window (the Credentials JSON label is visible ![image](https://user-images.githubusercontent.com/1061999/44044276-fe1abb6c-9f1c-11e8-9a34-8a2d44215e50.png)
)
4. Try to save the configuration

This is the manual process of reproducing, and on local environments refreshing the page helps, however on our dev environment the even thoutgh the label is not visible, the configuration fail to save

#### Your setup

* Magento version: 2.2.4
* Amazon Pay Extension Version: 2.0.12 installed from Magento Marketplace
* Magento Edition: Community

**Comment by prayagr** [comment]
Hi @kamilszewczyk , I believe we fixed this issue as part of the commit https://github.com/amzn/amazon-payments-magento-2-plugin/commit/6b5058208e94710e019d53c2a10e643d8d8fe3a2

Can you upgrade the Amazon Pay extension from 2.0.12 to the latest 2.x branch? The 2.x branch is specific to Magento 2.2.4 and 2.2.5. Please let me know if that helps resolve the issue.

**Comment by gnysek** [comment]
Seems that above issue doesn't happen anymore (checked on 2.x / e0c6c23a6a0f4a3d7717fef7d211e6559e6e5cdc )

**Comment by kamilszewczyk** [comment]
@prayagr - sorry for the delayed response. The above issue seems to be fixed on 2.x branch

**Comment by prayagr** [comment]
Glad to know that it is resolved, thanks for updating.
