### ISSUE TITLE
Upgrade to 2.0.14 break setup:di:compile on Magento 2.1.14 CE

### ISSUE THREAD

**Issue by urosevic** [amzn/amazon-payments-magento-2-plugin#312]
#### What I expected

After upgrade from amazon-payments-magento-2-plugin v1.2.6 to 2.0.14 Magento 2.1.14 can not finish di:compile

#### What happened instead

This is error we get when we run setup:di:compile [https://prnt.sc/kiwpj0](https://prnt.sc/kiwpj0)
```
[ReflectionException]
Class Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface does not exist
```

I can login to M2 Admin back-end and tune Amazon Pay configuration [https://goo.gl/fdbNfi](https://goo.gl/fdbNfi)

On front-end:

With custom theme and with enabled Mageplaza OneStepCheckout: On front-end I can pick **Pay with Amazon Pay** button and authenticate, but on OneStepCheckout page all is empty [https://goo.gl/Q4YiCc](https://goo.gl/Q4YiCc) with following error on JS console [https://goo.gl/DBxcaK](https://goo.gl/DBxcaK).
Obviously that Mageplaza OSC checkout template have to be tuned for new Amazon Pay, but before we attempt to that, we need setup:di:compile to finish successfully. 

When Mageplaza OSC disabled and Magento Luma theme selected, Amazon Pay in sandbox mode: on Checkout page Address Book and Payment Amazon widgets are rendered, but can not checkout. This is story for after setup:di:compile get resolved.

#### Steps to reproduce the issue

```
composer require amzn/amazon-payments-magento-2-plugin:^2.0.14 --no-update
composer update
rm -rf var/cache/* var/di/* var/generation/* var/page_cache/*
redis-cli FLUSHALL
php bin/magento maintenance:enable
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento deploy:mode:set production -s
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy en_GB
php bin/magento setup:static-content:deploy en_CA
php bin/magento setup:static-content:deploy en_AU
php bin/magento setup:static-content:deploy
php bin/magento setup:di:compile
```

#### Your setup

* Magento version: 2.1.14
* Amazon Pay Extension Version: 2.0.14
* Magento Edition: Community
* Magento Mode: Production
* Mageplaza OneStepCheckout 2.1.3
* JavaScript Console: provided screenshots in section **What happened instead**

**Comment by prayagr** [comment]
Hi @urosevic , Amazon Pay v2.0.x is meant for Magento 2.2.4+. For your Magento version, you should use the 1.x branch, which is versions previous to Magento 2.2.4. 

We will be releasing v1.2.7 tomorrow for the 1.x branch, which includes a few bug fixes. I would suggest you upgrade to this version once we release it.

**Comment by urosevic** [comment]
Thank you @prayagr for that precious tiny detail.

Could you also please update Pre-Requirements for branch 2.x because at the moment it's **Magento 2.1+**
https://github.com/amzn/amazon-payments-magento-2-plugin/tree/2.x

And also a note to release notes that branch 2.0 is not compatible with Magneto <2.2.4
https://github.com/amzn/amazon-payments-magento-2-plugin/releases

Thanks,
Alex

**Comment by prayagr** [comment]
@urosevic , thanks for pointing that out - we will update the files to reflect the correct versions. 

For installing Amazon Pay into your Magento setup, please wait until later today when we release a new 1.x version - 1.2.7

**Comment by urosevic** [comment]
Thank you very much @prayagr ,
Amazon Payments v1.2.7 applied successfully on Magento 2.1.14 w/o compilation errors.
