### ISSUE TITLE
Composer Install the latest v2.0.14 doesn't Support PHP 7.1

### ISSUE THREAD

**Issue by darmayantiPuteri** [amzn/amazon-payments-magento-2-plugin#319]
Composer Install the latest v2.0.14 doesn't Support PHP 7.1

#### What I expected
Able to Install in the PHP version 7.1

#### What happened instead
Got this error when composer require :
Problem 1
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.0-rc3 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.0-rc2 requires php ~5.5.22|~5.6.0|~7.0.0 -> your PHP version (7.1.20) does not satisfy that requirement.
    - magento/framework 100.1.0-rc1 requires php ~5.5.22|~5.6.0|~7.0.0 -> your PHP version (7.1.20) does not satisfy that requirement.
    - Conclusion: don't install magento/framework 100.2.0-rc20
    - Installation request for amzn/amazon-payments-magento-2-plugin ^2.0.14 -> satisfiable by amzn/amazon-payments-magento-2-plugin[2.0.14].
    - Conclusion: don't install magento/framework 101.0.3|install magento/framework 100.2.0-rc20
    - Conclusion: remove magento/framework 101.0.3|install magento/framework 100.2.0-rc20
    - amzn/amazon-payments-magento-2-plugin 2.0.14 requires magento/framework ^100.1.0|^101.0.4 -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.2.0-rc20, 100.1.9, 100.1.10, 100.1.11, 100.1.12, 100.1.13, 101.0.4, 101.0.5, 100.1.14].
    - Can only install one of: magento/framework[101.0.3, 101.0.4].
    - Can only install one of: magento/framework[101.0.3, 101.0.5].
    - Installation request for magento/framework == 101.0.3.0 -> satisfiable by magento/framework[101.0.3].

#### Steps to reproduce the issue
Run composer composer require amzn/amazon-payments-magento-2-plugin:^2.0.14

#### Your setup

* Magento version: 2.2.3
* Amazon Pay Extension Version: 2.0.14 
* Magento Edition: Enterprise Cloud (installing on Local site with the same PHP version with Cloud)
* Shop URL : https://vault.testingnow.me/

Thanks for the support.

**Comment by tarishah** [comment]
@darmayantiPuteri 

Can you confirm which Magento Version are you on? When you say 2.3.3 - do you mean 2.2.3?

If you are on Magento version 2.2.3 - Please install Amazon Pay extension from the [1.x branch](https://github.com/amzn/amazon-payments-magento-2-plugin/tree/1.x).

**Comment by MicheleBeargroup** [comment]
2.0.14 from amzn repo is currently set to ~7.1.0 - let us know if this is excluding the version of PHP 7.1 you are using.

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
