### ISSUE TITLE
Wrong page_layout seems to be used by the checkout_index_index XML update.

### ISSUE THREAD

**Issue by korostii** [amzn/amazon-payments-magento-2-plugin#32]
The 1column page layout used [here](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/view/frontend/layout/checkout_index_index.xml#L18)  seems to override the one used by Magento internally (which is different, see [here](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/layout/checkout_index_index.xml#L8) ) which causes the checkout header to break unexpectedly accompanied by an error of the following sort in system.log:
`main.CRITICAL: Broken reference: No element found with ID 'checkout.header.wrapper'.`

**Comment by danielneu** [comment]
Hi @korostii 

thanks for reporting this.
This seems to have stuck since the [2.0](https://github.com/magento/magento2/blob/2.0/app/code/Magento/Checkout/view/frontend/layout/checkout_index_index.xml#L8) times.

I will add this to the next release.

Best wishes
Daniel

**Comment by korostii** [comment]
Hi Daniel,

Glad to be of help. Thank you for the very fast response and fix! 
Such a contrast to the flow of issues in magento/magento2 repository, pure pleasure for my eyes.
Thank you for making this cool plugin, and keep up the good work =)

Best, Denis
