### ISSUE TITLE
Amazon Pay Breck Compilation

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [amzn/amazon-payments-magento-2-plugin#324]
I have recently installed this extension in my Magento 2.2.3 and it will break all Magento command.
#### What I expected
Magento all command need to run successfully.

#### What happened instead
`php bin/magento s:up` Setup Upgrad 
PHP Fatal error:  Class 'AmazonPay\Client' not found in /XXXXX/app/code/Amazon/Core/Client/Client.php on line 20

Fatal error: Class 'AmazonPay\Client' not found in /XXXXX/app/code/Amazon/Core/Client/Client.php on line 20

`php bin/magento s:d:c`
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 50.0 Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 54.0 Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 54.0 MiBPHP Fatal error:  Class 'Amazon\IpnHandler' not found in /XXXXX/app/code/Amazon/Payment/Ipn/MockIpnHandler.php on line 25

Fatal error: Class 'Amazon\IpnHandler' not found in /XXXXX/app/code/Amazon/Payment/Ipn/MockIpnHandler.php on line 25

#### Steps to reproduce the issue

After install Run `php bin/magento s:up` Setup Upgrad 
#### Your setup

* Magento version: 2.2.3
* Amazon Pay Extension Version: 
* Magento Edition: Community 
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : local setup

**Comment by tarishah** [comment]
Hello @dodiya-divyarajsinh 

Thanks for getting in touch.

How exactly did you install the extension? The missing calls is part of our SDK and not of this extension.
The SDK is added as a dependency and will be installed automatically, if you follow the [official installation instructions](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#installation-process).

If you installed the module differently (e.g. simply extracting it to the Magento installation), please do so for all the dependencies as well.

Best wishes
Daniel

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
