### ISSUE TITLE
Amazon  - incompatible versions of modules installed?

### ISSUE THREAD

**Issue by kornblumenapotheke** [amzn/amazon-payments-magento-2-plugin#329]
#### What I expected
After update from M 2.2.2 to 2.2.5, compilation should work fine

Should compile without errors

	Amazon\Core\Domain\AmazonAddressDe
Extra parameters passed to parent construct: $addressNameFactory. File: /var/www/vhosts/meineapo.at/httpdocs/vendor/amzn/amazon-pay-and-login-with-amazon-core-module/Domain/AmazonAddressDe.php
Total Errors Count: 1

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version:  latest via composer
* Magento Edition: Community
* Shop URL : meineapo.at

**Comment by kornblumenapotheke** [comment]
Anyone?

**Comment by lemked** [comment]
Hi @kornblumenapotheke ,

We can confirm this issue and are currently looking into it.

Kind regards,
Daniel

**Comment by lemked** [comment]
Hi @kornblumenapotheke ,

Can you confirm that this is the same shop that you are encountering an issue with as described in #330?

Kind regards,
Daniel

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
