### ISSUE TITLE
Amazon_Core db data version: defined in codebase - 1.2.6, currently installed - 2.0.12

### ISSUE THREAD

**Issue by kornblumenapotheke** [amzn/amazon-payments-magento-2-plugin#330]
#### What I expected
Codebase and INstalled same version

#### What happened instead

Versions inconsistent. No chance to uninstall or to change version.

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 
* Magento Edition: Community

**Comment by lemked** [comment]
Hi @kornblumenapotheke ,

Do you still encounter this issue? If so, can you please provide the following information?

- file composer.json
- file composer.lock
- list content of /vendor/amzn/

This should help us to find a fix for your problem.

Kind regards,
Daniel

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
