### ISSUE TITLE
Shipping Address chosen, overwritten by Magento shipping default...

### ISSUE THREAD

**Issue by EmilyPepperman** [amzn/amazon-payments-magento-2-plugin#344]
What I expected: That the shipping address chosen from Amazon screen would be used as the shipping address on the Magento order.

What happened instead: The shipping address chosen on the Amazon screen shows as the Billing Address on the Magento order, the shipping address on the Magento order is overwritten with the default shipping address from Magento customer account.

You can reproduce by: Logging into a Magento customer account... for testing purposes have a different address for default billing and shipping so you can see the issue better.

Checkout with Amazon Pay using a different name and address than any address you have saved in the Magento account (so you can see the difference)... Note that the address that you picked from your Amazon account is now on the order as your Billing Address, and the Magento default shipping address is the shipping address on the order and not what you chose from Amazon account.

* Magento version: 2.2.5
* Amazon Pay Extension Version: 2.0.14
* Magento Edition: Community
* Shop URL : https://www.divegearexpress.com

**Comment by prayagr** [comment]
Thanks for reporting this @EmilyPepperman and sorry for the delay in responding. We will aim to replicate and fix this.

**Comment by EmilyPepperman** [comment]
Thanks @prayagr Let me know if you need anymore details we are hot to solve this. :-) It has caused a few misshipments for customers. We have a lot of customers that use hotels or destinations as their shipping addresses for some orders, so the address can be wrong.

**Comment by prayagr** [comment]
Hi @EmilyPepperman  , we are looking into this with priority. I'll reach out if we need any details, but hope to provide a fix for this shortly.

**Comment by EmilyPepperman** [comment]
Hi @prayagr This is still an issue. Thanks!

**Comment by requix** [comment]
Hi @prayagr. We use Amazon Pay 3.0.0 and this issue is still exists. Do you have any update on this?
@EmilyPepperman, did you find a solution for this issue? 
Thanks.

**Comment by EmilyPepperman** [comment]
@requix Do you use ShipperHQ? We did get this solved and can look back at my notes.

**Comment by requix** [comment]
@EmilyPepperman We don't use ShipperHQ. Only 3rd party onestep checkout. Any information about your solution would be helpful. Thanks a lot.

**Comment by EmilyPepperman** [comment]
@requix Here is what Amazon devs told me and from this our Senior dev did solve it. 

INFO from Amazon Dev team:
As you can see in the attached images, the address form that is hidden when the Amazon Pay address block displays is missing on your site. So essentially, what is happening is when the widget is interacted with, the address items are fed into that hidden form, which is what causes it to get saved into the quote object after selecting a shipping method. If the form isn't there (as is the case on your site) the default shipping address remains unchanged in the quote object and we get a JS error since the script can't find that form block.

See if your developer(s) is overriding a *.js or *.phtml document that is also in use by the Amazon_Payment module.  This would most likely be in your site's theme folder.  If so, make sure any AP specific blocks of HTML or JS are also included in that override.
