### ISSUE TITLE
Checkout Button broken after Amazon Pay Login

### ISSUE THREAD

**Issue by OhkaBaka** [amzn/amazon-payments-magento-2-plugin#354]
#### What I expected

After logging in to Amazon Pay I expected to be able to click the checkout button and continue on with my purchase.

#### What happened instead

My checkout button does not respond when clicked.  If the page is refreshed with the address and payment method already selected, the checkout button will work fine.

#### Steps to reproduce the issue

1) Visit the store without being logged in to Amazon Pay
2) Put items in cart and attempt to checkout as normal
3) During checkout a secondary window may open with an additional copy of the Wallet widget in it.
4) After the login is successful the Checkout button does not work

#### Your setup

* Magento version: 2.1.7
* Amazon Pay Extension Version: 1.2.6
* Magento Edition: Enterprise
* Shop URL : AudioAdvice.com

![screen shot 2018-09-24 at 1 46 41 pm](https://user-images.githubusercontent.com/784235/45978182-75948200-c000-11e8-8415-856a8fa77816.png)

**Comment by prayagr** [comment]
Hi @OhkaBaka , we made some changes in our extension that should improve the checkout process. Can you try upgrading from version 1.2.6 to 1.2.8 of Amazon Pay and see if the issue still exists?

**Comment by OhkaBaka** [comment]
I'll reach out to the seller...

(and I'm adding seller and edition to issue)

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
