### ISSUE TITLE
Checkout 'Place Order' Issue Since Update

### ISSUE THREAD

**Issue by bedroomathletics** [amzn/amazon-payments-magento-2-plugin#355]
#### What I expected

Selecting Amazon Pay in payment method list (glad you guys updated to include Amazon Pay in 2.2.6) and then hitting 'Place Order' instead of hitting the amazon button directly should trigger the Amazon login pop-up.

#### What happened instead

Order is placed without loggin into amazon. Customer receives 'order success' page and email. Failure of payment email triggered to the company.

#### Steps to reproduce the issue

Please watch;

http://recordit.co/PtRQq816x6

#### Your setup

* Magento version: 2.2.6
* Amazon Pay Extension Version: 2.1.0
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : dev.bedroomathletics.com

**Comment by prayagr** [comment]
Hi @bedroomathletics , thanks for reporting this and appreciate the video explanation as well. Are you using a third party checkout? I was not able to see the Place Order button on a default M2 setup after choosing Amazon Pay.

![coap](https://user-images.githubusercontent.com/24440891/46097952-10639c80-c178-11e8-89bf-aca6660efcfa.png)

**Comment by bedroomathletics** [comment]
Hey,

Not a problem, videos are much easier for everyone! :) 

We are using Aheadworks One-Step Checkout - they have tested and said, "The same behaviour also happens on native checkout with our extension disabled, could you please check and fix it?"

So Place order button should actually be hidden with 2.2.6 when Amazon Pay is listed in the payment method list?

**Comment by prayagr** [comment]
Hi @bedroomathletics , I am sorry for the late response here but I am currently in touch with the Aheadworks team to figure out a solution for this problem. I will provide an update when I can.

**Comment by requix** [comment]
Hi @prayagr, we found the same issue with Amasty One-Step Checkout.
Is it possible to open Amazon checkout on Place order click? (in case when Amazon Pay is selected as payment method)

**Comment by hammockvienna** [comment]
@bedroomathletics we face the same issue with Magento 2.2.5 and Amasty Onestep Checkout. 
We see the Place order button until the Amazon Pay MOdule has loaded completly. Then the button disappears.

@bedroomathletics @prayagr @requix Was anybody able to fix the issue?

`<button class="action primary checkout amasty" type="submit" data-bind="
                        click: placeOrder,
                        attr: {title: label}
                        " data-role="review-save" title="
                            
                        ">
            <span data-bind="text: label">
                            HERE SHOULD BE THE SUMBIT BUTTON - BUT ITS EMPTY
                        </span>
        </button>
`

**Comment by tarishah** [comment]
@hammockvienna @requix Amazon Pay should be compatible with Amasty OSC from v1.4. can you let me know which version of Amasty OSC are you both on?

**Comment by hammockvienna** [comment]
@tarishah we are currently using 2.3.0.

**Comment by prasant206** [comment]
We are also getting the same error , while we select amazon pay then place order button text was missing . we are using Amasty one page checkout version ::2.4.0 amd magento version's is:: 2.3.
Does anyone have an solution for that.

**Comment by tarishah** [comment]
@prasant206 @hammockvienna I have reached  out to Amasty support. They are asking for the email address that was used for the extension purchase at amasty.com and at least 1 order ID, could you please provide this info by sending an email at payments-cp-devel@amazon.com ?

Thanks,
Tarini

**Comment by RayAnaya** [comment]
Hello all,

I am going to go ahead and close this issue for now due to the fact that we have had some improvements and features built within the plugin that allows it to work 'better' with other plugins.

If you continue to experience cross-plugin problems related to this issue, please re-open this issue or email us at payments-cp-devel@amazon.com.
