### ISSUE TITLE
customer-addresses.js Error

### ISSUE THREAD

**Issue by juhanix** [amzn/amazon-payments-magento-2-plugin#36]
#### What I expected

I exptected no error message

#### What happened instead

Chrome Developer Tools throws the error 
`Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.getAddressItems (customer-addresses.js:20)
    at address-list.js:13
    at Object.execCb (require.js:1650)
    at Object.context.execCb (resolver.js:131)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
    at require.js:1156
    at each (require.js:57)
    at Module.emit (require.js:1155)
    at Module.check (require.js:917)
    at Module.enable (require.js:1143)
    at Module.init (require.js:774)
    at Module.<anonymous> (require.js:991)
    at require.js:132`

after enabling Amazon_Login (Core and Payment are enabled), if i disable Amazon_Login it does not throw the error anymore.

#### Steps to reproduce the issue

- `php bin/magento module:enable Amazon_Core Amazon_Login Amazon_Payment --clear-static-content`
- `php bin/magento setup:upgrade`
- `php bin/magento setup:di:compile`
- `php bin/magento setup:static-content:deploy de_DE`
- surf any site on the webshop (except: /checkout/ and /checkout/cart/)
- error message appears

_FYI:_
- Checkout_Cart and Checkout_Process **do not** throw this error
- system.log not throwing nothing of importance

#### Your setup

* Magento version: 2.1.4
* Magento Edition: Community
* JavaScript Console: 

![image](https://cloud.githubusercontent.com/assets/13943759/23021276/83045794-f44b-11e6-8ebe-0e5a20daa705.png)

#### Conclusion

The site does not break, everything else seems to load fine, I'm just curious if anyone else is also having the same problem?

**Comment by danielneu** [comment]
Thanks for reporting this issue.

I have seen this happening myself but did not associate it with the Amazon Payments module.
This will be investigated soon.

Best wishes
Daniel

**Comment by OnTapSupport** [comment]
Hi @juhanix

We will be assisting you on behalf of Amazon to get this matter resolved. We are going to replicate the environment you have suggested, and let you know what we find.

Regards,
Support Team.

**Comment by danielneu** [comment]
Hello,

sorry for the delay in getting back to you.
It seems this is not related to the Amazon Pay module, it looks like the Magento 2 core issue: https://github.com/magento/magento2/issues/7115

There is a fix available since quite a while, but it did not make it into the Magento core code yet:
https://github.com/magento/magento2/commit/0195c22e8305d93cc893fb83fd0e28c1fc250aa6

Best wishes 
Daniel
