### ISSUE TITLE
AP Doesn't Work with M2 Enterprise Cloud Multishipping Functionality

### ISSUE THREAD

**Issue by egoodeve** [amzn/amazon-payments-magento-2-plugin#365]
#### What I expected

To be able to checkout with AP using M2's native multishipping feature OR to have this option hidden from multishipping if enabled for standard checkout.

#### What happened instead

Unable to login to AP when selected and receive errors when placing the order

#### Steps to reproduce the issue
- Create an account and add a few items to your cart. 
- Go to /multishipping/checkout 
- Step through multishipping process to the Billing Info section
- Select AmazonPay on and note how it doesn't prompt the login modal
<img width="613" alt="billing" src="https://user-images.githubusercontent.com/8367590/46897515-e1b41a00-ce37-11e8-9bb6-4d1a04713b25.png">
 
- Proceed to Review Order and click Place Order
- Takes you to  /multishipping/checkout/results/ with errors about AP connectivity

>  Unfortunately it is not possible to Pay with Amazon Pay for this order. Please choose another payment method. Please see details below. 

![46895408-153d7700-ce2d-11e8-8022-fb380c59e82f](https://user-images.githubusercontent.com/8367590/46897523-e973be80-ce37-11e8-8cb4-fca966182d13.png)

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: Module version: 2.0.14
* Magento Edition: Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by tarishah** [comment]
@egoodeve Sorry for the late response. Amazon Pay doesnot work with multishipping feature.

Were you able to hide Amazon Pay button when this feature is used?

**Comment by RayAnaya** [comment]
I'm going to go ahead and close this issue as we have not heard back on hiding Amazon Pay as a payment option for multi-shipping scenarios.  If you have any further issues or questions, please feel free to re-open this issue!
