### ISSUE TITLE
IE 11 Error "Expected identifier"

### ISSUE THREAD

**Issue by gclift** [amzn/amazon-payments-magento-2-plugin#367]
On the Magento 2.2.6 checkout page with Amazon Pay enabled, there is a javascript error in IE 11. The error is coming from the amazonlogin.js. The function parameters on line 19 contain a trailing comma which IE 11 throws an error. From my reading, trailing commas in function parameters was not added until ECMAScript 2017. 

* Magento version: 2.2.6
* Amazon Pay Extension Version: "amzn/amazon-pay-module": "2.1.0"
* Magento Edition: Community 
* JavaScript Console: (see below) showing the error "Expected identifier"
* OS&Browser: Window 10 / IE 11

![amzpay-ie11-amazonlogin-issue](https://user-images.githubusercontent.com/2327942/47036136-0b6f8880-d139-11e8-91bf-ab6f775580af.png)

Currently 
```
    function ($,
        Component,
        ko,
        amazonStorage,
        storage,
        amazonPaymentConfig,
        registry,
        loginButton,
    ) {
```

Suggested Fix
```
    function ($,
        Component,
        ko,
        amazonStorage,
        storage,
        amazonPaymentConfig,
        registry,
        loginButton
    ) {

```

**Comment by tarishah** [comment]
Closing. This issue has been fixed here: https://github.com/amzn/amazon-payments-magento-2-plugin/commit/7172998afc544f771d2d92d79242149a11f39718. Master branch contains the fix.
