### ISSUE TITLE
AP 2.2.2 installing on M2.2.5

### ISSUE THREAD

**Issue by BernardRobbins** [amzn/amazon-payments-magento-2-plugin#375]
#### What I expected
Composer update on Magento 2.2.5 to install only AP 2.0.15

#### What happened instead
Composer update on Magento 2.2.5 installed AP 2.2.2

#### Steps to reproduce the issue
Run composer update on magento/product-community-edition 2.2.5

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 2.2.2
* Magento Edition: Community 
* Shop URL : our internal dev sites

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of Magento 2.
