### ISSUE TITLE
http method not allowed sucuri firewall

### ISSUE THREAD

**Issue by sivajik34** [amzn/amazon-payments-magento-2-plugin#377]
checkout should go smooth
#### What happened instead

403 issue:

#### Steps to reproduce the issue
1. login with customer info.
2.add product to cart
3.go to checkout 
Sucuri WebSite Firewall - Access Denied
Block reason:HTTP method not allowed.
oururl/rest/xxx/V1/amazon-billing-address/S01-7907337-6181013

#### Your setup

* Magento version: 2.2.6
* Amazon Pay Extension Version: 2.1.0 from composer.json
* Magento Edition:  Enterprise 
* JavaScript Console: Sucuri WebSite Firewall - Access Denied
Block reason:HTTP method not allowed.
oururl/rest/xxx/V1/amazon-billing-address/S01-7907337-6181013
* Shop URL :

**Comment by sivajik34** [comment]
i think it should take https instead of http.  
i mean https://oururl/rest/footballamerica_en/V1/amazon-billing-address/S01-7907337-6181013

**Comment by prayagr** [comment]
Hi @sivajik34 , my apologies for the late response. If I understand correctly, your checkout page was not 'https' enabled - Amazon Pay requires the cart and checkout pages to be on https instead of http in order to securely run. Can you confirm if you are still facing this issue?

**Comment by sivajik34** [comment]
@prayagr thanks for your response.Now its working fine.

**Comment by prayagr** [comment]
Thanks, I am closing this.
