### ISSUE TITLE
shop name single quote ' throws error in adminhtml

### ISSUE THREAD

**Issue by yaroslav-zenin** [amzn/amazon-payments-magento-2-plugin#391]
#### What I expected

open adminhtml/payment/configuration working page
#### What happened instead
thrown error on page

```
VM6421:2 Uncaught SyntaxError: Unexpected end of JSON input
```
#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 2.2.5
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
![image](https://user-images.githubusercontent.com/27727454/48078256-b1bb2500-e1f1-11e8-8555-05f1150ede6f.png)

error has been occured because of 
```html
<div data-mage-init='{"Amazon_Core/js/simplepath": ... "merchantStoreDescription":"shop name with single ' quote"}'></div>
```

**Comment by prayagr** [comment]
Hi @yaroslav-zenin , thanks for reporting the issue and providing a potential fix as well. With Magento 2.2.5, Amazon Pay (AP) v2.0.12 is packaged by default.

A composer update upgrades the AP extension to 2.2.5. I am not sure how M2.2.5 interacts with AP2.2.5, but we will test and get back to you.

**Comment by RayAnaya** [comment]
Hi all,

This issue had been reported separately and as there have been numerous new versions and features released (both by Magento and by Amazon Pay), I'm going to go ahead and close this issue.

If you continue to observe this issue, or similar ones related to upgrade paths (especially with our newest versions) please re-open this issue and let us know!
