### ISSUE TITLE
Amazon Pay button issue on mini cart

### ISSUE THREAD

**Issue by nafees1988** [amzn/amazon-payments-magento-2-plugin#399]
Hi,
I installed Amazon Pay version 1.2.6 on magento version 2.24. Its working fine except one issue that on mini cart that Amazon Pay button some times does not appear.

**Comment by prayagr** [comment]
Hi @nafees1988 , sorry for the delay - are you still seeing this error? I was not able to reproduce this on my test 2.2.4 instance.

**Comment by nafees1988** [comment]
@prayagr hi, still having the same issue.

**Comment by prayagr** [comment]
Can you share the URL with us where we can reproduce this? If you want to keep it private, please email it to us at payments-cp-devel@amazon.com

**Comment by johnvanrees** [comment]
I have the same issue with Magento 2.2.5 and multiple versions of Amazon Pay including 2.2.10. Has there been a resolution to this problem?

**Comment by lemked** [comment]
Hi @johnvanrees ,

Can you share a URL where this issue can be reproduced? If confidential, please share the URL via payments-cp-devel@amazon.com.

Kind regards,
Daniel

**Comment by johnvanrees** [comment]
This was a conflict with Nextopia Search which was was resolved with the latest update to Nextopia 2.2.2.

**Comment by tarishah** [comment]
@johnvanrees Thanks for the update. Closing the issue.
