### ISSUE TITLE
Currency issue

### ISSUE THREAD

**Issue by hryksbt** [amzn/amazon-payments-magento-2-plugin#406]
When I set bace currency is JPY but allowed currency is USD, Amazon Pay and Amazon login are not displayed.
But if both settings are JPY, those button are appeared.
I think this module look allowed currency setting.
This is invalid.
Magento' concept is payment currency is set by base currency.
So this must must work my case.
Developer have to fix this issue to see only base currency.

Ex: 10,000JPY(Base currency) = US$90(Allowed currency)
      Magento should through 10,000JPY to Amazon Pay API.

Built in Amazon Pay module of Magento CE 2.2.7.

I asked Amazon supporter. They said I have to ask here.
So I commented here.

Thank you.

**Comment by lemked** [comment]
That's correct, the Amazon Pay button shows up only if base currency and display currency of the store view are the same and if it's matching the region selected in the extension settings (United Stats <> USD, Euro Region <> EUR, etc).

We have plans to introduce multi-currency support for our extension in 2019, which will require changes in the same scope. This should allow us to fix this issue at the very same time.

**Comment by hryksbt** [comment]
Magento is No.1 share e-commerce platform as you know.
But many people who use Magento cannot use by current specification.
I think this is very high priority issue.
We will try to update by ourself then we will post pull request here.

**Comment by lemked** [comment]
Hi @hryksbt ,

It does have a very high priority for us to look into this as we are aware that there is a high number of customers affected by this problem. We hope to get the required changes into the code base soon enough so that it will be available probably with the release of Magento 2.2.8 and 2.3.1.

Kind regards,
Daniel

**Comment by lemked** [comment]
This issue will be addressed with the release of our multi-currency feature, that will be available with Magento 2.3.1 (related pull request is #415). The current master branch in this repository already contains the required changes.

Leaving this issue open until new version has been released.

**Comment by lemked** [comment]
Fixed with version 3.1.4 that is included in Magento 2.3.1. Closing issue. Please re-open if still facing this issue.
