### ISSUE TITLE
Error 400 on https://payments.amazon.de/checkout/clear?coe=DE&env=SANDBOX

### ISSUE THREAD

**Issue by jpmaligne** [amzn/amazon-payments-magento-2-plugin#407]
#### What I expected

I expect the amazon pay button to appear

#### What happened instead

Nothing is displayed and in the network panel I can see :

https://payments.amazon.de/checkout/clear?coe=DE&env=SANDBOX 

with a 400 status code

and in the body 

{clear:false}

#### Steps to reproduce the issue

1. install the plugin using composer
1. configure it in admin panel using amazon seller central credentials etc.
1. open one of your product page
=> the issue happened

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 2.0.15 
* Magento Edition: Community 
* JavaScript Console: 
![selection_001](https://user-images.githubusercontent.com/16101039/50522172-d46b0b00-0ac9-11e9-8e2c-7c01c93514b2.png)

* Shop URL : local dev environment

**Comment by jpmaligne** [comment]
Actually this error was caused because we hardcoded an amazon button during tests.

Sorry for the inconvenience.

**Comment by lemked** [comment]
This issue has been solved by our engineering team. Please re-open, should this still apply.
