### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by SasiKiranK** [amzn/amazon-payments-magento-2-plugin#41]
Hi Team

I tried installing the module. it doesn't work. 
Tried:
Manual and composer installation. Instructions not provided.
composer require amzn/amazon-pay-and-login-magento-2-module
is the above one is for composer installation.

Please assist.

Thanks
Sasikiran Kesavan

**Comment by danielneu** [comment]
Hi,

"require" would require this module being listed on packagist, which it is not yet.
Please add it manually to your composer.json and add a repo  entry to github and you can proceed with the installation.

Best wishes
Daniel
