### ISSUE TITLE
OrderTotal of zero not handled perfectly

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#42]
#### What I expected

When the order total is zero, payments can not be done using Amazon Pay. In this case, a meaningful message to the customer should be shown and a simple way to complete the purchase should be possible.

#### What happened instead

If a voucher drops the total to zero, the "place order" button disappears, no message to the customer is shown. The customer is stuck in the checkout.

#### Steps to reproduce the issue

Create a 100% off voucher and apply it in the checkkout.
Please also check what happens if we drop  too zero in the cart alread.

**Comment by cosmointeractive** [comment]
When can we expect a release of 1.1.1? Should we patch the extension ourselves?

**Comment by cosmointeractive** [comment]
I'm assuming that the 1.1.1 changes are not available through the composer update method.

**Comment by danielneu** [comment]
The 1.1.1 release is in preparation and will be released on Github today, most likely as well today on the Magento Marketplace.
