### ISSUE TITLE
AmazonLogin: logged as different customer on Magento frontend.

### ISSUE THREAD

**Issue by qsolutions-pl** [amzn/amazon-payments-magento-2-plugin#420]
#### What I expected
Throw an error when Magento 2 Customer does not exists.

User should not be logged in Magento if there is no email related to Amazon Account.

#### What happened instead

User is logged in to Magento 2, but as a different user (random customer).

#### Steps to reproduce the issue

I've configured Amazon Login and Amazon Pay on my installation.
I don't have a customer account in Magento related to my email address.
When I click "Login with Amazon" I am redirected to Amazon popup, I put my email and password, Amazon logs me in, Magento logs me in as different customer (it should throw an error or redirect me to registration page)
I don't have any customizations done to login features.

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 2.0.15
* Magento Edition: Enterprise
* JavaScript Console: no errors
* Shop URL :

**Comment by lemked** [comment]
The 'implicit' account creation is supposed to work like that with "Login with Amazon". This means that if you don't have an account yet, a new account will be created using the email address associated with your Amazon account.

I'm not sure why you are stating that you are logged in as a "random customer". Can you outline this and provide a screenshot if possible (please obfuscate any information that may identify a user).

Kind regards,
Daniel

**Comment by islandskater43** [comment]
@qsolutions-pl - can you please email us at payments-cp-devel@amazon.com with additional details so that we can work with you on this?

**Comment by lemked** [comment]
Thank you, email was received. We will follow-up with you by email.

**Comment by qsolutions-pl** [comment]
Please close the issues, I've found out that the problem was related to amazon_customer table not being sync with Magento Migration tool. Problem solved :-)

**Comment by lemked** [comment]
Thanks for the feedback! Closing.
