### ISSUE TITLE
Apostrophe in Site Name Causes JSON Parse Error

### ISSUE THREAD

**Issue by ryandiamond23** [amzn/amazon-payments-magento-2-plugin#428]
Apostrophe in Site Name Causes JSON Parse Error

#### What I expected

No Javascript errors on Magento admin payment methods configuration

#### What happened instead

JSON parse error due to unescaped apostrophe (') in site name -- Burt's Bees Baby

#### Steps to reproduce the issue

Set site name with an apostrophe and then try to hit payments method page. All JS functionality is broken due to JSON parse error.

#### Your setup

* Magento version: 2.2.7
* Amazon Pay Extension Version: 2.1.2
* Magento Edition: Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
<img width="702" alt="screen shot 2019-02-05 at 9 55 08 am" src="https://user-images.githubusercontent.com/9298925/52281574-66b5c880-292c-11e9-8182-394967be8c49.png">
<img width="1573" alt="screen shot 2019-02-05 at 9 55 33 am" src="https://user-images.githubusercontent.com/9298925/52281588-6ae1e600-292c-11e9-806e-5905a7b1a788.png">

**Comment by lemked** [comment]
Hi @ryandiamond23 ,

Thank you for reporting this issue. We will look into it and provide back feedback here.

Kind regards,
Daniel

**Comment by sargon1404** [comment]
In case it helps someone, here's a fix:
File:
> vendor/amzn/amazon-pay-and-login-with-amazon-core-module/Model/Config/SimplePath.php  

Replace Line: 487
`'merchantStoreDescription'    => $this->getConfig('general/store_information/name'),`

with:
`'merchantStoreDescription'    => htmlspecialchars($this->getConfig('general/store_information/name'), ENT_QUOTES),`

**Comment by lemked** [comment]
Thanks @sargon1404 ,

We'll check if the proposed fix solves the issue and merge it into the code base then.

Kind regards,
Daniel

**Comment by bjguillot** [comment]
Confirming issue also exists in Magento 2.3.0.  I had a merchant contact the US support team with same issue.

**Comment by tarishah** [comment]
@bjguillot We are working on this issue with a high priority. Will provide update as we get.

**Comment by tarishah** [comment]
@bjguillot Fix for 2.3.0 can be seen in this commit - https://github.com/amzn/amazon-payments-magento-2-plugin/commit/95c0e31790b1ef2d034c4a5cd21a03d8507bc6c5.
master branch has this commit tested and merged.

**Comment by tarishah** [comment]
@ryandiamond23 Fix for 2.1.2 is https://github.com/amzn/amazon-payments-magento-2-plugin/commit/9a6de4dfcf39ee33761d106dce670b4b4b417ac4

2.1.x branch is tested and merged with this commit, however there are other additional updates in that branch as well - so I will recommend to apply this change manually in that one file in your 'test instance' first. 

Please let us know how this goes.

Thanks!

**Comment by ryandiamond23** [comment]
@tarishah Yep, that appears to have fixed it! Thanks for the diligence on this -- we had been patching this via Magento2 hot-fixes in the meantime but will remove this patch and update the modules as soon as possible. Thanks to all @sargon1404 @bjguillot @lemked

**Comment by tarishah** [comment]
Thanks @ryandiamond23 Closing this.
