### ISSUE TITLE
[Magento 2.1] Obsolete reference to a css

### ISSUE THREAD

**Issue by korostii** [amzn/amazon-payments-magento-2-plugin#43]
#### What I expected
No errors in the exception.log

#### What happened instead
An error in exception.log:
[2017-03-13 11:04:58] main.CRITICAL: Magento\Framework\View\Asset\File\NotFoundException: Unable to get content for 'adminhtml/Magento/backend/en_US/Magento_Catalog/catalog/category-selector.min.css'

#### Steps to reproduce the issue
Open    admin > Stores > Configuration    while having the plugin installed

#### Your setup
* Magento version: 2.1.5
* Magento Edition: Community

#### Additional info
I think [this](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Core/view/adminhtml/layout/adminhtml_system_config_edit.xml#L20) is where the css in being referenced

It seems that category-selector.css got deleted from Magento 2.1.x branch codebase but is still referenced by the plugin

https://github.com/magento/magento2/tree/2.0/app/code/Magento/Catalog/view/adminhtml/web/catalog
https://github.com/magento/magento2/tree/2.1/app/code/Magento/Catalog/view/adminhtml/web/catalog

**Comment by danielneu** [comment]
This was resolved and will be fixed in the next version
