### ISSUE TITLE
Add sort order configuration

### ISSUE THREAD

**Issue by bamboekeizer** [amzn/amazon-payments-magento-2-plugin#440]
Amazon Pay is showing up as first payment option when multiple payment methods exist. 

A sort order confirgurable field should be added in Admin, as to place Amazon Pay in the order as desired in checkout. 
Other payment options already have a sort order field.

* Magento version: 2..3.0
* Amazon Pay Extension Version: included in 2.3.0
* Magento Edition: Community

**Comment by lemked** [comment]
Thank you @bamboekeizer ,

We will consider this for our product road-map.

Kind regards,
Daniel

**Comment by hammockvienna** [comment]
any news on this issue? I guess from an Amazon point of view thats more "low priority" ? :-)

**Comment by RayAnaya** [comment]
Hi @hammockvienna,

Our apologies for not responding further!  I am going to investigate this request with the team and will let you know within the next 2 weeks as to whether or not this is something we'd like to build in to the plugin.

**Comment by RayAnaya** [comment]
Hey @woutk88,

Thank you for your PR.  We will review this in the next few weeks (I apologize, we do not have a firm deadline) for inclusion in our plugin.  At first-glance, it looks great though - and I just wanted to let you know this / thank you for your contribution.

**Comment by Eddcapone** [comment]
@RayAnaya Can you please implement it finally?! I understand that you dont have an interest to not change the sort order, so that your method is showing at the top, but do you really think that we developers are so stupid to not resort it by using javascript?

**Comment by RayAnaya** [comment]
> @RayAnaya Can you please implement it finally?! I understand that you have an interest to not change the sort order, so that your method is showing at the top, but do you really think that we developers are so stupid to not resort it by using javascript? So please solve it properly, this is ridicoulous.

Hi @Eddcapone - I appreciate and understand your frustration.  I know this seems like a very simple change, and it's been sitting in our backlog for months, but we've had a number of higher-priority features and fixes to implement.  As you mentioned, there is an 'easy' work-around via JavaScript, but again - I understand you'd rather not have to build some custom code on -top- of our extension which should just work.

I do want to say that our slowness in implementing this does **not** have anything to do with our desire to be shown first, but that complaints or requests about sort order are simply few and far between.  To hopefully add perspective to this, we are releasing an entirely new version of our plugin in early February (both here on GitHub and via the Magento Marketplace) which has consumed **a lot** of dev cycles, and which also means we are not able to accept pull requests from contributors, without a lot of legal and security reviews.

Again, this is not an excuse, I just wanted to share with you that we 1) Do fully intend on implementing this, 2) Have not been able to do so yet, and 3) Are planning to release an entirely new version of this extension in February.

**Comment by Eddcapone** [comment]
@RayAnaya okay, I can accept this. Thank you very much!

**Comment by jaybeckr** [comment]
Hi @bamboekeizer / @hammockvienna / @Eddcapone - thanks for reporting and your patience on this issue. It has been implemented and will be included in the next release to Magento Marketplace - https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html
