### ISSUE TITLE
Amazon Login returns wrong customer.id from Amazon

### ISSUE THREAD

**Issue by qsolutions-pl** [amzn/amazon-payments-magento-2-plugin#441]
Ok, so this issue is tricky so I need to explain in more details
1) We have working Magento 1 integration with Amazon Login, when I click "Login with Amazon", my customer ID is returned from Amazon (SOAP Request I think), which is
`amzn1.account.AGC6KRQWE6OH3Z7SZJJHKDQXP2TQ` - same as an entry in `amazon_login` table
that same amazon id is stored in customer_login table
2) We have imported all Customer data to Magento 2 Enterprise Edition.
All data is stored in `amazon_customer` table and it reflects Magento 1 data

When I try to login with Amazon... Amazon returns my customer ID:
`amzn1.account.AFLEE6I66BZHLONS7FER3HLVA4JA`
which is not stored anywhere nor in Magento1, nor in Magento 2 database.

Is AmazonID for amazon login somehow domain related?
My email is: jwinkler@qsolutionsstudio.com
We use live Amazon account to wrap up testing and launch project in 2 weeks - this is the last issue we face. 

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 2.2.7
* Magento Edition: Enterprise
* JavaScript Console: no errors

**Comment by tarishah** [comment]
@qsolutions-pl Thanks for reaching out! 

Let me get back to you in couple of days with an explanation on this. 

Thanks,
Tarini S.
Amazon Pay

**Comment by tarishah** [comment]
@qsolutions-pl Are you using the same Amazon Pay merchant account for both M1 and M2 instances?
Different customer IDs are returned for different merchant accounts and similar for a single merchant account. 

Look forward to hear from you.
Thanks!

**Comment by christianzichichi** [comment]
Hi @qsolutions-pl ,

As we noticed no further input from you I am going to have to go ahead and close this issue for now. If you need further support please provide any details to payments-cp-devel@amazon.com, we would be glad to help you troubleshoot further.

Thanks
Regards

Christian
