### ISSUE TITLE
Missing street on checkout page

### ISSUE THREAD

**Issue by matekovacs-srg** [amzn/amazon-payments-magento-2-plugin#442]
Hi!

I have an annoying problem with this plugin. I'm using Magento 2.3.1 with the default installed amazon's payments plugin (amzn/amazon-pay-module : 3.1.4) and porto theme.
When I try to pay with a selected amazon shipping address/credit card and then I click the buy/pay button I always get the "Please check the shipping address information. "street" is required. Enter and try again." ... but actually I already filled out the street field.

What I already find out is that, when I select an address then the javascript send a POST ajax request to the "/rest/at/V1/carts/mine/estimate-shipping-methods" url with the address data, but unfortunately the street field is empty.

I hope someone can help me.

Thanks in advance!

**Comment by tarishah** [comment]
@matekovacs-srg Thanks for reaching out. Please provide further site details and logs if possible. 
Send them to payments-cp-devel@amazon.com referencing this GH issue.

Look forward to hear from you.
Thanks!

**Comment by matekovacs-srg** [comment]
@tarishah Thanks, I sent an email!

**Comment by lemked** [comment]
Issue confirmed. Looking into it.

**Comment by lemked** [comment]
Bug fix releases for this issue:

* 3.x and higher: https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/3.1.5
* 2.2.6 - 2.2.x: https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/2.1.4

**Comment by lemked** [comment]
Alternative way for patch existing installations shown below.

```
cd <magento installation directory>
cd vendor/amzn/amazon-pay-and-login-with-amazon-core-module/
curl https://github.com/amzn/amazon-payments-magento-2-plugin/commit/7c3735158a06875eb44be6fbffc2310c291a4713.patch | patch -p 3
```

**Comment by Trenk** [comment]
Hello,

I have the same problem with Magento 2.3.1 after the update.

that does not work:
cd <magento installation directory>
cd vendor / amzn / amazon-pay-and-login-with-amazon-core-module /
curl https://github.com/amzn/amazon-payments-magento-2-plugin/commit/7c3735158a06875eb44be6fbffc2310c291a4713.patch | patch -p 3

Is there still another possibility over the Composer or manual?

I have no experience with Github yet.

Thank you for a short help
