### ISSUE TITLE
No such entity with cartId 

### ISSUE THREAD

**Issue by lfritsche** [amzn/amazon-payments-magento-2-plugin#451]
#### What I expected

Create an online invoice for an order payed via Amazon Pay

#### What happened instead

Get error message: `No such entity with cartId 12345``
It's not possible to create an online invoice with capture for certain orders - not all.

#### Steps to reproduce the issue

Unfortunately the mentioned cartId is really missing in the database for those orders.
The manual process works:
1. create an offline invoice instead
2. capture the amount manually in the Amzn Seller backend.

Other payment methods work fine. It's related to Amazon Pay only.
The authorization entry within the transactions section is also fine.

I haven't found a pattern yet why some invoices can be created regularly and others not.

#### Your setup

* Magento version: 2.2.6

amzn/amazon-pay-and-login-with-amazon-core-module 2.1.0     Shared functionality for Amazon Pay and Login with Amazon modules
amzn/amazon-pay-module                            2.1.0     Amazon Pay module
amzn/amazon-pay-sdk-php                           3.4.1     Amazon Pay SDK (PHP)
amzn/login-with-amazon-module                     2.1.0     Login with Amazon module

* Magento Edition: Community

**Comment by kerlama** [comment]
I can confirm this with 2.1.4 amazon module and magento 2.2.8
With one small exception, that other payment methods, like stripe are also affected by this. Order passes by no such entity with cartId is shown on checkout.

**Comment by lfritsche** [comment]
Hi @lemked,

do you have any update on this issue or have you been able to reproduce it?
The cartId seems to be a reference to the initial quote which is not available for those orders any more when trying to generate the invoice (Database entry is missing). Why is the quote still necessary during invoicing - I thought quotes would be converted to orders on purchase?

Best,
Leander

**Comment by nadeefit6** [comment]
This issue can be reproduced in 2.2.7. Any update on this?

**Comment by lemked** [comment]
Hi everyone,

Unfortunately we cannot provide an update to this yet. We will look into it as soon as possible.

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked,

as we are creating invoices offline now for two weeks and capturing the amounts manually at the seller central it would be great to hear whether or not you've been able to reproduce this issue.

I don't know whether the extension deletes the quote after creating the order, or if that's a native magento behaviour and the extension relies on this quote when creating the invoice.

If the extension delete's the quote by mistake you may find that out quite quickly or in the other case, if invoice generation depends on an not existing database quote entry you would have to follow the dependencies on order creation.

I'm not able to debug on my own, but maybe you are already a step further and can provide us an update?

Thanks & best regards,
Leander

**Comment by lemked** [comment]
Hi @lfritsche ,

Unfortunately, I cannot provide an update on this issue yet. We have limited resources only and are currently working on other high priority items for the upcoming 2.2.9 / 2.3.2 release of Magento. I'll provide an update as soon as we had a chance to investigate this issue. 

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked 

as you have released your PSD2 Update recently with 2.3.2 -> do you have the capacity now to work on this issue? Wo do have to process all payments manually since April and need this process working again.

An additional question: Is the PSD2 Update available für 2.3 only?
I have not seen the information about the Amazon Pay Update in the 2.2.9 Changelog.

Thank you and kind regards,
Leander

**Comment by lemked** [comment]
Hi @lfritsche ,

Yes, we should be able to provide you feedback on this issue soon.
PSD2/MFA is available on the 2.2 branch as well, minimum version is 2.2.9.

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked 

great to hear, it's available in 2.2.* too - thank you.

Kind regards,
Leander

**Comment by bear-mmartin** [comment]
Hi @lfritsche ,

Thanks for reporting this error.  We've been looking into the reported behavior, but have not been able to reproduce it on Magento 2.2.6 with Amazon Pay module 2.1.0.

To help us track down this issue, can you provide us any more details on the following?
* The steps listed under "Steps to Reproduce" appear to be a workaround for this bug, not steps to reproduce.  Can you let us know what steps we can follow to trigger this bug?  I understand it's happening only intermittently, but we'd like to know exactly what your process is when this error appears.
* Where does this error message appear?  In the browser, in Magento's logs, or in the Amazon Pay module's log file?  If possible, can you add a screenshot or full copy/paste of the error message and context?

Thanks!

**Comment by lemked** [comment]
Hi @lfritsche ,

Can you provide feedback on this?

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked & @bear-mmartin ,

In the meanwhile we are on 2.2.8 and are looking forward to deploy 2.2.9 with the new PSD2 compatible Amazon Pay this or next week.

Steps to reproduce:
1. customer buys (configurable) product via Amazon Pay (Amzn Login enabled).
2. Due to preauthorization mode the invoice will be created later upon delivery
3. While importing the tracking numbers via Xtento Tracking Import, or via a manual process the invoice should be created (online invoice, with capture).
4. Unfortunately this step fails with no exact trace in the .log files, but as message in the Magento backend or the Xtento import logs:
![image](https://user-images.githubusercontent.com/15127451/63428972-270e8400-c419-11e9-87e9-5e140d9ee431.png)

- Other Payment Methods: Payone, Paypal (here everything works fine)

In the database every sales_order entry has it's original quote_id as reference.
The error message always points to this id naming it the cart ID.
But a lookup in the quotes table shows, that those referencing entries are missing for Amazon Pay orders. I don't know why the quote is still relevant for a created order in case of an invoice creation; but the missing quote entry leads to this error message.

I tried to manually re-create such an entry on a test-environment and created the invoice  afterwards with online capture successfully.

I hope this information helps?

Best regards,
Leander

**Comment by lemked** [comment]
Thanks @lfritsche , will follow-up shortly.

**Comment by bear-mmartin** [comment]
Hi @lfritsche ,

We haven't been able to find a way to reproduce the missing `quote` table entries on our end.  Orders created using the Amazon Pay method on a Magento 2.2.6 test instance retain their quote entries in the database, and invoices are created without error.
Because a Quote would already need to be present in order for an Order to be created, it seems like the Quote is being deleted somewhere along the line, as you suggested.  I've reviewed the Amazon Pay module code around order creation, and haven't spotted any way a Quote would be deleted there.

To find out where/when Quote items are being deleted, you can add an Observer on the `sales_quote_delete_after` event, and log a stack trace whenever the event is triggered.

By the way, this ticket was initially logged against Magento 2.2.6, but you mentioned in a recent comment that you are running Magento 2.2.8 currently.  Is my understanding correct, that you have upgraded Magento and are still seeing the same problem?

**Comment by lfritsche** [comment]
Hi @bear-mmartin ,

one detail I found out in addition to the previous steps to reproduce:
We are in preauthorization mode and couple the invoicing to the shipment status.
It can be up to 30 days until we generate the invoice.

I now got reported, that invoices created within 24-36 hours after the initial purchase are fine - invoices can be generated. After this timeframe the error occurs.
Maybe this helps?

We are now switching to direct capture, to test this process for a while.
I'll send you an update after running in this mode for a week.

And to your question about 2.2.6->2.2.8
Yes indeed, and this week the 2.2.9 update follows with the new Amazon Pay PSD2 compliant package.

Regards,
Leander

**Comment by lfritsche** [comment]
Hi @lemked 

it works in direct capture mode.
So for the moment we are fine.

But you should probably retest in preauthorization mode to capture the payment some days after the order was created.
Maybe you're able to reproduce the issue following this process.

**Comment by lemked** [comment]
Thanks @lfritsche , will have a look!
