### ISSUE TITLE
System configuration not working after installing this plugin

### ISSUE THREAD

**Issue by axemusiclive** [amzn/amazon-payments-magento-2-plugin#46]
Hello Team,

I have installed this plugin and after installing this plugin i am not able to store any value under store-> configuration section in admin panel

When i try to go to that section, it says session time our and i am logging out from the system

**Comment by danielneu** [comment]
Hi,

thanks for raising this.

Are you sure this has any relation to this module? We are not touching any of the functionalities related to the admin session or lifetime. This has not been experienced before, either.

However, there are a number of >Magento 2 specific complaints around timed out admin sessions.
E.g. https://github.com/magento/magento2/issues/2922

Please also specify Module version, Magento version, ... like asked for in the issue template. This helps us root-causing issues a lot.

Thanks
Daniel

**Comment by axemusiclive** [comment]
Hi ,

Magento version 2.1.4 enterprise edition and version 1.1.0 .

If you need FTP and admin panel access i can provide it to you

Regards,
Arpita

**Comment by danielneu** [comment]
Hi,

we were not able to reproduce this and as said earlier, we are not touching anything admin session related at all in this module, nor have we heard anything similar before related to this module.

I am afraid this module is not the cause of your issue.
