### ISSUE TITLE
Conflict with Sage Pay Suite Pro

### ISSUE THREAD

**Issue by nobuttsalex** [amzn/amazon-payments-magento-2-plugin#48]
#### What I expected

To be able to pay for orders with either Amazon Payments or SagePay (https://store.ebizmarts.com/sage-pay-suite-pro-magento-2.htmlhttps://store.ebizmarts.com/sage-pay-suite-pro-magento-2.html).

#### What happened instead

Amazon Payments module works fine but stops the SagePay module being able to complete the order. I get the following error when trying to make a payment with SagePay:

`Fatal error: Uncaught Error: Call to a member function getMethod() on null in magento2rootdirectory/vendor/amzn/amazon-payments-magento-2-plugin/src/Payment/Observer/CompleteOrderStatus.php on line 56
`
#### Steps to reproduce the issue

Installed this module with composer and installed SagePay module by adding to the app/code directory, have not tested with both modules installed with composer.

#### Your setup

* Magento version: 2.1.5
* Magento Edition: Community

**Comment by danielneu** [comment]
Hi,

this was a known issue and was fixed in #27 (part of release 1.0.10).
Can you update to version 1.1.0 of this module and try again?

Feel free to reach out again if this does not solve the issue, resolving for now.

Best wishes 
Daniel
