### ISSUE TITLE
Amazon Payment Method empty

### ISSUE THREAD

**Issue by DJ0815** [amzn/amazon-payments-magento-2-plugin#485]
#### What I expected

Customer can select his preferred shipping address and Amazon Payment Method

#### What happened instead

Amazon Payment Method Box is not showing up

#### Steps to reproduce the issue

Install Magento 2.3.0 configure pre-installed Amazon Pay Module and try to order a product

#### Your setup

* Magento version: 2.3.0
* Amazon Pay Extension Version:  3.0.0
* Magento Edition: Community
* JavaScript Console: No JavaScript error is shown, so i am posting payment log and a screenshot of checkout page

```
[2019-05-06 09:22:22] amazonClientLogger.DEBUG: <SetOrderReferenceDetailsResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <SetOrderReferenceDetailsResult>
    <OrderReferenceDetails>
      <OrderReferenceStatus>
        <State>Draft</State>
      </OrderReferenceStatus>
      <OrderLanguage>de-DE</OrderLanguage>
      <Destination>
        <DestinationType>Physical</DestinationType>
        <PhysicalDestination> REMOVED </PhysicalDestination>
      </Destination>
      <ExpirationTimestamp>2019-11-02T09:21:36.306Z</ExpirationTimestamp>
      <PlatformId>AUGT0HMCLQVX1</PlatformId>
      <SellerOrderAttributes>
        <StoreName>Deutsch</StoreName>
        <CustomInformation>Magento Version : 2.3.0 Plugin Version : 3.0.0</CustomInformation>
        <SellerOrderId>1000044433</SellerOrderId>
      </SellerOrderAttributes>
      <OrderTotal>
        <CurrencyCode>EUR</CurrencyCode>
        <Amount>22.85</Amount>
      </OrderTotal>
      <PaymentAuthenticationStatus/>
      <ReleaseEnvironment>Live</ReleaseEnvironment>
      <AmazonOrderReferenceId>P02-5816289-5776509</AmazonOrderReferenceId>
      <CreationTimestamp>2019-05-06T09:21:36.306Z</CreationTimestamp>
      <RequestPaymentAuthorization>false</RequestPaymentAuthorization>
    </OrderReferenceDetails>
  </SetOrderReferenceDetailsResult>
  <ResponseMetadata>
    <RequestId>42fb1205-b865-4777-8c3e-49e5672ef39d</RequestId>
  </ResponseMetadata>
</SetOrderReferenceDetailsResponse>
```
![screenshot](https://user-images.githubusercontent.com/29231142/57216890-6c857d80-6ff1-11e9-984b-3ffc7f3320d8.jpg)

**Comment by lemked** [comment]
Hi @DJ0815 ,

Thank you for reporting this issue.

Are there any other checkout extensions installed on your Magento 2 installation? From the screenshot it seems as if this is not a default checkout or default template. If so, I'd recommend to first verify on a staging server if Amazon Pay is working on the default template, with all checkout extensions disabled. Then, re-apply your template and enable one extension by another to identify the root cause of the issue.

Kind regards,
Daniel

**Comment by DJ0815** [comment]
Thanks @lemked, seems like it is really theme related. Sorry for inconveniences.
