### ISSUE TITLE
Button not showing on checkout

### ISSUE THREAD

**Issue by nobuttsalex** [amzn/amazon-payments-magento-2-plugin#49]
#### What I expected

Amazon Payments option on first stage of checkout.

#### What happened instead

Tooltip for Amazon Payments shows but the button is not there.

![image](https://cloud.githubusercontent.com/assets/9484573/24549909/792d7036-1613-11e7-80cf-1755cbb9c7dd.png)

#### Steps to reproduce the issue

amazon-payments-magento-2-plugin 1.1.0
Add an item to cart
Go to checkout

#### Your setup

* Magento version: 2.1.5
* Magento Edition: Community
* JavaScript Console: 
![image](https://cloud.githubusercontent.com/assets/9484573/24549876/58be6a8a-1613-11e7-90e7-505c3b8cd7e3.png)

* Shop URL : https://www.vpoutlet.co.uk

**Comment by nobuttsalex** [comment]
The cause was our theme (https://themeforest.net/item/porto-ultimate-responsive-magento-theme/9725864) includes the header on checkout (including the minicart) meaning the PayWithAmazon button was trying to be rendered twice on the same page. Fixed by overriding the minicart-button.phtml file to not include the button in the minicart.

**Comment by danielneu** [comment]
Thanks for coming back and giving the explanation as well. In the next version we will have an option to disable the mini cart button to save you from overriding the file after an update again.

Best wishes 
Daniel

**Comment by cenzo81** [comment]
Thx! This saved me lot of time !

**Comment by danielneu** [comment]
Hi,

we are about to release version 1.1.4.
This also includes a fix for the button rendering twice issue. No need anymore to change any configuration setting from then on.

Best wishes 
Daniel

**Comment by shashanktest** [comment]
i need amazon pay on checkout payment page but didn't get any solution.Can somebody help me for magento2?
