### ISSUE TITLE
Adjust Checkout Agreements Block

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-2-plugin#5]
In the file `vendor/amazon/module-login-and-pay/src/Payment/view/frontend/web/template/payment/amazon-payment-widget.html` you have this div: 

`<div class="checkout-agreements-block"></div>`

This is what other payment methods have that pulls in the Terms and Agreements checkbox.

      <div class="checkout-agreements-block">
           
               
           
       </div>

Can this be updated in this extension?

**Comment by danielneu** [comment]
@islandskater43 I can ammend the code and test this.
What exactly would be the difference I should see after implementing this?

**Comment by Silarn** [comment]
To answer your question, if you've enabled terms and conditions in checkout, you're supposed to see a check box with a link to view the terms in order to agree. When this is enabled, orders will not validate unless the agreement is agreed to.

**Comment by Silarn** [comment]
What's the status of this? My PR has been working for us without any problems. I'm hoping to return to using the core Amazon code sooner or later.

**Comment by danielneu** [comment]
solved by #11
