### ISSUE TITLE
Amazon pay with Klarna

### ISSUE THREAD

**Issue by mibbinvc** [amzn/amazon-payments-magento-2-plugin#501]
I have implemented the amazon pay with klarna, on checkout as a method, Is it possible to add a redirect url from that?
* Magento version: 2.3.1
* Amazon Pay Extension Version: 3.1.4
* Magento Edition: Community 

`<klarna xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Klarna_KcoCore:etc/klarna.xsd">
    <external_payment_method id="amazon_payment" translate="label description" ifconfig="payment/amazon_payment/active">
        <label>Amazon Payment</label>
        <name>Amazon Pay</name>
        <redirect_url><![CDATA[{{secure_base_url}}amazon_payment/start]]></redirect_url>
        <image_url><![CDATA[https://st1.bgr.in/wp-content/uploads/2018/08/amazon-pay-logo.jpg]]></image_url>
        <description>Checkout using Amazon Payment</description>
        <fee>0</fee>
    </external_payment_method>
</klarna>`

which redirect url can be added with it?

**Comment by tarishah** [comment]
Hello @mibbinvc - can you please reach out to us at payments-cp-devel@amazon.com with details on the Amazon Pay merchant ID, you website url (where Amazon Pay is setup)? 

Look forward to hear from you.
Tarini

**Comment by lemked** [comment]
Hi @mibbinvc ,

Compatibility for Klarna Checkout has been added with version 3.1.4 of our extension, which is bundled with Magento 2.3.1 (see related pull request #401). If you are having issues with using Klarna Checkout along with Amazon Pay, can you please provide details about the problem (screenshots, etc.)?

Related issues:
* https://github.com/amzn/amazon-payments-magento-2-plugin/issues/286
* https://github.com/amzn/amazon-payments-magento-2-plugin/issues/247

Kind regards,
Daniel

**Comment by lemked** [comment]
Hi @mibbinvc ,

Have you been able to verify if the problem can be solved by using a more recent Magento 2 version?

Kind regards,
Daniel

**Comment by RayAnaya** [comment]
Hello,

We are going to mark this issue as resolved for now, as the recommendation was to upgrade to a more recent version of Magento.  If you are still experiencing this issue, please feel free to re-open!
