### ISSUE TITLE
Amazon Pay button not available in English when using payment region JP

### ISSUE THREAD

**Issue by hryksbt** [amzn/amazon-payments-magento-2-plugin#514]
#### What I expected

My amazon account is Japan.
So Amazon pay button is showing on only JPY.
I think this issue is resolved at ver 2.2.7 and 2.3.1.
I updated from 2.2.6 to 2.2.7. But button still not exists.

**Comment by hryksbt** [comment]
No Amazon login button as well.

**Comment by hryksbt** [comment]
Which release includes this update?
https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/2.1.4
This one?

**Comment by lemked** [comment]
Hi @hryksbt ,

The button should show up if the extension was configured correctly.

Can you provide a link where the issue can be reproduced?

Kind regards,
Daniel

**Comment by hryksbt** [comment]
Hi,

Amazon Login not showing.
https://illustration-marker.com/customer/account/login/referer/aHR0cHM6Ly9pbGx1c3RyYXRpb24tbWFya2VyLmNvbS8%2C/

Amazon Payment button is existing in JPY mode too.
Thanks.

**Comment by lemked** [comment]
Hi @hryksbt ,

Did you select Japanse Yen as currency for the store view? If so, it should work fine.

The Login button shows up for me on the account page:
![image](https://user-images.githubusercontent.com/4786477/58485374-35276e00-8164-11e9-86b6-7926642762d3.png)

It also shows up on the product pages, the mini cart and the cart page:
![image](https://user-images.githubusercontent.com/4786477/58485409-4b352e80-8164-11e9-868b-7104cd91f8c2.png)

Kind regards,
Daniel

**Comment by hryksbt** [comment]
I meant they were updated to show in other than Japanese yen from new version of AmazonPay module. But still not showing them in 2.2.7 version.
I reported this issue before.

**Comment by hryksbt** [comment]
I know they are working in Japanese Yen. But they should be displayed other than Japanese Yen.

**Comment by lemked** [comment]
Thanks for the context @hryksbt , I now understand what you are referring to (#406). This has been addressed and fixed with Magento 2.3.1. If you are using Magento 2.2.7, you can try to manually apply the [required changes](https://github.com/amzn/amazon-payments-magento-2-plugin/pull/409/files).

Kind regards,
Daniel

**Comment by hryksbt** [comment]
Ah, ok. You didn't apply fix to 2.2.7 that was released at the same time of 2.3.1.
I got it.

**Comment by lemked** [comment]
That's correct. The fix was implemented as part of our new multi-currency feature that allows buyers to pay in their native currency while merchants are charged in the currency their merchant is registered with. As the Magento 2.2 branch is supposed to incorporate bug fixes only, we've applied the relevant code changes to the 2.3 branch only.

**Comment by hryksbt** [comment]
OK. Thank you.

**Comment by hryksbt** [comment]
Hello,

I updated Magento version to 2.3.1.
Actually AmazonPay and AmazonLogin button are showing up.
But 1 issue here.
My account is issued by Amazon Japan. So the button is showing only by Japanese language.
Will you patch for this issue?

**Comment by lemked** [comment]
Hi @hryksbt ,

Thanks for reporting this issue.

The button for the regions US, EU and UK uses the browser language of the buyer, for Japan however the image is always using Japanese as a language (and also a slightly different image format as when compared to other regions). 

This standard behavior of Amazon Pay and not specific to the Magento 2 extension. Having said that, I agree that this is not ideal for buyers who do not speak Japanese but want to buy on a Japanese website. I will clarify with the team how we can improve this situation and report back here.

Kind regards,
Daniel

**Comment by hryksbt** [comment]
Hi @lemked ,

I got that.
Do you think we should create Amazon Pay account in such as Amazon US?
I think we cannot.

**Comment by lemked** [comment]
Hi @hryksbt ,

You could, but opening a merchant account in the US requires you to possess a legal entity in the US as well. If you do have one already, you can start registration here: https://pay.amazon.com/signup .

Kind regards,
Daniel

**Comment by hryksbt** [comment]
Hi @lemked 

Thank you. But we don't have that.
So we need to use Amazon Pay in Japan but want to use for global market.
We need multi language button and checkout page.

Thank you.

**Comment by lemked** [comment]
Yes, the button should show up in the right language if the buyer's preferred language is set to English, which is currently not supported in Amazon Pay for region Japan.

I'll reach out internally to discuss this topic.

Kind regards,
Daniel

**Comment by hryksbt** [comment]
@lemked OK. Thank you.

**Comment by RayAnaya** [comment]
I am going to close this issue for now, as we have made multiple changes to our plugin (including the GitHub release of our V2Checkout branch) for support across regions.

If none of the updated versions meet your specific request, please feel free to open a new ticket against the newest version.
