### ISSUE TITLE
Amazon Pay interfering with other payment modules even when not used in Magento 2.3.1

### ISSUE THREAD

**Issue by FatchipRobert** [amzn/amazon-payments-magento-2-plugin#516]
#### What I expected

I would expect the Amazon Pay module bundled to a Magento 2 release package to do nothing at all, when it was not explicitly configured to be active.

#### What happened instead

When loading the home page in a freshly installed Magento 2.3.1, your module loads 7 different javascripts, even though your module was not even configured to be used.
Which can be seen here:
![IssueAmazonPayModule](https://user-images.githubusercontent.com/25302155/59509592-c9f2d100-8eb1-11e9-92d7-c8f07edead64.jpg)

Most problematic is, that your amazon-core.js interferes with other modules that implement Amazon Pay themselves.

The amazon-core.js is loaded for every single page in the shop.

The problem is this line:
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/view/frontend/web/js/amazon-core.js#L56

The window.onAmazonPaymentsReady definition is needed for the initialization of the Amazon Pay button and your module blocks it globally for the shop or at least it creates a race-condition where the last script to define window.onAmazonPaymentsReady will dictate the behaviour.

Magento 2 is not the fastest shop system to begin with, so every unneeded script that is being loaded is one script too much.

#### Steps to reproduce the issue

Install a new Magento 2.3.1 without touching the backend configuration. 
Open any page in the frontend and check for the loaded javascripts.

When the amazon-core.js was loaded, then other modules can't add an Amazon Pay button.

#### Your setup

* Magento version: 2.3.1
* Amazon Pay Extension Version: 3.1.4 ( bundled to the Mage 2.3.1 version )
* Magento Edition: Community

#### Conclusion

The described behaviour just started with Magento 2.3.1 or your module version 3.1.4 which is bundled to Mage2.3.1. 
In Magento 2.3.0 ( 3.0.0 of your module ) just one javascript was loaded without activation and other payment modules were not broken.

It would be great if your module would not load any unwanted javascripts if not explicitly activated.

Right now the only solution I could find to solve the problem for our own payment module is to deinstall your module, but that is not a practical solution to communicate to our customers.

Would be great if you consider a change in your module here.

Thank you

**Comment by tarishah** [comment]
@FatchipRobert Thanks for contacting us and raising this issue. We will look into this and release a fix soon. 

Apologies for any inconvenience this must have caused.
Tarini Shah

**Comment by tarishah** [comment]
@FatchipRobert We have released a fix for the issue you have raised here, in our master branch.

Here is the patch command that you can run:  `cd vendor/amzn; curl https://github.com/amzn/amazon-payments-magento-2-plugin/commit/ada4a77603607a25aef1f7ceb9ccc709c6afe43f.patch | sed 's/\/src\/Login\//\/login-with-amazon-module\//g' | sed 's/\/src\/Core\//\/amazon-pay-and-login-with-amazon-core-module\//g' | patch -p1`. 

Note: Here is the [commit](https://github.com/amzn/amazon-payments-magento-2-plugin/commit/ada4a77603607a25aef1f7ceb9ccc709c6afe43f) if you would want to take a look.

**Comment by tarishah** [comment]
Closing this issue for now, please let us know if there are any other concerns.

Thanks!
