### ISSUE TITLE
amazon-pay-and-login-magento-2-module requires amazon-pay-module, causing ambiguous class resolution in autoloader

### ISSUE THREAD

**Issue by uabassguy** [amzn/amazon-payments-magento-2-plugin#530]
#### What I expected
composer update installs 3.2.9 without warnings

#### What happened instead
Generating optimized autoload files
Warning: Ambiguous class resolution, "Amazon\Payment\Api\AddressManagementInterface" was found in both "vendor/amzn/amazon-pay-module/Api/AddressManagementInterface.php" and "vendor/amzn/amazon-payments-magento-2-plugin/src/Payment/Api/AddressManagementInterface.php", the first will be used.

.. Along with too many warnings to list

#### Steps to reproduce the issue
composer require amzn/amazon-payments-magento-2-plugin:3.2.9
composer update

While upgrading to Magento 2.3.2, we also are updating amazon pay. The install succeeds, but generates a ton of warnings.

#### Your setup

* Magento version: 2.3.2
* Amazon Pay Extension Version: 3.2.9
* Magento Edition: Enterprise
* JavaScript Console: N/A
* Shop URL : N/A

**Comment by tarishah** [comment]
@uabassguy Thanks for reaching out. We will get this fixed for the next release. 

Apologies for the inconvenience.
Tarini

**Comment by uabassguy** [comment]
Thank you

**Comment by bear-mmartin** [comment]
Hi @uabassguy ,

If you've installed Magento via composer, then upgrading to Magento 2.3.2 will install version 3.2.9 of the Amazon Pay modules (`amzn/amazon-pay-and-login-with-amazon-core-module`, `amzn/amazon-pay-module`, `amzn/login-with-amazon-module`) from Magento's repository automatically.

Doing a `composer require amzn/amazon-payments-magento-2-plugin:3.2.9` will install _a second copy_ of the Amazon Pay module code from GitHub (via Packagist), which is not what you want.  (This explains the "Ambiguous class resolution" warnings, as those class names are indeed defined twice within your vendor/ directory.)

To clear up the warnings, and to prevent issues the next time you update Magento, you can remove the duplicate package with
`composer remove amzn/amazon-payments-magento-2-plugin`
If you do a `composer show` after that, you should still see the Amazon Pay modules installed at version 3.2.9 .

**Comment by uabassguy** [comment]
Thank you, that did the trick. We were trying to lock the module to a specific version, and were unaware of the package name change. I switched it to amzn/amazon-pay-module instead.
