### ISSUE TITLE
Error on "Buy Now" button click (payment processed, no order in Magento created)

### ISSUE THREAD

**Issue by svorreiter** [amzn/amazon-payments-magento-2-plugin#531]
#### What I expected

we use in our Magento 2.3.2 shop the Amazon Extension of you in version 3.2.11

Unfortunately, it is the case that once Amazon Login was clicked the "buy now" button no
Has effects and nothing else happens. Only when "Ctrl + F5" is made and the goods
basket is reloaded it is possible to click the button "buy now" and then it goes to the
Amazon page woe appears "Payment in progress". After a few seconds becomes our shop
but returned with an error page and not the "successful creation".

In the course of such an order, the payment is registered with Amazon and the customer receives an info
the payment is processed by Amazon. However, there is no transaction in our shop,
neither a new customer nor a new purchase order was created in the system.

We are very disturbed by this problem and unfortunately do not know any further, so we turn
to you as a developer of the extension if you already know such problems and have a solution
or accept the topic.

#### What happened instead

once Amazon Login has been clicked the "buy now" button no
Has effects and nothing else happens. Only when "Ctrl + F5" is made and the goods
basket is reloaded it is possible to click the button "buy now" and then it goes to the
Amazon page woe appears "Payment in progress". After a few seconds becomes our shop
but returned with an error page and not the "successful creation".

#### Steps to reproduce the issue

[error-after-amazon-payment.txt](https://github.com/amzn/amazon-payments-magento-2-plugin/files/3405054/error-after-amazon-payment.txt)

#### Your setup

* Magento version: 2.3.2
* Amazon Pay Extension Version:  3.2.11
* Magento Edition: Community 
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : https://impruneta.de

[error-after-amazon-payment.txt](https://github.com/amzn/amazon-payments-magento-2-plugin/files/3405059/error-after-amazon-payment.txt)

**Comment by lemked** [comment]
Dear @svorreiter ,

Thank you for reporting this issue. 

Can you provide a screenshot of your checkout screen along with the Buy Now button? Please make sure the browser console is open when taking the screenshot so that we can see potential errors there.

From the stacktrace it appears as if you are using additional 3rd party extensions (Infortis, Amasty). Can you disable those extensions for testing purposes to see whether the issue persists?

Kind regards,
Daniel

**Comment by svorreiter** [comment]
We have fixed the problems, so the ticket can closed

 

Von: Daniel Lemke <notifications@github.com> 
Gesendet: Freitag, 19. Juli 2019 08:09
An: amzn/amazon-payments-magento-2-plugin <amazon-payments-magento-2-plugin@noreply.github.com>
Cc: Stefan Vorreiter <stefan@vorreiter.eu>; Mention <mention@noreply.github.com>
Betreff: Re: [amzn/amazon-payments-magento-2-plugin] Error on "Buy Now" button click (payment processed, no order in Magento created) (#531)

 

Dear @svorreiter <https://github.com/svorreiter>  ,

Thank you for reporting this issue.

Can you provide a screenshot of your checkout screen along with the Buy Now button? Please make sure the browser console is open when taking the screenshot so that we can see potential errors there.

From the stacktrace it appears as if you are using additional 3rd party extensions (Infortis, Amasty). Can you disable those extensions for testing purposes to see whether the issue persists?

Kind regards,
Daniel

**Comment by lemked** [comment]
Thank you for the feedback, closing.
