### ISSUE TITLE
Update Not Working (M2.3.0)

### ISSUE THREAD

**Issue by snoroozi** [amzn/amazon-payments-magento-2-plugin#533]
Expect version number to be 3.2.9 in Admin

#### What happened instead

Version won't change from 3.0.0

#### Your setup

My magento is 2.3.0 and I updated manually to try to get latest version of the amazon plugin using this guide https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#manual-composer-install-method

I get this https://nimb.ws/bArEHN
And my files still have several directories that I think belong to old installs https://nimb.ws/u5ecJQ
Even though composer updated to correct version https://nimb.ws/xyfuoU

Is there some composer remove I need to run to get rid of all the old files?  

Also attached is my composer.lock which seems to be keeping it locked at 3.0.0 - but I don't know how to update this.
[composer.txt](https://github.com/amzn/amazon-payments-magento-2-plugin/files/3431287/composer.txt)

**Comment by lemked** [comment]
Hi @snoroozi ,

As written in #308, there is currently no easy way to update the extension as it's provided as "Core Bundled Extension" (CBE) with the Magento 2 installation and we have limited control only on the distribution process. We are currently working together with Magento to make it possible to update the extension via the regular composer update command. 

In the meantime, the extension can only be updated manually via patch files or by overwriting the files in the vendor directory. We recommend to use patch files as this ensure that a subsequent composer update will not revert the changes, however, we have to provide patch files for each version set manually. 

We will provide the required files and instructions to update extension version 3.0.0 here by the end of the week.

Kind regards,
Daniel

**Comment by snoroozi** [comment]
@lemked thank you.

A couple questions.

1. In https://github.com/amzn/amazon-payments-magento-2-plugin/issues/308 you mentioned after patch I'll be able to update in future without issues. However, your comments about it being a CBE here seem to contradict that? Curious if I'm going to be able to keep it up to date or not.

2. Are all the directories in my screenshot supposed to still be there, or only the 4th one down?

**Comment by lemked** [comment]
Hi @snoroozi ,

On 1) I'm sorry, I didn't want to cause confusion. Trying to make it more clear: right now, the recommended approach is to update the extension via patch files. Those patch files can be installed via composer. Later this year, this should not be required anymore as it should be possible by then to update the extension directly, without having to install specific patches. Previously installed patches become obsolete by this and can be either removed or ignored (not yet tested as we aren't there yet).

On 2) I've adapted your screenshot. The directory marked in red comes via our GitHub repository and can be removed. Instead, the Core Bundled Extension (CBE) will be used (marked in yellow). The SDK will be required for both "variants" and must not be removed.

![image](https://user-images.githubusercontent.com/4786477/61937894-27d60680-af90-11e9-818f-8d6d88617e83.png)

Kind regards,
Daniel

**Comment by snoroozi** [comment]
Ok got it. So I need to Composer remove what I found under manual install, and then just wait for your patch to update the CBE?

**Comment by lemked** [comment]
Yes, you should be able to safely remove the GitHub version using `composer remove amzn/amazon-payments-magento-2-plugin`. Please be sure to run `composer update` afterwards so that the CBE extension is properly restored in case there are any missing/overwritten files.

We will provide the patch here as soon as possible.

**Comment by snoroozi** [comment]
What's the name of the Composer package for the CBE. I don't want run a catch all composer update and update all my other modules inadvertently

**Comment by snoroozi** [comment]
Hey I'm still waiting on the patch that you send end of week on.  I've had Amazon pay disabled for 2 weeks now after I realized mobile users were getting stuck at you'll be redirected shortly. Hoping this is fixed in latest so I can re-enable

**Comment by lemked** [comment]
Hi @snoroozi ,

The name of the package is the same for both packages, the CBE one and the one provided via GitHub. The CBE one is however hardly coupled with Magento via the composer.lock file, hence you could remove the package via the command mentioned before and re-install via composer update. If you do not have the GitHub repository referenced in your composer.json, you should be able to safely re-install the extension via ``composer require amzn/amazon-payments-magento-2-plugin`` (not tested, but should work).

RE: patch files: sorry that these haven't been provided yet. Will try to get this sorted latest by tomorrow. 

Kind regards,
Daniel

**Comment by snoroozi** [comment]
Update on patch @lemked ?

Can you please give me step by step to clean up the lock file? I'm not sure I'm on the same page as you.

**Comment by snoroozi** [comment]
bippity bump

**Comment by lemked** [comment]
Hi @snoroozi ,

Unfortunately I don't have any news regarding the patch yet. We're waiting for our support agency to provide these.

On the lock file: there shouldn't be any clean up required. If you cannot run ``composer update`` safely, I'd suggest the following:

- open composer.json file and remove the reference to amzn/amazon-payments-magento-2-plugin
- remove directory vendor/amzn/amazon-payments-magento-2-plugin

By this, your Magento 2 installation should be again "on defaults" regarding the Amazon Pay extension. As soon as we have provided you with the patch file instructions, you can then use these to update the CBE extension files safely.

I'm sorry for the delay in providing the files, will follow-up with our agency again and report back here as soon as possible.

Kind regards,
Daniel

**Comment by snoroozi** [comment]
Still nothing?

**Comment by lemked** [comment]
Hi @snoroozi ,

Please use the following instructions to apply the patch.

**Update instructions for Magento 2.3.0**

1. Install the "composer-patches" tool via composer:  

```
composer require cweagans/composer-patches
```

2. Update the "extra" section in composer.json (or add it if it does not exist) with the module name, a patch description, and location of the patch to be applied.
```
        "patches": {
            "amzn/amazon-pay-and-login-with-amazon-core-module": {
                "3.0.0->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.0.0-3.2.9.patch"
            },
            "amzn/amazon-pay-module": {
                "3.0.0->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-module/3.0.0-3.2.9.patch"
            },
            "amzn/login-with-amazon-module": {
                "3.0.0->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/login-with-amazon-module/3.0.0-3.2.9.patch"
            }
        }
```
3. Install the patch via composer:
```
composer -v install
composer update --lock
```

4. Apply the change within Magento:

```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

Kind regards,
Daniel

**Comment by snoroozi** [comment]
@lemked thanks, but composer update is going to update all modules. How can I use this to just apply the amazon update?

**Comment by snoroozi** [comment]
update worked.

**Comment by lemked** [comment]
Thanks for the feedback @snoroozi, closing this then.

Kind regards,
Daniel

**Comment by simonrl** [comment]
Hi,

is there a chance to get patch files for v3.1.4 -> 3.2.9 also?
We're using Magento 2.3.1 where Amazon 3.1.4 comes as CBE, but we need to fix the street address bug that has been addressed in 3.1.5.

Thanks
Simon

**Comment by tarishah** [comment]
Hi @simonrl 

Please use the following instructions to apply the patch.

Install the "composer-patches" tool via composer:

`composer require cweagans/composer-patches`

Update the "extra" section in composer.json (or add it if it does not exist) with the module name, a patch description, and location of the patch to be applied.

```
        "patches": {
            "amzn/amazon-pay-and-login-with-amazon-core-module": {
                "3.1.4->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.1.4-3.2.9.patch"
            },
            "amzn/amazon-pay-module": {
                "3.1.4->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-module/3.1.4-3.2.9.patch"
            },
            "amzn/login-with-amazon-module": {
                "3.1.4->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/login-with-amazon-module/3.1.4-3.2.9.patch"
            }
        }
```

Install the patch via composer:

```
composer -v install
composer update --lock
```

Apply the change within Magento:

```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

Kind regards,
Daniel

**Comment by tarishah** [comment]
Hi @simonrl 

Please use the following instructions to apply the patch.

Install the "composer-patches" tool via composer:

`composer require cweagans/composer-patches`

Update the "extra" section in composer.json (or add it if it does not exist) with the module name, a patch description, and location of the patch to be applied.

```
        "patches": {
            "amzn/amazon-pay-and-login-with-amazon-core-module": {
                "3.1.4->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.1.4-3.2.9.patch"
            },
            "amzn/amazon-pay-module": {
                "3.1.4->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-module/3.1.4-3.2.9.patch"
            },
            "amzn/login-with-amazon-module": {
                "3.1.4->3.2.9": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/login-with-amazon-module/3.1.4-3.2.9.patch"
            }
        }
```

Install the patch via composer:

```
composer -v install
composer update --lock
```

Apply the change within Magento:

```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

Thanks,
Tarini
