### ISSUE TITLE
PHP 7.3.x not supported by sub-packages

### ISSUE THREAD

**Issue by nifr** [amzn/amazon-payments-magento-2-plugin#552]
#### Error Description

The installation of the `amzn/amazon-pay-and-login-with-amazon-core-module` package is rejected on PHP version `7.3.x` due to the current PHP version constraint in `src/{Core,Login,Payment}/composer.json`.

#534 introduced PHP 7.3 support for the main package `amzn/amazon-pay-and-login-magento-2-module` but the `composer.json` files of the sub-modules `src/{Core,Login,Payment}/composer.json` were not updated accordingly.

The following packages are affected:

 *   Package: `amzn/amazon-pay-and-login-with-amazon-core-module`, Version: `3.2.13`
  *  Package: `amzn/login-with-amazon-module`, Version: `3.2.13`
  *  Package: `amzn/amazon-pay-module`, Version: `3.2.13`

[This question](https://stackoverflow.com/q/57473166/1832745) on stackoverflow is related to the issue.

#### Error Message

> amzn/amazon-pay-and-login-with-amazon-core-module 3.2.13 requires php 7.1.3- 7.2.0 your php version 7.3.x doesn't satisfy that requirment.

#### Steps to reproduce the issue

* Use a PHP version that matches version constraint `~7.3.0`
* Run `composer require amzn/amazon-pay-and-login-with-amazon-core-module`

#### Setup

* Amazon Pay Extension Version: **3.2.13**

### How to Fix?

Change `src/{Core,Login,Payment}/composer.json` to include the following lines and publish a new version of the packages.

```json
"require": {
    "php": "~7.1.3||~7.2.0||~7.3.0",
```

**Comment by craigcarnell** [comment]
Please fix this.

**Comment by nifr** [comment]
I've sent a PR to fix the issue. Please update the version after merging.
