### ISSUE TITLE
CompleteOrder.php on line 47 error

### ISSUE THREAD

**Issue by clickdigitalinteractive** [amzn/amazon-payments-magento-2-plugin#56]
when we installed amazon module, if we place an order through another payment provider, (i.e. paypal) we get the following error:

main.CRITICAL: Exception: Notice: Undefined index: state in /vendor/amzn/amazon-pay-and-login-magento-2-module/src/Payment/Observer/CompleteOrder.php on line 47 in /vendor/magento/framework/App/ErrorHandler.php:61

and 

Next Exception: Report ID: webapi-590a4d505babf; Message: Notice: Undefined index: state in /vendor/amzn/amazon-pay-and-login-magento-2-module/src/Payment/Observer/CompleteOrder.php on line 47 in /vendor/magento/framework/Webapi/ErrorProcessor.php:195

#### What I expected

order to be placed

#### What happened instead

error

#### Steps to reproduce the issue

installing amazon module, placing order

#### Your setup

* Magento version: 2.13
* Magento Edition: Community

**Comment by digitalredefned** [comment]
Experiencing the same issue 2.1.6  Was causing paypal payments fail.  Disabled the module and paypal worked.  Following.

**Comment by danielneu** [comment]
Are you using any special module or the built-in PayPal experience?

Best wishes 
Daniel

**Comment by digitalredefned** [comment]
@danielneu - sorry thought I replied to your message but we are using the built in paypal extension.  Thanks for the update.

**Comment by danielneu** [comment]
Thanks.

This will be part of the next release.

Best wishes 
Daniel
