### ISSUE TITLE
Amazon Pay could not process your request. Please try again. {"exception":"[object] (Amazon\\Core\\Exception\\AmazonServiceUnavailableException(code: 0): Amazon Pay could not process your request. Please try again.

### ISSUE THREAD

**Issue by elfeffe** [amzn/amazon-payments-magento-2-plugin#560]
#### What I expected

Complete checkout using Amazon Pay

#### What happened instead

It returns Error 500, and leaves a log saying Amazon Pay could not process your request. Please try again. {"exception":"[object] (Amazon\\Core\\Exception\\AmazonServiceUnavailableException(code: 0): Amazon Pay could not process your request. Please try again.
I think it's the same as https://github.com/amzn/amazon-payments-magento-2-plugin/issues/316

#### Steps to reproduce the issue

Just go to checkout, click the button over the form to pay with Amazon, and as soon as the addresses are shown, I get this error.

#### Your setup

* Magento version: 2.3.2
* Amazon Pay Extension Version: Latest from Composer
* Magento Edition: Community 
* JavaScript Console: https://gyazo.com/72202abb0562c573d1f7299f1419d56e

**Comment by tarishah** [comment]
@elfeffe Can you please list out the website where we can try to replicate?

Thanks,
Tarini

**Comment by elfeffe** [comment]
If you check it now, you can go to m2.irixusa.com and see it

**Comment by elfeffe** [comment]
@tarishah did you check?

**Comment by elfeffe** [comment]
@tarishah I decided to "Test credentials" and I have received an error. Strange, because I didn't invent the credentials, I pasted the ones from Amazon.
So I went again to Amazon to get the credentials JSON, I pasted again and I tested without problems.
After that, it begun to work (or at least is not giving any error at the screen)

**Comment by tarishah** [comment]
@elfeffe Interesting. I can try and replicate that on my end. If I do see any issue, I ll get it fixed. Thanks for bringing this to our attention. 

Please feel free to resolve/close the issue if this is resolved on your end.

**Comment by shilpambb** [comment]
I'm seeing the same error on my local environment connected to the Amazon Pay sandbox. I've tested the credentials in the admin config and the test shows successful. However, I'm getting the please try again error when I try to checkout. I debugged locally, and am actually getting a 403 with an error object that has a Message saying: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

**Comment by shilpambb** [comment]
My issue was that we were running on single store mode, and somehow the wrong credentials got added for store_id=1, which was being used on the frontend. Updating the credentials in the admin was updating the credentials for store_id=0, so it continued to not work even though I entered the correct credentials. I fixed it by deleting the store_id=1 rows from core_config_data.

**Comment by tarishah** [comment]
@elfeffe is this issue resolved? If so, please feel free to close this case.

Thank you,
Tarini

**Comment by elfeffe** [comment]
@tarishah it seems like yes, thank you

**Comment by smadasam** [comment]
Thanks, I had the same issue.  Basically I just created a new "login with amazon" application and used that, and it started working again.

**Comment by aadithyadckap** [comment]
Hi,
I'm also facing this issue.
I am getting the following 403 error in my log file.
"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details".

I have reconfigured the credentials in my Magento admin panel. But it is not working.
Help me to resolve this issue.
