### ISSUE TITLE
Performance of extension attributes amazon_order_reference_id

### ISSUE THREAD

**Issue by addls** [amzn/amazon-payments-magento-2-plugin#564]
#### What I expected
Mysql Index Works

#### What happened instead
If select put the field `amazon_order_reference_id`, 
Mysql index not working, instead is `Using temporary; Using filesort`

/vendor/amzn/amazon-pay-module/etc/extension_attributes.xml
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Quote\Api\Data\CartInterface">
        <attribute code="amazon_order_reference_id" type="string">
            <join reference_table="amazon_quote" reference_field="quote_id" join_on_field="entity_id">
                <field>amazon_order_reference_id</field>
            </join>
        </attribute>
    </extension_attributes>
    <extension_attributes for="Magento\Sales\Api\Data\OrderInterface">
        <attribute code="amazon_order_reference_id" type="string">
            <join reference_table="amazon_sales_order" reference_field="order_id" join_on_field="entity_id">
                <field>amazon_order_reference_id</field>
            </join>
        </attribute>
    </extension_attributes>
</config>
```
#### Steps to reproduce the issue
Sql generated by magento core:
```mysql
EXPLAIN
SELECT
    `main_table`.*,
    `extension_attribute_amazon_order_reference_id`.`amazon_order_reference_id` AS `extension_attribute_amazon_order_reference_id_amazon_order_reference_id`
FROM
    `sc_sales_order` AS `main_table`
LEFT JOIN `sc_amazon_sales_order` AS `extension_attribute_amazon_order_reference_id`
ON
    main_table.entity_id = extension_attribute_amazon_order_reference_id.order_id
ORDER BY
    main_table.entity_id
DESC
LIMIT 10;
```

#### Your setup

* Magento version: 2.2.9
* Amazon Pay Extension Name: amzn/amazon-pay-module
* Amazon Pay Extension Version: 2.2.14
* Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @addls ,
thanks for contacting us. Can you please describe what is the expected behaviour and provide more details about the issue our extension is causing to your Magento installation?
Please feel free to send relevant logs and input data to payments-cp-devel@amazon.com, we will be glad to assist you.

Thanks
Regards

Christian

**Comment by christianzichichi** [comment]
Hi @addls , I'm closing this issue for now as it's regarding a branch of Magento 2 that is not officially supported anymore (2.2.x). If encounter the same issue on a newer release of 2.3.x (current branch), feel free to reopen it or contact us at payments-cp-devel@amazon.com.

Thanks
Regards

Christian
