### ISSUE TITLE
Many rogue queries even when disabled.

### ISSUE THREAD

**Issue by ragboy** [amzn/amazon-payments-magento-2-plugin#566]
#### What I expected

We are not using this module, it is not enabled in configuration, although it is enabled by default in config.php.

#### What happened instead

Our database is being inundated with queries like this:

```
SELECT `main_table`.*, `extension_attribute_amazon_order_reference_id`.`amazon_order_reference_id` AS `extension_attribute_amazon_order_reference_id_amazon_order_reference_id`, `extension_attribute_amazon_order_reference_id`.`quote_id` AS `extension_attribute_amazon_order_reference_id_quote_id`, `extension_attribute_amazon_order_reference_id`.`sandbox_simulation_reference` AS `extension_attribute_amazon_order_reference_id_sandbox_simulation_reference`, `extension_attribute_amazon_order_reference_id`.`confirmed` AS `extension_attribute_amazon_order_reference_id_confirmed` FROM `quote` AS `main_table`
 LEFT JOIN `amazon_quote` AS `extension_attribute_amazon_order_reference_id` ON main_table.entity_id = extension_attribute_amazon_order_reference_id.quote_id WHERE ((`updated_at` > '2019-10-21 09:35:31')) ORDER BY updated_at DESC
 LIMIT 50 OFFSET 23100
```

They have been going for many hours, and its gotten worse, sometimes 3 queries like this running simultaneously.

#### Steps to reproduce the issue

We just did a major upgrade from 2.1.9 to 2.3.2.

#### Your setup

* Magento version: 2.3.2
* Amazon Pay Extension Version: 3.2.9
* Magento Edition: Enterprise
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : join-eby.com

![2019-10-21_09-37-48 (2)](https://user-images.githubusercontent.com/1896958/67210065-7441ae80-f3e6-11e9-8d15-9ab21cc84d09.png)

**Comment by tarishah** [comment]
Thanks for reaching out. We will get this looked in next couple weeks.

**Comment by RayAnaya** [comment]
Hi @ragboy,

My apologies for the delay here, but we wanted to make sure we had the right fix for your issue.  At this time, we have both a simple set of instructions for you to follow, **and** we will be making some performance adjustments in our next plugin version as Tarini mentioned above.

**To immediately and completely disable the plugin, perform these commands from your Magento installation:** 

```
php bin/magento module:disable Amazon_Core Amazon_Login Amazon_Payment
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

This will disable all of Amazon Pay's  Plugins and Observers, including the ones generating those queries.

As for a proper resolution and patch, we will be making adjustments to disable those observers and background tasks automatically in our next release.

Thank you for bringing this to our attention!
