### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SaadSohailK** [amzn/amazon-payments-magento-2-plugin#57]
I've a pre-built Magento 2.1.5 website, now I want to install this extension on it, but don't know how?

Documentation says TBC. Would you please help?

**Comment by juhanix** [comment]
## Conditions ##
1. have access to your server via ssh
2. have write permissions for magento-root
3. have composer installed

## TODO ##
1. log in to server via ssh
2. cd /your/path/to/magento-installation/
3. update composer.json: `composer config repositories.amazon_pay vcs git@github.com:amzn/amazon-payments-magento-2-plugin.git`
4. install extension/module via composer: `composer require amzn/amazon-payments-magento-2-plugin:dev-master`
5. enable extension/module: `php bin/magento module:enable Amazon_Core Amazon_Login Amazon_Payment`
6. installing database changes from module: `php bin/magento setup:upgrade`
7. deploy static content: `php bin/magento setup:static-content:deploy` or `php bin/magento setup:static-content:deploy xx_XX` where xx_XX is your locale
8. check permissions on directories and files and set them correctly if needed

**Comment by SaadSohailK** [comment]
Thanks. I've followed your instructions but got the following error:

Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friends                                      ofphp/php-cs-fixer instead.
Package amzn/login-and-pay-with-amazon-sdk-php is abandoned, you should avoid us                                      ing it. Use amzn/amazon-pay-sdk-php instead.

**Comment by danielneu** [comment]
Hi,

simply exchange the two modules in your composer.json file with the ones composer suggests.
e.g. replace "amzn/login-and-pay-with-amazon-sdk-php" with "amzn/amazon-pay-sdk-php"

Best wishes 
Daniel

**Comment by SaadSohailK** [comment]
In composer.json, I've replaced 'fabpot/php-cs-fixer' with 'friendsofphp/php-cs-fixer', but I haven't found 'amzn/login-and-pay-with-amazon-sdk-php' there.

Then I again started the process, but still facing the same error. Do I missing something?

**Comment by danielneu** [comment]
My bad I read the message a bit too fast.
The SDK is something this module loads as a requirement and nothing you add to your composer file.

We are going to adjust this in the near future.

Please ignore this _warning_ till then, the functionality will not be affected.

Best wishes 
Daniel
