### ISSUE TITLE
Minicart show multiple button

### ISSUE THREAD

**Issue by sebashottesimplyphp** [amzn/amazon-payments-magento-2-plugin#584]
To have a simple amazon pay button in the mini cart.

We are seeing more than one button, some time it's 2 and other time 3.

The step:
Add any item to the cart.
Click on the mini cart and you will see more than one button.

* Magento version: 2.2.7
* Amazon Pay Extension Version: 2.1.2
* Magento Edition: Community
* Shop URL : https://www.furnitureconnexion.com/

**Comment by tarishah** [comment]
@sebashottesimplyphp Thanks for reaching out. This seems to be a theme issue on your end. While inspecting the PDP (Product Details Page), I am seeing two instances of the amazon pay button - amazon-button-container__cell. Also, the cart is shown on this page, twice. Once at the bottom of the page and another in the mini cart. Check the attached image. 
![Screen Shot 2019-11-25 at 8 36 42 AM](https://user-images.githubusercontent.com/19417845/69559917-b3bc6700-0f5f-11ea-8d29-6058952914a3.png)

**Comment by christianzichichi** [comment]
Hi @sebashottesimplyphp ,

As we noticed no further input from you I am going to have to go ahead and close this issue for now. If you need further support please provide any details to payments-cp-devel@amazon.com, we would be glad to help you troubleshoot further. 

Thanks
Regards

Christian
