### ISSUE TITLE
Checkout from Minicart and from Productpage fails [Multistore]

### ISSUE THREAD

**Issue by achtdreizehn** [amzn/amazon-payments-magento-2-plugin#588]
We extended our Shop to multiple Languages. Since then the Amazon Pay Button does not work anymore from the Minicart and from the Product page. In the Checkout Process the AmazonPayButton from "/checkout/" and "checkout/cart" works fine. Works fine = Popup opens, Login with Amazoncredentials and complete the order. 

On the "/checkout/" and "checkout/cart"-pages the minicart Pay button also works, on other pages (like product pages) not.

I think it must be a problem with the languages. When hitting the Paybutton on pages (exept the checkout pages) this appears (notice: laguage is empty):

>  Entschuldigung
Die gewählte Zahlungsweise ist für diesen Einkauf nicht verfügbar. Wählen Sie eine andere Zahlungsweise.
400
redirect_uri=https://xxxxxx.eu/amazon/login/processAuthHash/
language=
ui_locales=de_DE
requested_scopes=["profile", "payments:widget", "payments:shipping_address", "payments:billing_address"]
coe=DE
ledger_currency=EUR
env=LIVE
client_id=amzn1.application-oa2-client.206XXXXXXXXXXXX7f92c1e3c101664
state=XXXXXXXXXXXX+XXXXXXXXXXXX+XXXXXXXXXXXX+KBMr616+s=
marketplace_id=XXXXXXXXXXXX
merchant_id=XXXXXXXXXXXX
ia_ui_weblab=T2
is_itp_request=true
merchant_origin_url=https://xxxxx.eu/xxxxxx.html
![grafik](https://user-images.githubusercontent.com/38767971/70980262-48276e80-20b3-11ea-87b2-3af38af8dd37.png)

Errorlog paywithamazon.log:
![grafik](https://user-images.githubusercontent.com/38767971/70980419-92105480-20b3-11ea-914e-472d300700e8.png)

Backend Settings:
![grafik](https://user-images.githubusercontent.com/38767971/70980493-b4a26d80-20b3-11ea-93ae-8738b905b6b9.png)

#### Your setup

* Magento version: 2.2.2
* Amazon Pay Extension Version: 1.2.6
* Magento Edition: Community 
* PHP 7.1

**Comment by christianzichichi** [comment]
Hi @achtdreizehn, thanks for reporting this issue.
Can you please verify that all Allowed JavaScript Origins and Allowed Return URLs in Magento 2 configuration have been put into Seller Central "Login With Amazon" client application configuration?

instructions here: https://developer.amazon.com/it/docs/eu/amazon-pay-onetime/javascript-origins-and-allowed-urls.html#setting-allowed-javascript-origins-or-allowed-return-urls
and here: https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#allowed-javascript-origins-allowed-return-urls-ipn-url

Thanks,
Kind Regards

Christian

**Comment by achtdreizehn** [comment]
Thanks - This fixed the Error.
