### ISSUE TITLE
Pay with Amazon in product-page/cart/minicart forces registered customers to Magento login (not possible to guest checkout, not possible to Login with Amazon)

### ISSUE THREAD

**Issue by romeof1980** [amzn/amazon-payments-magento-2-plugin#591]
#### What I expected
Been able to do a GUEST checkout through AmazonPay in Product page or in cart/minicart even if customer is already registered in the website or, if guest checkout not allowed by module, being able to choose "Login with Amazon".

#### What happened instead
Hitting "Pay with Amazon" on product page or cart/minicart behaves like "Login with Magento" and do not even trigger "Login with Amazon" even if the last is enabled and tested (in the environment the Login with Amazon at customer/account/login works just fine).

#### Prerequisites
Having a valid Amazon account
Register an account to the vendor website then logout and clear browser cache
Having tested Login with Amazon works in customer/account/login and Pay with Amazon works fine on checkout

#### Steps to reproduce the issue
Add product to cart and hit "Pay with Amazon" in cart or minicart
or
Hit "Pay with Amazon" on product page

#### Your setup
* Magento version: 2.3.3
* Amazon Pay Extension Version: 3.2.13
* Magento Edition: Community
* Shop URL : www.giustoacquisto.com

Amazon docs on https://developer.amazon.com/docs/amazon-pay-onetime/button-widgets.html says the following:
**Guest checkout** - **The Amazon Pay button can be used to let a buyer complete a purchase without sharing any personally identifiable information with you before completing a transaction**. When a buyer signs in to access their shipping and payment information, you receive only the buyer's city, country, and postal code for calculating tax and shipping. The buyer doesn't see a consent screen when they sign in using Amazon Pay as a guest. After the buyer completes the checkout process, you receive only their name, email address, and shipping address. 

I do not see how to give a registered customer the possibility to checkout as guest: AmazonPay will always redirect to Magento customer login page if customner is already registered.

_The problem is that with working Amazon Login (tested)  the customer is forced to login with the vendor's magento's account and can't login with Amazon Login if hitting Amazon Pay._

thanks,
romeo

**Comment by RayAnaya** [comment]
Hi Romeo,

I'd like to take a look into this and understand your Magento store setup, as well as what you're trying to do.  From the description of your issue, it's not quite clear to me if this is an issue or not.

Could you please email us at: payments-cp-devel@amazon.com so we can work on getting access to your Magento instance?

**Comment by christianzichichi** [comment]
Closing this as the issue was solved in a newer release.

Christian
