### ISSUE TITLE
Fallback to JQueryUI Compat notification in console for M2.3.3 and later

### ISSUE THREAD

**Issue by n2diving-dgx** [amzn/amazon-payments-magento-2-plugin#614]
jQuery UI library was restructured in Magento 2.3.3. jQuery UI was split in separate widgets that can be loaded by core modules only when they are necessary. It was made to improve the performance of store features.  

The amazon button module has the jquery/ui dependency that needs to be replaced with a callout for the specific module needed rather than load the whole library. 

Otherwise, in the browser console will see a notification "Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will dramatically improve the performance of your site. Message from compat.js"

This issue was discovered to be the explanation for the lag in the display of the Amazon Pay checkout button in our M2.3.4 shopping cart, and was also slowing the cart page performance in general.

  A one line change....

```

diff --git a/vendor/amzn/amazon-pay-module/view/frontend/web/js/amazon-button.js b/vendor/amzn/amazon-pay-module/view/frontend/web/js/amazon-button.js
index f47e466..0a358dc 100644
--- a/vendor/amzn/amazon-pay-module/view/frontend/web/js/amazon-button.js
+++ b/vendor/amzn/amazon-pay-module/view/frontend/web/js/amazon-button.js
@@ -21,7 +21,7 @@ define([
     'Magento_Checkout/js/model/full-screen-loader',
     'modernizr/modernizr',
     'amazonCore',
-    'jquery/ui',
+    'jquery-ui-modules/widget',
     'uiRegistry',
     'mage/cookies'
 ], function ($, customerData, sectionConfig, amazonPaymentConfig, amazonCsrf, fullScreenLoader) {

```

**Comment by christianzichichi** [comment]
Hi @n2diving-dgx , thanks for contacting us! I'm happy to tell you that we fixed that error in version 3.4.0 of our module, that will be shipped in-core in the next Magento 2 releases. 
In order to apply the changes to older versions or to the current Magento 2 version, please follow one of these upgrade instructions: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/PATCH_INSTRUCTIONS.MD

Thanks
Regards

Christian
