### ISSUE TITLE
Magento 2.3.4 Amazon Login/payment not possible for downloadable products.

### ISSUE THREAD

**Issue by romeof1980** [amzn/amazon-payments-magento-2-plugin#616]
#### Your setup
Magento 2.3.4
Magento Edition: Community
Theme: Luma (no customization)
Additional modules: none
Shop URL : https://lezioni.armonia.yoga
php 7.2 with apache 2
amzn/amazon-pay-and-login-with-amazon-core-module 3.3.1
JavaScript Console: [2020-03-24 07:59:03] [ERROR] Failed to load the "Amazon_Login/js/view/login-button-wrapper" component.
ConsoleOutputHandler.show @ console-output-handler.js:34

#### Step to reproduce
- activate Login with Amazon and Amazon Pay and set up as per devdocs
- add a downloadable product in magenot 2 (that disables the guest checkout)
- make sure Amazon login is enabled in the desired store view otherwise Amazon pay won't work because of magento 2 guest checkout automatically disabled for downloadable products

- try to login with amazon or pay with amazon with an email not present in the list of magento's customers

#### What I expected
being able to login with amazon
being able to pay with amazon

#### What happened instead
always getting the message that a customer with such a mail already exist (no matter what mail is used)
no difference between login with amazon and pay with amazon. same message given

**Comment by tarishah** [comment]
Hi @romeof1980 Thanks for raising this. 

For further troubleshooting, can you please share amazon pay logs and shop admin access (assuming https://lezioni.armonia.yoga is a test shop) at payments-cp-devel@amazon.com? 

Regards,
Tarini

**Comment by romeof1980** [comment]
thanks @tarishah 

module's logs:
[paywithamazon.log](https://github.com/amzn/amazon-payments-magento-2-plugin/files/4376925/paywithamazon.log)

m2 mode set == developer
lezioni.armonia.yoga/admin_mb6454
user: amazon
p: demosys90
amazon pay = sandbox

frontend (where a product can be added to cart) : https://lezioni.armonia.yoga/lezioni-yoga.html
customer login page: https://lezioni.armonia.yoga/customer/account/login/

it's a test environment, feel free to test and set settings as you like

**Comment by romeof1980** [comment]
adding debug log too:
cat var/log/debug.log  | grep "amazon/login/authorize"
[debug.log](https://github.com/amzn/amazon-payments-magento-2-plugin/files/4376997/debug.log)

**Comment by romeof1980** [comment]
hi @tarishah ,
thanks for answering. May I know if you aknowledge the bug and if the amazon team aims to work on the issue. I can provide more info if I'm requested to.
thanks

**Comment by tarishah** [comment]
@romeof1980 Let me circle back by tomorrow. Apologies for the delay.

**Comment by romeof1980** [comment]
@tarishah no problem, thanks a lot for answering. If you want me to check logs again or to put breakpoints somewhere for checking possible bugs, let me know what I can do. many thanks

**Comment by tarishah** [comment]
@romeof1980 thanks for your patience and apologies for my delayed response.
At the moment, Amazon Pay is not supported for digital products. 

However, we are launching a new Amazon Pay checkout where there's support for digital products. If you are interested in being a beta merchant to try this new checkout and avail the digital feature, please let email us at payments-cp-devel@amazon.com. We can take you through the plugin installation and testing. 

Thanks,
Tarini
