### ISSUE TITLE
Shipping methods are not rendered after amazon payment process on Checkout magento 2

### ISSUE THREAD

**Issue by aadithyadckap** [amzn/amazon-payments-magento-2-plugin#620]
#### What I expected

successful checkout using amazon pay

#### What happened instead

shipping methods are not calculated after amazon payment process

#### Steps to reproduce the issue

1.Add some items to cart
2.Go to checkout
3.Login with amazon pay

#### Your setup

* Magento version: 2.3.3
* Amazon Pay Extension Version: 3.2.13
* Magento Edition: magento cloud

#### Note
I got this error in exception log
"Amazon Pay could not process your request. Please try again. {"exception":"[object] (Amazon\\Core\\Exception\\AmazonServiceUnavailableException(code: 0): Amazon Pay could not process your request. Please try again. at /app/ypz7jqthmlviw_stg2/vendor/amzn/amazon-pay-module/Model/AddressManagement.php:224)"}

![image](https://user-images.githubusercontent.com/50445925/78037879-be618f80-7389-11ea-905c-6a4c22bfd2cc.png)

**Comment by tarishah** [comment]
@aadithyadckap Thanks for reaching out. 
This seems to be an Amazon Pay credentials issue. To resolve it, you will need to copy the keys from Amazon Pay SellerCentral to the M2 Amazon Pay settings, via Credentails -> Credentails JSON field. Reference [documentation](https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#credentials-json) on this process.

Let me know how this goes.

Regards,
Amazon Pay Support

**Comment by aadithyadckap** [comment]
@tarishah 
I'm not able to place my JSON credential( MWS access key that is copied from amazon seller account) in a credential JSON field.
When I try to enter the credentials, It's always showing the empty text area with a place holder(Invalid JSON credentials entered, please try again.)

**Comment by tarishah** [comment]
@aadithyadckap that's weird. Possible to copy paste all the keys manually from seller central? 
Also, if you can give me access to the demo admin, I can try out the credentials JSON field, to see what's going on.

**Comment by aadithyadckap** [comment]
I manually entered all keys in their corresponding fields(Merchant Id, Access Key Id, Secret Access Key, Client Id, Client Secret). configuration is done successfully.

I have tried to enter the JSON credentials in both ( normal Magento 2.3.4 instance and our Magento admin panel)

You can try this in a normal Magento instance.

**Comment by tarishah** [comment]
Closing this ticket, as I am working with the merchant developer over email.
