### ISSUE TITLE
No Payment Methods - When discount drops the cart/order total to $0.00

### ISSUE THREAD

**Issue by cosmointeractive** [amzn/amazon-payments-magento-2-plugin#64]
If a coupon or store credit is applied to the cart/order after signing in to Amazon Pay, the **Place Order** button disappears and an error "No Payment Methods" is displayed. Which stops the customer from completing their purchase. 

Yes, **Zero Subtotal Checkout** has been configured per [this](http://docs.magento.com/m2/ce/user_guide/payment/zero-subtotal-checkout.html) guide.

#### What I expected

To be able to place an order after signing into Amazon Pay and after a credit is applied to the cart that causes the balance to drop to $0.00. 

#### What happened instead

The **Place Order** button disappears and an error "No Payment Methods" is displayed. 

![image](https://cloud.githubusercontent.com/assets/7852494/26415768/9dea7020-4081-11e7-8d5d-2ab03eb9284e.png)

![image](https://cloud.githubusercontent.com/assets/7852494/26415606/1c496c10-4081-11e7-960d-bdf78c0c9f80.png)

#### Steps to reproduce the issue

Add items to your shopping cart, login to store using Magento account, continue to checkout using Amazon pay, apply discount that reduces cart to $0.00.

#### Your setup

* Magento version: 2.1.5
* Magento Edition: Community
* JavaScript Console: No errors

**Comment by cosmointeractive** [comment]
It appears that this is a duplicate of issue #42

**Comment by danielneu** [comment]
@cosmointeractive Yes, this was handled in #42 and will be part of the upcoming release.

Best wishes 
Daniel
