### ISSUE TITLE
Payments not collected, I have to collect by hand in Sellercentral

### ISSUE THREAD

**Issue by elfeffe** [amzn/amazon-payments-magento-2-plugin#645]
#### What I expected
I wanted the order to mark as paid, as usual

#### What happened instead
They are still a quote, not converting to an order. And I have to "collect the payment" in SellerCentral, and if I do that it seems that I get the payment, but the order doesn't update in Magento, it is still a quote.

I also have a log that says

> amazonClientLogger.ERROR: Amazon\Core\Exception\AmazonWebapiException: Transaction has been declined. Please try again later. in /home/web/web.com/vendor/amzn/amazon-pay-module/Gateway/Command/AmazonAuthCommand.php:205

This is referring to the quote that I'm speaking about, the same quote id and date. It's like if the card was declined, but then I finally have collected the payment by hand, the problem is that the order is still not showing in Magento, it's still a quote.

#### Your setup

* Magento version: 2.4.4
* Amazon Pay Extension Version: 3.4.2
* Magento Edition: Community

Is there any way to convert the quote into an order with some command when this kind of thing happen?

**Comment by tarishah** [comment]
Hi @elfeffe, Thanks for reaching out.

To understand better, can you share the orderId that this happened with? Please send us an email at payments-cp-devel@amazon.com with this info. Thank you!

**Comment by elfeffe** [comment]
done

**Comment by elfeffe** [comment]
My customer says that after the payment, he was not redirected to the order confirmation

**Comment by elfeffe** [comment]
To tell you the truth, the plugin geva us a lot of problems, we we have decided to remove it for now.

**Comment by christianzichichi** [comment]
Hi @elfeffe ,
thanks for your feedback. We would like to understand what were the issues and support you in every way we can. Feel free to connect with us again at payments-cp-devel@amazon.com should you decide to re-enable it. 

Thanks,
Regards

Christian
