### ISSUE TITLE
Amazon Pay not shown in the payment methods

### ISSUE THREAD

**Issue by Konni1234** [amzn/amazon-payments-magento-2-plugin#649]
#### What I expected

Amazon Pay not shown in the payment methods

#### What happened instead

only the other selected methos shown

#### Steps to reproduce the issue

installed a plain magento, updated amazon pay module to 3.4.3 

#### Your setup

* Magento version: 2.3.4
* Amazon Pay Extension Version: 3.4.3
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : https://shop.elko-tours.de/magento2

**Comment by christianzichichi** [comment]
HI @Konni1234 ,
thanks for contacting us. Can you make sure "Advanced->Frontend->Show Amazon Payment method" option in the plugin configuration is disabled?

https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#show-amazon-pay-method

thanks
regards

Christian

**Comment by Konni1234** [comment]
Hello, it's enabled.

https://www.bilder-upload.eu/bild-b0bbb0-1587747671.png.html

**Comment by christianzichichi** [comment]
Hi @Konni1234 ,
https://shop.elko-tours.de/magento2/ returns error 404 at the moment. Would you please contact us at payments-cp-devel@amazon.com providing a screenshot or recording where the issue is shown in the testing environment? 

Thanks
Regards

Christian

**Comment by christianzichichi** [comment]
Hi @Konni1234 ,
unfortunately our in-core plugin does not support with virtual products. 
We recommend installing the new version of our plugin, which supports both physical and virtual products, following the instructions in the README here:

https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x 

Thanks
Regards

Christian
