### ISSUE TITLE
PHP 7.3?

### ISSUE THREAD

**Issue by elfeffe** [amzn/amazon-payments-magento-2-plugin#664]
Is it really required? Why not 7.1?
composer complains because some extensions just support 7.1, so I can't upgrade to Amazon Pay 4.0

**Comment by christianzichichi** [comment]
Hi @elfeffe,

Amazon Pay 4.0.0 will be delivered within Magento 2.4.0, in which PHP version requirements are different than Magento 2.3.x and which has not yet been released. Please a take a look at the following compatibility table https://github.com/amzn/amazon-payments-magento-2-plugin#branch-information
the latest available version for Magento 2.3.x at the moment is 3.5.1, which you can find in 3.4.x branch https://github.com/amzn/amazon-payments-magento-2-plugin/tree/3.4.x

Thanks
Regards

Christian
