### ISSUE TITLE
Class 'PayWithAmazon\Client' not found

### ISSUE THREAD

**Issue by magecomp** [amzn/amazon-payments-magento-2-plugin#67]
#### What I expected
I was hoping simple plug n play extension

#### What happened instead
Class 'PayWithAmazon\Client' not found in app/code/Amazon/Core/Client/Client.php on line 20

When  we try to save payment methods, it shows this above error . Although data is saving in database.

#### Steps to reproduce the issue
After installing, saving the payment gateway showing above error.

#### Your setup

* Magento version: 2.1.6
* Magento Edition: Community 
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by danielneu** [comment]
Hi,

thanks for getting in touch.
How exactly did you install the extension? The missing calls is part of our SDK and not of this extension.
The SDK is added as a dependency and will be installed automatically, if you follow the official [installation instructions](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#installation-process).

If you installed the module differently (e.g. simply extracting it to the Magento installation), please do so for all the dependencies as well.

Best wishes 
Daniel

**Comment by magecomp** [comment]
Hey that worked :)

**Comment by danielneu** [comment]
Glad I could help, closing.
