### ISSUE TITLE
[2.3.5-p1 bug]Amazon Pay -  Guest Checkout - Wrong Authorization Status

### ISSUE THREAD

**Issue by wilhelmpa** [amzn/amazon-payments-magento-2-plugin#685]
Hi There, 

after a fresh reinstall of fresh Magento 2.5.1-p1 there occurs the following error, with Luma Theme, and all other Custom Themes as well:

Once You Click the Button PayWithAmazon In the Cart, Login and then you will be redirected to the Checkout Shipping Step. So far so good. But if you click on the "next" button to go to the payment page (with the amazon payment iframe) the order seems to be already transferred to amazon.

The System.log throws:
main.WARNING: Could not modify Amazon order details for xxx: OrderReference xxx is not in draft state and cannot be modified with the request submitted by you. [] []

Furthermore you can't change the delivery Adress in this case, because the is an error message in the frontend that says you can't modify an Order with Status Open.

Furthermore the customer receives and E-Mail about upcoming Payment, but the Purchase was not made yet.

The Amazon Backend also shows the transactions ready to capture, but without an Magneto Order Number.

System Details
Magento 2.5.1-p1
PHP 7.2
Nginx 10
Redis 6
Varnish 5

The Same Machine with Magento 2.3.4 has no such Problem.

Best Regards

Patrick

**Comment by tarishah** [comment]
Hello @wilhelmpa, Thanks for reaching out.

We are aware of this bug and are working with Magento team to release a fix asap. 
I will provide an update here, by EOD.

Regards,
Amazon Pay Support

**Comment by wilhelmpa** [comment]
Thanks four your quick reply. Really appreciate your work :-)

**Comment by tarishah** [comment]
@wilhelmpa Thanks for your patience. 
To resolve this issue and remove the error, we have created a [patch](https://support.magento.com/hc/en-us/article_attachments/360056411111/BUNDLE-2554_EE_2.3.5-p1.composer.patch). See [How to apply a composer patch](https://support.magento.com/hc/en-us/articles/360028367731) provided by Magento.

Please let us know if this fixes the issue and if there are any other concerns. 

Thank you.
Amazon Pay Support

**Comment by wilhelmpa** [comment]
Hi tarishah,

I can confirm the patch fixed it. Amazon Pay is working as expected.

Thank you very much.



P.S. There is another Bug within the checkout, but since this bug also appears with the Klarna checkout, and the checkout in general, this should not be something with this extension but with magento 2.3.5-p1 itsself. But just to mention it in case it has something to do with it:

https://domain.com/rest/default/V1/carts/mine/set-payment-information returns a 400 because the payment method is not set (error via console).  This error is also true for guests via the guest api request. However it does not affect the payment process with amazon pay. With klarna for instance it is not possible to redeem a coupon, because the loading gauge wont disappear.

**Comment by onicholas87** [comment]
Where is the patch for the fix for this please?

**Comment by christianzichichi** [comment]
Hi @onicholas87,
patch link: https://support.magento.com/hc/en-us/article_attachments/360056411111/BUNDLE-2554_EE_2.3.5-p1.composer.patch
how to apply composer patches: https://support.magento.com/hc/en-us/articles/360028367731

Thanks
Regards

Christian

**Comment by RayAnaya** [comment]
Hello all,

I'm closing this ticket as we have a known resolution and patch for this problem.  Please re-open the issue, or file a new one if you encounter any further issues with 2.3.5-p1.

Thanks!
