### ISSUE TITLE
[2.3.5-p1 bug]Amazon Pay - Guest Checkout - InvalidParameterValue

### ISSUE THREAD

**Issue by wilhelmpa** [amzn/amazon-payments-magento-2-plugin#693]
Hi There,

there seems to be a but with amazon pay and coupons on Magento 2.3.5-p1 with applied patch! 

Please the the error log. I can't reproduce it on Test Environment but on Live it gives:

[2020-05-08 11:58:08] amazonClientLogger.DEBUG: <ErrorResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>The Value '' is invalid for the Parameter 'OrderTotal'</Message>
  </Error>
  <RequestId>xxxxxxxx</RequestId>
</ErrorResponse>
 [] []
[2020-05-08 12:08:35] amazonClientLogger.DEBUG: POST
mws-eu.amazonservices.com
/OffAmazonPayments/2013-01-01
AWSAccessKeyId=yyyyyyyyy&Action=SetOrderAttributes&AmazonOrderReferenceId=xxxxxxx&OrderAttributes.SellerOrderAttributes.SellerOrderId=xxxxxx&SellerId=xxxx&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-05-08T12%3A08%3A35.000Z&Version=2013-01-01 [] []
[2020-05-08 12:08:35] amazonClientLogger.DEBUG: amazon-pay-sdk-php/3.6.0 (PHP/7.2.24-0ubuntu0.18.04.4; Linux/x86_64/5.3.0-1017-aws) [] []
[2020-05-08 12:08:35] amazonClientLogger.DEBUG: <ErrorResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
  </Error>
  <RequestId>xxxxxxxxxxxxxxxxxxxxxxxx</RequestId>
</ErrorResponse>

**Comment by tarishah** [comment]
@wilhelmpa can you please provide the website url at which this is happening?
Also, as you said, this is not the case in test environment, are there any differences between the live and test instances, that you can share?

**Comment by wilhelmpa** [comment]
Hi tarishah,

it is happening on this site: https://www.beautymates.de

Test and Live Environment are the same. It happens randomly. Unfortunately I can't reproduce. But   maybe it has something to do with https://github.com/magento/magento2/issues/28161 which I opened before. It seems that the calculation of the coupon / discount maybe is not 100% reliable. I keep you updated once I have some more clues :-)

**Comment by RayAnaya** [comment]
Closing this issue as there was a known problem and fix (please see the Magento 2.3.5-p1 patch) with this version of Magento and Amazon Pay.

Please feel free to re-open this issue, or submit a new one if you encounter any further problems.

Thanks!
