### ISSUE TITLE
Wrong placeholder

### ISSUE THREAD

**Issue by kerlama** [amzn/amazon-payments-magento-2-plugin#694]
#### What I expected

Placeholder for password field should say: Password instead of optional

#### What happened instead

"optional" placeholder shown instead

#### Steps to reproduce the issue

For some reason, when amazon payment is enabled but not configured it replaces email.html form element on the magento checkout and you ll see placeholder says optional for password instead "Password". This was fixed in magento here:

https://github.com/magento/magento2/issues/16378

#### Your setup

* Magento version: 2.3.5
* Amazon Pay Extension Version: 3.4.1
* Magento Edition: Community

**Comment by tarishah** [comment]
Thanks @kerlama for reporting. We will get this looked at and resolved.

**Comment by christianzichichi** [comment]
Hi @kerlama ,
I'm happy to tell you that a fix for this issue has just been merged into the plugin ( https://github.com/amzn/amazon-payments-magento-2-plugin/pull/741#pullrequestreview-428706126 ) and will be shipped in the next Magento releases. Thanks for your contribution.

Thanks
Regards

Christian
