### ISSUE TITLE
Checkout hangs from time to time (loading indicator)

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#7]
A spinner at the top of the page does not disappear and blocks the whole checkout.

**Comment by EmilyPepperman** [comment]
We had this issue early on... and it was solved. I can try to dig up what the fix was.

**Comment by danielneu** [comment]
Thanks @EmilyPepperman 

would be appreciated

**Comment by danielneu** [comment]
@EmilyPepperman 
Wa sit this one? https://github.com/amzn/amazon-payments-magento-2-plugin/commit/2ac7059343b0faa7d11fe9a93e7397ec4cdcb9fd

**Comment by danielneu** [comment]
Another merchant affected

**Comment by danielneu** [comment]
Haven't seen this in the last versions with current Magento 2.1 installations, resolving for now
