### ISSUE TITLE
Amazon Pay payment method not showing on frontend

### ISSUE THREAD

**Issue by gbyte-dev** [amzn/amazon-payments-magento-2-plugin#729]
#### What I expected
I have my magento site on magento 2.3.3 version, I setup amazon pay
Filled up all the credentials
![image](https://user-images.githubusercontent.com/66471234/83867810-a28eb700-a747-11ea-84d6-42327da3513b.png)
 
My settings as well to show every where the amazon logo for the payment
![image](https://user-images.githubusercontent.com/66471234/83867886-c18d4900-a747-11ea-932c-8b971aec8bc8.png)

#### What happened instead
Nothing showing on the frontend
![image](https://user-images.githubusercontent.com/66471234/83868036-d9fd6380-a747-11ea-9d4b-f558e6b51e96.png)

#### Steps to reproduce the issue
payment method not showing, I read the issues available in this repo but nothing answered my problem

#### Your setup

* Magento version: 2.3.3
* Amazon Pay Extension Version: 3.4.1
* Magento Edition: Community 
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by christianzichichi** [comment]
Hi @gbyte-dev ,
Thanks for reaching out. Would you please check if "Payment Region" parameter in the plugin matches Magento "Base Currency" (e.g. Euro Payment Region and Euro Base Currency) ? Are there any errors showing in console when in cart page?

Thanks
Regards

Christian

**Comment by gbyte-dev** [comment]
Hi @christianzichichi ,
yes the base currency and store currency is same Euro and payment region is also the Euro.
![image](https://user-images.githubusercontent.com/66471234/83894977-aafae800-a76f-11ea-822b-0ef6dab0e408.png)

Please check there is no error coming on the console
![image](https://user-images.githubusercontent.com/66471234/83895075-d382e200-a76f-11ea-8aa8-6937d3640899.png)

Please check here in console I can find on the shipment page there amazon login button is coming but it is not showing css set display:none when manuall do display block then showing

**Comment by gbyte-dev** [comment]
Any update?

**Comment by christianzichichi** [comment]
Hi @gbyte-dev, 
from the screenshots provided I can see the button is showing at the shipping step but not in the cart. would you please contact us at payments-cp-devel@amazon.com? We would need some more information to continue the investigation on the issue you are having on your installation. In the meantime, would you please update the plugin to the latest available version with these instructions https://gist.github.com/christianzichichi/bc44b914badac1f53b6005a262298ee8 ? 

thanks
regards
Christian

**Comment by RayAnaya** [comment]
@gbyte-dev Just wanted to check in on this issue and see if it was resolved or not?  Looking back, it seems like the issue was related to configuration-options, but I just wanted to make sure!

Thank you!

**Comment by Puru2016** [comment]
I am using magento ver 2.3.5-p2 and I am still facing the same issue. 
Is there any solution or update on this.

**Comment by RayAnaya** [comment]
@Puru2016 Could you please send us an email directly, at payments-cp-devel@amazon.com so I can get some more specific information regarding your Amazon Pay integration?

**Comment by Puru2016** [comment]
@RayAnaya I already shared the details on payments-cp-devel@amazon.com on Aug 10, 2020, 1:42 PM, but still no reply from your side,I also send you reminder but still no reply, Please reply on this issue ASAP.

**Comment by yeetenderyeeter** [comment]
I also have the same Issue. (The address Widget and Payment Widget in the Checkout not showing) 
Magento Version: 2.3.5
Amazon Pay Extension Version: 3.6.2

**Comment by christianzichichi** [comment]
Hi @yeetenderyeeter  and @gbyte-dev,

I apologize for the delay here. Would you please update to latest release (3.7.1) with the following patch instructions? https://github.com/amzn/amazon-payments-magento-2-plugin/blob/3.0.x/PATCH_INSTRUCTIONS.MD 

We have recently delivered bugfixes to currency management in multi-store-views scenarios. If that doesn't solve the issue, we would need more information regarding the environment (template, 3rd party plugin) and we invite you to contact us again on payments-cp-devel@amazon.com

thanks
Best

Christian
