### ISSUE TITLE
[Feature request] Add Amazon Pay as a payment option to the payment step

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#75]
Requested e.g. in #73

**Comment by andidhouse** [comment]
Hi Daniel,

Amazon Pay works fine on one of our shops now. But the problem really is that we have other shops running for example the aheadworks checkout which is not compatible with the iframe loading at all so here a solution (for all one step checkouts and not native magento checkouts) to integrate amazon pay "as a normal payment" in the payment section would be great - so these shop can also use amazon pay as a pure payment option.

**Comment by andidhouse** [comment]
Is there an update to this one? 

We will change to aheadworks checkout on about 4 systems and this requires that amazon pay is displayed as a normal payment method.

I think this one is important as most onestepcheckouts or 3step checkouts do not support amazon pay like it is at the moment.

Thanks!

**Comment by szubariev** [comment]
Hi @danielneu,  is there any updates on this request?

I understood what you mean under 'checkout solution', but the way it is implemented now is confusing for buyers, they doesn't clearly understand what will happen so just ignoring "Amazon Pay" button completely.
Adding option to use it just like any other payment option will be definitely step in right direction.

**Comment by danielneu** [comment]
Hi @szubariev 

thanks a lot for the feedback. We will take this into account in our discussions.
However, for now, there is no update on this topic.

Best wishes 
Daniel

**Comment by islandskater43** [comment]
We should also have an admin setting that drives this behavior. Defaulting to on.

**Comment by gbear** [comment]
M1 extension's admin setting label & help text:

![screen shot 2018-01-29 at 3 45 54 pm](https://user-images.githubusercontent.com/11601/35541150-324c98fa-050e-11e8-8141-c53c5daf40ff.png)

**Comment by islandskater43** [comment]
Let's add the "Display as Payment Option" field under **Advanced** > **Frontend**, defaulting to Yes.

**Comment by craigcarnell** [comment]
@danielneu We would also like it to appear as a payment option instead of a random button in the checkout. We are going to remove this button ourselves, so it is up to you if you still want our money! :)

**Comment by prayagr** [comment]
Hi @craigcarnell , the feature to have Amazon Pay as a payment option will be included as part of our extension with the Magento 2.2.6 release. I will also provide an update on this ticket once we cut a release with this feature included.

**Comment by prayagr** [comment]
This feature has been released for 2.2.6. Closing this issue.
