### ISSUE TITLE
SSL Certificate expired 

### ISSUE THREAD

**Issue by stkrelax** [amzn/amazon-payments-magento-2-plugin#776]
Error: Script error for: https://static-eu.payments-amazon.com/OffAmazonPayments/de/lpa/js/Widgets.js?nomin
http://requirejs.org/docs/errors.html#scripterror 53265ff8f03317afd615b35d60149c87.min.js:16:53

#### What I expected

is secure and so Amazon login button appears

#### What happened instead

is not secure since 14:00 GMT amazon login button does not appear

#### Steps to reproduce the issue

call https://static-eu.payments-amazon.com

**Comment by lemked** [comment]
Thanks for reporting @stkrelax . We're investigating the issue and will report back here when it's resolved.

**Comment by stkrelax** [comment]
okay they managed to fix this. closing
