### ISSUE TITLE
Amazon Pay creating Transaction / Order in Amazon Pay before completing order

### ISSUE THREAD

**Issue by live4soccer7** [amzn/amazon-payments-magento-2-plugin#783]
#### What I expected

Transaction in amazon pay is created before order is submitted. So if customer wants to go back and checkout with another method, the transaction is already created in Amazon Pay and the customer gets and email about the transaction/order. This happens once the customer gets to the payment option within the Amazon checkout. 

#### What happened instead

A transaction in Amazon Pay is created before checkout is complete (hitting submit order button) or if the customer backs out after selection payment method and wants to shop more or checkout a different method.

#### Steps to reproduce the issue

Add item to cart
go to amazon pay checkout
sign in using guest or account
select address
select shipping method
select payment method
Either select go back to shipping addresses, choose checkout different way or go back to home page

At this point a transaction is created in Amazon Pay

#### Your setup

* Magento version: 2.3.5-p1
* Amazon Pay Extension Version: 3.6.1
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by christianzichichi** [comment]
Hi @live4soccer7 ,
thanks for contacting us. We will look into the issue and report back.

Thanks
Regards

Christian

**Comment by live4soccer7** [comment]
I just updated to the most recent patches for amazon pay and it appears to be resolved.

**Comment by stkrelax** [comment]
can you list the patches here please ?

**Comment by christianzichichi** [comment]
Thanks for the feedback @live4soccer7. I'm going to close this issue. Please re-open it should you encounter the same issue

Thanks
Regards

Christian

**Comment by live4soccer7** [comment]
> Thanks for the feedback @live4soccer7. I'm going to close this issue. Please re-open it should you encounter the same issue
> 
> Thanks
> Regards
> 
> Christian

Thank you very much.
