### ISSUE TITLE
Feature Request : Checkout through for Magento 2 GraphQL

### ISSUE THREAD

**Issue by mandarzope** [amzn/amazon-payments-magento-2-plugin#798]
I am trying to checkout from PWA using GraphQL. 

Can this module include methods to checkout from GraphQL.

getAmazonShippingAddress(input: AmazonAddressInput)
getAmazonBillingAddress(input: AmazonAddressInput)

input AmazonAddressInput {
    cart_id: String!
    amazonOrderReferenceId: String @Doc(description: "amazonOrderReferenceId"),
    addressConsentToken: String @Doc(description: "addressConsentToken")
}

And the on placeOrder mutation it should process as expected.

**Comment by christianzichichi** [comment]
Hi @mandarzope ,
thanks for reaching out. Our current in-core product does not support GraphQL, but our new product, Checkout V2, actually does.
You can install it from here: https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x#installation-steps (supported Magento versions: 2.2.6 up to 2.3.5)
here you can also find exposed endponts required by PWA: https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x#pwa-support

please contact us at payments-cp-devel@amazon.com and we'll help you with the integration

Thanks
Regards

Christian
