### ISSUE TITLE
Base Subtotal Inc Tax not set on Amazon Pay Order records 

### ISSUE THREAD

**Issue by Mkennethsmith** [amzn/amazon-payments-magento-2-plugin#812]
#### What I expected

Placed orders contain the _base_subtotal_incl_tax_ value and can be retrieved via the magento 2 API. 

#### What happened instead

All Amazon pay orders are setting the _base_subtotal_incl_tax_ value to NULL in the database. 

#### Steps to reproduce the issue

Place an order using Amazon Pay. 

#### Your setup

* Magento version: 2.2.10
* Amazon Pay Extension Version: 2.2.18
* Magento Edition: Community
* Shop URL : thehayexpoerts.co.uk

**Comment by bear-ihor** [comment]
Hi @Mkennethsmith,

The Amazon Pay is not responsible for setting the _base_subtotal_incl_tax_ or any other amount value.
Instead, it gets necessary values from Magento entities and performs operations, e.g. [getting grand total to perform authorization](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/3.6.1/src/Payment/Gateway/Request/AuthorizationRequestBuilder.php#L116-L117).

Thank you.
