### ISSUE TITLE
2.3.5-p1 Heavy JS and Jquery loaded even when it may not be necessary

### ISSUE THREAD

**Issue by live4soccer7** [amzn/amazon-payments-magento-2-plugin#816]
#### What I expected

Amazon js and jquery version loaded on every page. This is heavy and inefficient, especially on mobile devices. This is especially not necessary when there are no badges displayed on any pages or the mini cart and only the actually checkout page or shopping cart page itself.

#### What happened instead

I have the minicart badge and product page badge disabled and the module's js is still loading and therefore loading an additional jquery version (3.4.1) as well as magento's jquery version 1.x.x.

#### Steps to reproduce the issue

Load any page with the module configured and you will see this. You can confirm it in browser console or a speed tool like yellowlab

#### Your setup

* Magento version: 2.3.5
* Amazon Pay Extension Version: latest
* Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @live4soccer7 ,
thanks for reaching out and for highlighting this issue. We are tracking it and scoping it. For your information, our new product, Checkout V2, should already mitigate the performance issues caused by unnecessary loading : https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x 

I will report back here once I have an update on the matter.


Thanks
Best

Christian

**Comment by live4soccer7** [comment]
Thank you very much. Will this become the new default amazon pay module bundled with future magento upgrades?

**Comment by RayAnaya** [comment]
Hey @live4soccer7 

Not yet!  We will be looking to include this as the standard plugin (enabled by default) some time early next year.  For now, we are including the code as part of Magento V2.4.0+ but it will need to be manually installed and enabled for the forseeable future.

**Comment by christianzichichi** [comment]
Hi @live4soccer7 ,
our new extension has now been published onto Magento Marketplace and should fix the performance issues highlighted here: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html . New User guide: https://amzn.github.io/amazon-payments-magento-2-plugin/

Feel free to open another issue if you encounter the same issue again.

Thanks
Best

Christian

**Comment by live4soccer7** [comment]
@christianzichichi 

Thank you very much. I presume that the marketplace version will be only supported version after 2.5?

**Comment by christianzichichi** [comment]
hi @live4soccer7 , that's correct. and you can already use the marketplace version in m2.3 and m2.4
