### ISSUE TITLE
Amazon Payment is not working with virtual quote

### ISSUE THREAD

**Issue by Dren7755** [amzn/amazon-payments-magento-2-plugin#828]
#### What I expected

I have created virtual product and added it to the cart as a guest. And I want to pay this order by Amazon payment

#### What happened instead

I can't see Amazon pay payment method on the checkout

It happen because of \Amazon\Payment\Plugin\DisableAmazonPaymentMethod. If I remove this plugin, I can use Amazon payment, but I see following error: 
![image](https://user-images.githubusercontent.com/19759530/89506628-1430c300-d7d4-11ea-8b37-7f4d278e70d0.png)

Is there any way to make amazon pay compatible with virtual quote?
Maybe I can pass billing address instead of shipping to amazon?

#### Your setup

* Magento version: 2.3.3
* Amazon Pay Extension Version: amzn/amazon-pay-module:3.2.13
* Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @Dren7755 ,
our in-core plugin does not support virtual orders. Please install our new plugin (Checkout V2), which supports them, following the instructions in this branch https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x
if you need any help in installing/configuring the plugin, please reach out to payments-cp-devel@amazon.com.

Thanks
Best

Christian

**Comment by Dren7755** [comment]
@christianzichichi , Thanks for your answer!
