### ISSUE TITLE
Amazon Pay not working in Magento2.3.3

### ISSUE THREAD

**Issue by jayanta88** [amzn/amazon-payments-magento-2-plugin#829]
Expected it will work in Magento 2.3.3 as we're running successfully with the same account in Magento1.

In the checkout page after login to amazon account when clicking the place order button. We're getting error in Network Tab. See this [screenshot](https://monosnap.com/file/X9mByqGqod4YRoJksRuzJTeKQvXpF1)

We can login to Amazon and select address and card information. See here https://monosnap.com/file/AzGkclHlFnnsgJshdyjMU6OGFGpFPe
But getting errors in the checkout page and log. Nothing is happening after clicking the Place Order button.

* Magento version: 2.3.3
* Amazon Pay Extension Version: 3.2.13
* Magento Edition: Community
* JavaScript Console: 
https://monosnap.com/file/4ZT2YKa8kEG8qjwirVs27iUyLcsjrR
https://monosnap.com/file/X9mByqGqod4YRoJksRuzJTeKQvXpF1

**Note:** We have not added the IPN url in amazon seller central. Because the same account we're using in Magento1. Don't know if that will impact the Magento1 setup or not.
We have only added the Javascript origins and allowed return urls.

**Comment by christianzichichi** [comment]
Hi @jayanta88 ,
thanks for reaching out. It seems that you're using a third party plugin to achieve one step checkout functionality, which is not supported natively by our plugin. Can you list the extensions you're using that could affect checkout directly?

We suggest you patch your in-core plugin to the latest available version following these instructions: https://gist.github.com/christianzichichi/bc44b914badac1f53b6005a262298ee8

The latest version includes several bugfixes and could potentially solve your issue.
Looking forward to hearing from you

Thanks
Best

Christian

**Comment by jayanta88** [comment]
Hi @christianzichichi -

I just tried to place order with default magento checkout now it worked. So, I confirm the issue is with Onestepcheckout.

Thanks

**Comment by christianzichichi** [comment]
@jayanta88 ,
thanks for confirming. Would be helpful for us knowing one step checkout plugin vendor and module version. we will reach out to them to let them know there is an incompatibility to be solved. 

Best
Christian

**Comment by jayanta88** [comment]
Hi @christianzichichi -

Here are the details. onestepcheckout/iosc:1.2.038

Thanks

**Comment by speedupmate** [comment]
please contact OneStepCheckout  support for the fix.  theres a broken js file in 1.2.038 that misses requirejs dependencies .
