### ISSUE TITLE
CSP for module is not complete

### ISSUE THREAD

**Issue by live4soccer7** [amzn/amazon-payments-magento-2-plugin#841]
There are still components not included in the CSP whitelist. I am utilizing the latest amazon module patch on 2.3.5-p2. I have confirmed the patch is installed by checking the version in amazon payment methods within admin.

'https://d2ldlvi1yef00y.cloudfront.net/us/live/en_us/amazonpay/gold/medium/button_T6.png

https://d2ldlvi1yef00y.cloudfront.net/default/us/live/lwa/gold/medium/LwA.png'

**Comment by christianzichichi** [comment]
Hi @live4soccer7 ,
Thanks for contacting us. CSP whitelisting will be enforced in Magento 2.3.6 and 2.4.1. Magento 2.3.5 does not have that check, that is why you are seeing related console messages even if you have patched our extension to the latest release.

Thanks
Best
Christian
