### ISSUE TITLE
Problems with Amazon Checkout V2(1.5) and Magento 2.3.5-p2

### ISSUE THREAD

**Issue by diybook** [amzn/amazon-payments-magento-2-plugin#855]
#### What I expected
1) Amazon Pay Button should be rendered in the minicart on all pages. Currently the button is only shown in the minicart when we are on the cart and checkout page itself. On other pages the redering fails due to js errors. 

2) Button contantly changes height on desktop browser size. On mobile page layout the size stays fixed. It seems that some sort of js constantly is changing the size of the button.

3) Amazon button on the product page is no intsant purchase button, but only adds the product to the cart. This behaviour may be intended, but than the button it quite useless to my opinion. I would expect an instant puchase like PayPal express checkout.

#### What happened instead
1) The button is not shown on other sites than the cart or checkout page. The following js error occurs:

`checkout.js:1 Uncaught TypeError: Cannot read property 'duration' of undefined
    at _t (checkout.js:1)
    at Object.Ae [as renderButton] (checkout.js:1)
    at amazon-button.js:91
    at $.<computed>.<computed>.<anonymous> (amazon-button.js:36)
    at checkout-session-config-load.js:47
    at $.<computed>.<computed>._loadButtonConfig (amazon-button.js:34)
    at $.<computed>.<computed>._loadButtonConfig (widget.js:100)
    at $.<computed>.<computed>.<anonymous> (amazon-button.js:90)
    at amazon-checkout.js:49
    at Object.execCb (require.js:1650)`

The script gets stuck in this line:
`var a, r = (a = t(performance.getEntries(), gt)) ? a[0].duration : 0;`

2) The button should not change it's size and flicker all the time. 

3) The button should so some sort af adding the product to the cart and initialize the checkout. 

#### Steps to reproduce the issue

1) Add a product to the cart. Navigate to any site (except cart or checkout). Open the minicart. 
2) Go to the cart and check the button on desktop browser. 
3) On product page click the (product) amazon button for product pages. 

#### Your setup

* Magento version: 2.3.5-p2
* Amazon Pay Extension Version: 1.5
* Magento Edition: Community 
* Shop URL : staging.schraub-doc.at

![JS-Console](https://user-images.githubusercontent.com/3702595/92410804-9995f300-f145-11ea-9e02-65de987af7af.JPG)

Button is not showing up on home
![Home](https://user-images.githubusercontent.com/3702595/92411035-89324800-f146-11ea-9f81-2b84bdc63de8.JPG)

Button is showing up on cart page but constantly changes size
![cart](https://user-images.githubusercontent.com/3702595/92411039-8d5e6580-f146-11ea-8c41-df52f95a3dd7.JPG)

**Comment by diybook** [comment]
Ad 2) I've found the code where the resizing is done, but have no clue how to fix it.

![Unbenannt](https://user-images.githubusercontent.com/3702595/92547896-2039f580-f256-11ea-99bf-4081555992a5.JPG)

Could anyone of the team have had a look through these issues?

**Comment by christianzichichi** [comment]
Hi @diybook , 
thanks for contacting us. We have also received your email at payments-cp-devel@amazon.com. This seems like a template-specific issue, that is conflicting with our plugin. Our agency will investigate and I'll report back here. 

Thanks
Best
Christian

**Comment by diybook** [comment]
Thank you for your response. In the meantime I could fix point 2 by adepting the css. So the size is hardcoded and do not flickr any more. But more interesting are points 1 and 3. 

Thanks for your investigation. 
Best regards, 
Gerald

**Comment by jajajaime** [comment]
Hi @diybook,

1. I noticed that the button now shows in the minicart on all pages, but at least the homepage and category pages show it twice. What changed?
3. I was also not able to get the button to render on product pages, so could not test the add to cart part. Not even the container for the button shows up. Was a config changed?

Moreover, when clicking any of the buttons, it is rendering the V1 popup. Was the config changed to use V1?

**Comment by diybook** [comment]
Hi @jajajaime,

I suppose you've looked at the current live website.  But the V2 is implemented on our development site only. You have to look at staging.schraub-doc.at. I've sent the credentials to login to payments-cp-devel@amazon.com. I can send them to you directly but I have not found any PM-button here. There I can activate the button on the product page too. This is currently disabled also on our dev site. 

Please let me know how to send the credentials to you. 
With best regards, 
Gerald

**Comment by jaybeckr** [comment]
Hi @diybook , Following up on your items:
1. minicart rendering: We've seen that `duration` error before without it affecting anything, but it seems like it may have been related to your site not showing the button on the minicart or on product pages. Today I am no longer getting the error, and the button is showing on the staging site product pages, please re-test.
2. Button height: this is odd, but sounds like you fixed it via css
3. PDP button not instant purchase: Please update your Magento config to disable the "After Adding a Product Redirect to Shopping Cart" option if you want the button to begin Amazon checkout flow: https://docs.magento.com/user-guide/sales/cart-redirect.html

**Comment by diybook** [comment]
Hi @jaybeckr , thanks for your very useful hints. They pushed me in the right direction. And I've some news on this topic.
1. minicart rendering is only possible on sites with saleable products. So once the addtocart.phtml is not shown or better the `<?= $block->getChildHtml('', true) ?>` part in it is not called, the js error is produced and the button is not showing up. For testing purpose I've added the childblock to the else section of the addtocart.phtml so that instant payment buttons are shown on not saleable products. Then the minicart works but, it's no real solution, because category or home will still not work. Maybe this helps you to hellp me with that particular problem. 
2. fixed and forgotten
3. that works - turning of the redirect - but paypal can do better. I can live with that but it's maybe an improvement request. 
4. tured up testing the button on the product page. The cart is not cleared before adding the product to the cart for instant purchase, so the product was bought twice. To me it should clear the cart first. But that behaviour could be intended. 

Best regards, Gerald

**Comment by christianzichichi** [comment]
hi @diybook,
1 - a fix for this issue has been rolled out on Amazon side today. No fix is required on the plugin side.
3 - "After Adding a Product Redirect to Shopping Cart" is disabled by default, turning it on overrides plugin settings
4 - the behaviour is intended

Please reopen this issue should you encounter any other problem with the plugin. We will be happy to assist you.

Thanks
Best
Christian
