### ISSUE TITLE
bin/magento setup:di:compile Error

### ISSUE THREAD

**Issue by haneef-faisal** [amzn/amazon-payments-magento-2-plugin#856]
Magento Version: 2.3.5-p1
PHP Version: 7.2.33
PHP Memory Limit: 2048M

$ composer require amzn/amazon-payments-magento-2-plugin:dev-V2checkout-1.2.x
<some message: completed successfully>
$ bin/magento module:enable Amazon_PayV2 --clear-static-content
<some message: completed successfully>
$ bin/magento setup:upgrade
<some message: completed successfully>
$ bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/8 [===>------------------------]  12% 1 sec 82.5 MiBPHP Fatal error:  Class Amazon\PayV2\Domain\AmazonAddressDecoratorJp contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Amazon\PayV2\Domain\AmazonAddressInterface::shiftLines, Amazon\PayV2\Domain\AmazonAddressInterface::setCompany) in /chroot/home/a7aba934/pasm2.com/vendor/amzn/amazon-payments-magento-2-plugin/src/PayV2/Domain/AmazonAddressDecoratorJp.php on line 20

Tried the method mentioned at https://gist.github.com/christianzichichi/7d0d76b541070c3cdea77554c391c571; getting the same error during compile.

**Comment by christianzichichi** [comment]
Hi @haneef-faisal , 
we have just reverted a faulty commit that caused this issue on V2checkout-1.2.x branch (https://github.com/amzn/amazon-payments-magento-2-plugin/pull/857)

can you try installing it again?

I apologize for the inconvenience
Thanks
Best

Christian

**Comment by haneef-faisal** [comment]
worked now; pasting the output for reference

$ composer require amzn/amazon-payments-magento-2-plugin:dev-V2checkout-1.2.x
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating amzn/amazon-payments-magento-2-plugin dev-V2checkout-1.2.x (40bac3a => 370d5a6):  Checking out 370d5a637e
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../codeception,../../magento/magento-coding-standard,../../phpcompatibility/php-compatibility

$ bin/magento module:enable Amazon_PayV2 --clear-static-content
No modules were changed.

$ bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
Updating modules:
Nothing to import.

$ bin/magento setup:di:compile
Compilation was started.
App action list generation... 8/8 [============================] 100% 57 secs 526.0 MiB
Generated code and dependency injection configuration successfully.

$ bin/magento setup:static-content:deploy -f && bin/magento cache:flush

Deploy using quick strategy
frontend/Magento/blank/en_US            2550/2550           ============================ 100%   7 secs
adminhtml/Magento/backend/en_US         3013/3013           ============================ 100%   4 secs
frontend/Magento/luma/en_US             2567/2567           ============================ 100%   8 secs
frontend/Smartwave/porto/en_US          2657/2657           ============================ 100%   9 secs
frontend/Smartwave/porto_rtl/en_US      2657/2657           ============================ 100%   9 secs

Execution time: 41.466135978699
Flushed cache types:
config
layout
block_html
collections
reflection
db_ddl
compiled_config
eav
customer_notification
config_integration
config_integration_api
google_product
full_page
config_webservice
translate
vertex

**Comment by haneef-faisal** [comment]
After completing the above; now the Amazon Pay button is not appearing on cart page; getting following error in browser

Uncaught TypeError: Cannot read property 'duration' of undefined
    at _t (checkout.js:formatted:875)
    at Object.Ae [as renderButton] (checkout.js:formatted:1623)
    at amazon-button.js:91
    at $.<computed>.<computed>.<anonymous> (amazon-button.js:36)
    at Object.<anonymous> (checkout-session-config-load.js:42)
    at fire (jquery.js:3238)
    at Object.fireWith [as resolveWith] (jquery.js:3368)
    at done (jquery.js:9846)
    at XMLHttpRequest.callback (jquery.js:10317)

Note: Amazon Pay button appearing on following places without error:
a. Product Details Page
b. Mini Cart
c. Check Out Page

**Comment by diybook** [comment]
#855 seems the same issue I have. 

But the button is crrently visible in the minicart only on cart and checkout page itself. On other pages the redering fails due to the js error you have mentioned. Maybe you can check if the behaviour is the same. And do you also experience the constant changing in height of the button?

**Comment by haneef-faisal** [comment]
@diybook I have been testing on Opera Version:70.0.3728.154 on Win10. My observation is

1. The Amazon Pay doesn't load on the cart page on first load
2. After multiple reloads, the button seems to appear but I am not seeing the button changing height, it loads and remains the same size on my end; once the page load completes; I am not seeing any extra js being fired
3. The tool-tip beside the button is pretty annoying and should be removable via config settings rather than having to jump into the code
4. I am unable to initiate Amazon Pay due a config issue that I have explained at #858; because of that I am getting error 
"checkout.js:1 PUT https://m2design.proaudiostar.com/amazon_payv2/checkout/createSession 500" 
"checkout.js:1 Uncaught AmazonPay: Create checkout session failed, create checkout session error returns 500."

will report back after testing this on Chrome & Firefox

**Comment by christianzichichi** [comment]
Hi @haneef-faisal , 
closing this as the original issue (compile errors) has been solved. I'm going to reply to the other issues shortly.

Thanks 
Best
Christian
