### ISSUE TITLE
V2 Configurations Confusion

### ISSUE THREAD

**Issue by haneef-faisal** [amzn/amazon-payments-magento-2-plugin#858]
V2 Configurations are confusing

on Magento asking for:
Private Key
Public Key ID
Merchant Id
Store Id

on Amazon under Integration --> MWS Access Key; we have
Seller ID (using in Merchant ID above)
Access Key ID
Secret Access Key
Client ID (using in Store ID above)
Client Secret

which ones are to be used for Private Key & Public Key ID?

**Comment by islandskater43** [comment]
@haneef-faisal - you can grab the V2 configuration / key values from Seller Central and clicking "Integration" -> "Integration Central".

Additional details are available in the V2 readme in the V2Checkout branch.
https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout#amazon-pay-v2-configuration
