### ISSUE TITLE
[bug] Shipping methods are not rendered after address changing in Amazon Address Book widget on Checkout.

### ISSUE THREAD

**Issue by aholovan** [amzn/amazon-payments-magento-2-plugin#88]
#### What I expected

Shipping methods are re-rendered after changing the address

#### What happened instead

Shipping methods are not recalculated and actually freezes by damaging checkout process.

![050](https://user-images.githubusercontent.com/5063190/28662248-22b36542-72c2-11e7-9033-63767d5a8316.png)

#### Steps to reproduce the issue

Install on Magento 2.1.7
Install V1.1.2 of amazon-payments-magento-2-plugin
Configure account, enable Amazon pay in Magento admin

1 - Login with Amazon, add default address in my account, add a couple items to cart 
2 - Logout
3 - Start over as a guest and add one item to cart
4 - Login with Amazon again
5 - Go to Checkout and try to change the address in Amazon Address Book widget.

#### Your setup

* Magento version: 2.1.7
* Magento Edition: Enterprise
* JavaScript Console: There are no errors in console.

**Comment by aholovan** [comment]
Hello @danielneu,

Please, check the issue and review the fix.

Thanks.

**Comment by danielneu** [comment]
Thanks for raising this.

I will have our Magento experts check this.

Best wishes 
Daniel

**Comment by danielneu** [comment]
@Silarn So, you would favor this PR of the one you provided? Shall we close yours then?

For the redirecting, did you still see this with 1.1.3? We updated the logic a bit and are working on a even more robust way of deciding the target page currently.

The logic in 1.1.3 should however hardly in any situation do the wrong thing based on the tests we did.

Best wishes 
Daniel

**Comment by Silarn** [comment]
@danielneu I may not have upgraded to that version just yet, I'll give it a try soon.

I would probably favor this PR as it preserves the setShippingAddressFromData method as part of the process and then only uses selectShippingAddress if no selected address is found. My PR may skip some of the data setting that should occur, even though it does seem to work.

**Comment by OnTapKristjan** [comment]
Managed to reproduce the issue with Magento 2.1.6
Will attempt to fix this together with #28

**Comment by aholovan** [comment]
Hi @OnTapKristjan,
I'm not able to get this error with the latter code fix. Have You tested it?

**Comment by aholovan** [comment]
@OnTapKristjan,
which I recently added to fix current task:
https://github.com/amzn/amazon-payments-magento-2-plugin/pull/89/files

**Comment by danielneu** [comment]
This issue and the associated PR will most likely be resolved by #106 which is currently in QA.

**Comment by danielneu** [comment]
Also an update on #106 , we are close to having a stable version and getting this released.
This will solve a couple of problems and make the integration into the shop more stable.

Best wishes 
Daniel
