### ISSUE TITLE
Javascript Error on Checkout with last version

### ISSUE THREAD

**Issue by jarag-amersport** [amzn/amazon-payments-magento-2-plugin#911]
Since this commit (https://github.com/amzn/amazon-payments-magento-2-plugin/commit/1aa9ac67158f32e45ecd5e3fe7abc08f6a3f23b0), we have a javascript error on the checkout.

The method amazonStorage.isAmazonAccountLoggedIn() no longer exists in PayV2 ..

https://github.com/amzn/amazon-payments-magento-2-plugin/blob/d582dc3c91719a442b171ee5ab5d35a6b0eb6408/src/PayV2/view/frontend/web/js/view/checkout/summary/grand-total-mixin.js#L14

**Comment by jaybeckr** [comment]
Thanks for pointing that out @jarag-amersport , updated to the new way to detect if customer is in Amazon checkout flow in https://github.com/amzn/amazon-payments-magento-2-plugin/pull/912

Let me know if this resolves the issue for you, thanks!
