### ISSUE TITLE
graphql support

### ISSUE THREAD

**Issue by nbrouka** [amzn/amazon-payments-magento-2-plugin#919]
Do you plan to support graphql for your plugin similar to how it is implemented for PayPal, for example?
https://devdocs.magento.com/guides/v2.4/graphql/payment-methods/paypal-express-checkout.html

Or maybe you can suggest how this can be implemented?

**Comment by christianzichichi** [comment]
Hi @nbrouka,
Checkout V2 product REST Endpoints are exposed for PWA use cases : https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x#pwa-support

Let me know if this helps
Thanks
Best

Christian

**Comment by theshreyas** [comment]
[Check this.](https://github.com/theshreyas/magento-2-quickies/tree/main/GraphQl/Amazonpay) developed this a year back.

**Comment by liamjtoohey** [comment]
https://amzn.github.io/amazon-payments-magento-2-plugin/customisation.html - seems the best reference in regards to a PWA/GraphQL implementation.

**Comment by christianzichichi** [comment]
@liamjtoohey 
@theshreyas 
@nbrouka 

GraphQL support has been introduced in version 5.13.0: 
https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/5.13.0
https://amzn.github.io/amazon-payments-magento-2-plugin/graphql-docs.html
https://amzn.github.io/amazon-payments-magento-2-plugin/customisation.html#docs

feel free to provide any feedback and reopen this issue in case you have any problems!

Thanks
Best
Christian
