### ISSUE TITLE
Amazon Pay Not Working On Mobile - Throws An Error While Clicking Amazon Pay Button

### ISSUE THREAD

**Issue by codhepstack** [amzn/amazon-payments-magento-2-plugin#924]
This is to bring to your kind notice that while placing the order via Amazon Pay (IMPORTANT - On Mobile Only) the process break and it throws an error - The selected payment method is not available for this purchase. Choose a different payment method.
400

However, Amazon Pay works well on the Desktop.
Please check and share the best solution.

#### What I expected

While Clicking the Amazon Pay Button, on the cart page and the checkout page, the user must be redirected to the Amazon seller account to pay.

#### What happened instead

When you click on the Amazon Pay button, an error comes up like "The selected payment method is not available for this purchase. Choose a different payment method"

#### Steps to reproduce the issue

Goto the shop in mobile, add to cart a product and goto cart page. Check on the Amazon Pay button and see  the error.
![amazon pay error](https://user-images.githubusercontent.com/22224335/96539414-9b141880-12b8-11eb-87dd-e6676453ffab.png)

#### Your setup

* Magento version: 2.3.4
* Amazon Pay Extension Version: 3.7.1 
* Magento Edition: Enterprise 
* Shop URL : https://www.toneart-shop.de/

**Comment by christianzichichi** [comment]
Hi @codhepstack,

Can you doublecheck if "Allowed Return URLs" are correctly set in Seller Central as indicated in the docs: 
https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#allowed-javascript-origins-allowed-return-urls-ipn-url ?

Thanks
Best

Christian
