### ISSUE TITLE
Unable to test Amazon Pay in sandbox mode using mobile devices

### ISSUE THREAD

**Issue by arendarenko** [amzn/amazon-payments-magento-2-plugin#933]
I've configured Amazon Payments module on Magento 2.4.1 EE to test it in sandbox mode, added staging website url to whitelist. It's working as expected on desktop.

But once I'm trying to test in on mobile (iPhone X, Safari) or even on Mac Chrome with mobile device emulation mode it shows me such error:

![IMG_4761](https://user-images.githubusercontent.com/42036143/98265397-b60daa80-1f91-11eb-8b82-b45af286f6ff.PNG)

Is it a known issue? Is it happening only with sandbox mode or for production mode as well? 

#### Your setup

* Magento version: 2.4.1
* Amazon Pay Extension Version: 
* Magento Edition:  Enterprise

**Comment by arendarenko** [comment]
Hi guys, do you have any feedback on this?

**Comment by arendarenko** [comment]
seems like it's duplicate for https://github.com/amzn/amazon-payments-magento-2-plugin/issues/924

**Comment by christianzichichi** [comment]
Hi @arendarenko ,
apologize for the delay herre. have you been able to fix it following the indications on #924? it seems an issue with redirect URL whitelisting

Christian

**Comment by christianzichichi** [comment]
As we haven't received any feedback in a while, I'm going to close this issue out for the moment. Feel free to reopen it in case you have any other issue with our extension. We'd also suggest to move to our new extension (https://github.com/amzn/amazon-payments-magento-2-plugin), recently published on the Magento Marketplace: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html. New User guide: https://amzn.github.io/amazon-payments-magento-2-plugin/

Thanks
Best

Christian
