### ISSUE TITLE
Amazon PaymentPlanNotSet and AmountNotSet constraints

### ISSUE THREAD

**Issue by Dren7755** [amzn/amazon-payments-magento-2-plugin#954]
Customer can't choose Amazon Payment Method in amazon widget.
This problem is happend after some time I used sandbox amazon. 
So, before that it was possible to choose some credit card and place order successfully (for the same product). I don't know exactly what breaks this functionality.
And I hope you can explain what can trigger PaymentPlanNotSet and AmountNotSet errors.

#### What I expected

It should be possible to select amazon payment method and place order

#### What happened instead

I can't select amazon payment method (credit card etc)

I have attached the video
[Screen Recording 2020-11-18 at 11.38.01.zip](https://github.com/amzn/amazon-payments-magento-2-plugin/files/5559141/Screen.Recording.2020-11-18.at.11.38.01.zip)

paywithamazon.log contains following:
```
      <Constraints>
        <Constraint>
          <ConstraintID>PaymentPlanNotSet</ConstraintID>
          <Description>The buyer has not been able to select a Payment method for the given Order Reference.</Description>
        </Constraint>
        <Constraint>
          <ConstraintID>AmountNotSet</ConstraintID>
          <Description>The seller has not set the amount for the Order Reference.</Description>
        </Constraint>
      </Constraints>
    
```

#### Steps to reproduce the issue

1. Add product to card (configurable in my case)
2. Go to magento checkout (3rd party one-step checkout)
3. Click on Amazon Pay widget button
4. Choose the shipping address in Amazon Address Book
5. See that Amazon Payment Method widget has no any available method

#### Your setup

* Magento version: 2.3.3
* Amazon Pay Extension Version: amzn/amazon-pay-module:3.7.1
* Magento Edition: Community
* JavaScript Console: Console has no any errors

**Comment by christianzichichi** [comment]
Hi @Dren7755 ,
can you please contact us at payments-cp-devel@amazon.com? we would to investigate more about your installation and the compatibility with your 3rd party OSC (which is the most probable cause of the issue).

Thanks
Best
Christian

**Comment by Dren7755** [comment]
We reverted amazon upgrade and issue is gone. We will upgrade magento to the latest version and will try to upgrade Amazon later. 
Anyway, thank you for the reply.
