### ISSUE TITLE
Amazon button not showing due to performance profiling?

### ISSUE THREAD

**Issue by mikeymike** [amzn/amazon-payments-magento-2-plugin#957]
#### What I expected

Amazon pay button to show at basket

#### What happened instead

Button stays hidden by inline `display: none`

#### Steps to reproduce the issue

- In our case running with branch `V2checkout-1.2.x` with show on mini/basket enabled. 
- Add a product to basket and view basket page
- Amazon button does not show

#### Your setup

* Magento version: 2.3.2-p2
* Amazon Pay Extension Version: Branch `V2checkout-1.2.x` module: `1.8.0`
* Magento Edition: Enterprise Cloud

I traced this back to what looks like some performance profiling in the `https://static-eu.payments-amazon.com/checkout.js` JS. I know it's not controlled by this module but I'm hoping this issue may trigger a fix upstream as it's incorrectly checking for the existance of an array key. 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/2174476/99541079-498aa680-29a8-11eb-9342-1345453f175f.png">

**Comment by christianzichichi** [comment]
Hi @mikeymike ,
thanks for reaching out. Can you please share your module configuration? In particular:
- Payment region (amazon pay config)
- display currency (magento config)

Thanks
Best
Christian

**Comment by mikeymike** [comment]
Sure, Payment region is `uk` and display currency `GBP`

**Comment by christianzichichi** [comment]
could you send a test env url where the issue is reproducible to payments-cp-devel@amazon.com?

Thanks
Christian

**Comment by christianzichichi** [comment]
does the button appear correctly when the JS error does not show in console? 

Christian

**Comment by mikeymike** [comment]
@christianzichichi I don't have something I can share right this second (we have a hacky CSS fix in place for the clients benefit). However the console error is always present. manually running the `$(this.options.hideIfUnavailable).show();` line of code in the console does present the button as epxected and it never reaches this due to the console error so I'm fairly sure this is the cause.

**Comment by christianzichichi** [comment]
Hi @mikeymike ,
we are unable to reproduce the issue on our own. It could be very helpful for us if you could share a test environment where the issue is reproducible to payments-cp-devel@amazon.com

Thanks
Best

Christian

**Comment by mikeymike** [comment]
I personally don't need this resolved anymore however maybe @loxzibit would like to pick up on this now? 

The site where we see the console error is https://www.oliversweeney.com/ however as I mentioned there is some hacky code in that resolves it the button not being output. 

Feel free to close this if someone else from my old team doesn't pick up in due time.

**Comment by christianzichichi** [comment]
@mikeymike does the console error show up in console even if your fix resolves the display issue?

Thanks
Best

Christian

**Comment by mikeymike** [comment]
always shows yes
