### ISSUE TITLE
Payment Methods Tab Empty After Install

### ISSUE THREAD

**Issue by manuelfdo** [amzn/amazon-payments-magento-2-plugin#96]
#### What I expected

Proceed with Amazon Pay configuration using the backend.

#### What happened instead

The payments tab is now empty, no payment method configuration is displayed.

#### Steps to reproduce the issue

1) Install the Amazon Payment 1.1.3 via composer
2) run setup:upgrade
3) run setup:di:compile
4) run deploy static content (both front end and backend)
5) login to the Magento Admin and go to Stores > Configuration > Payment Methods
![screen shot 2017-07-28 at 10 00 45 am](https://user-images.githubusercontent.com/1271647/28724059-710add62-737e-11e7-87e2-3cb67ee06757.png)

#### Your setup

* Magento version: 2.1.2 
* Magento Edition: Community
* JavaScript Console: 
![screen shot 2017-07-28 at 10 16 27 am](https://user-images.githubusercontent.com/1271647/28724079-7e263ca8-737e-11e7-9709-651c144e5a65.png)

**Comment by EmilyPepperman** [comment]
I am fine with Amazon Pay 1.1.3 and Magento 2.1.7
![amazon_admin](https://user-images.githubusercontent.com/12411491/28725663-26ddb0c6-738c-11e7-8cde-c57c1323709f.JPG)

**Comment by danielneu** [comment]
HI,

we are also not seeing this issue on our side.

Are you seeing any log entries hinting to a possible problem?
It could be there is some collision with another payment option you installed, which is not shipped with Magento. Did you install another additional option?

Best wishes 
Daniel

**Comment by manuelfdo** [comment]
Hi! thank you for your reply!

> Did you install another additional option?
![screen shot 2017-07-31 at 9 49 27 am](https://user-images.githubusercontent.com/1271647/28783515-2a8978d0-75d6-11e7-89a2-5367210694df.png)

Just Affirm 1.0.3 Payment Module, there is something called M2EPRO that is part of eBay/Amazon market places.

**Comment by danielneu** [comment]
Are you able to verify if this is causing the issue in combination with Amazon Pay?

**Comment by manuelfdo** [comment]
Will start to disable/enable modules to test, will let you know!

thanks for your time :)

**Comment by manuelfdo** [comment]
Ok after testing, we managed to install the plugin. it works with the version 1.1.1 if try with 1.1.3 the Payment method tab disappear. we will update our Magento version soon so we can test if it happen again.

Now we are getting a different error in the checkout page, the shipping methods are not displayed and an error 404 is displayed.

> Request does not match any route.

`/rest/default/V1/amazon-shipping-address/P01-1974650-5381313 Failed to load resource: the server responded with a status of 404 (Not Found)
/rest/default/V1/amazon-billing-address/P01-1974650-5381313 Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by Silarn** [comment]
I believe #108 is a fix for this. This will happen for any install using table prefixes because this class was added with no tableName getter function. Thus, the prefix is never applied and fails when the DB call is made.

**Comment by danielneu** [comment]
This seems to be it, will be part of 1.1.4

**Comment by danielneu** [comment]
#108 was merged now

**Comment by danielneu** [comment]
#108 was a good first step, will be replaced by #117 

Will be fixed in the next release
