### ISSUE TITLE
Package amzn/login-and-pay-with-amazon-sdk-php is abandoned, you should avoid using it. Use amzn/amazon-pay-sdk-php instead.

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#97]
Installing the extension on a magento 2.1.7 system via composer shows this message:

Package amzn/login-and-pay-with-amazon-sdk-php is abandoned, you should avoid using it. Use amzn/amazon-pay-sdk-php instead.

Command line:

$ sudo composer require amzn/amazon-payments-magento-2-plugin:^1.1.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing amzn/login-and-pay-with-amazon-sdk-php (2.1.0)
    Loading from cache

  - Installing amzn/amazon-payments-magento-2-plugin (1.1.3)
    Downloading: 100%         

Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Package amzn/login-and-pay-with-amazon-sdk-php is abandoned, you should avoid using it. Use amzn/amazon-pay-sdk-php instead.
Writing lock file
Generating autoload files

After this when we run "composer update" command now each time this is shown in the output:

Package amzn/login-and-pay-with-amazon-sdk-php is abandoned, you should avoid using it. Use amzn/amazon-pay-sdk-php instead.

**Comment by danielneu** [comment]
This is being tracked in #59  and will be solved soon.
This is however not causing any issues, version 2.x of the SDK is still fully supported.
