### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by gamort** [amzn/amazon-payments-magento-2-plugin#971]
There are no release notes of changes between versions.  It would be helpful to know all the changes between 4.0.2 to 4.1.3

**Comment by christianzichichi** [comment]
Hi @gamort ,
we don't have a proper release notes file yet other than commit/PR messages between versions at the moment. 
Between 4.0.2 and 4.1.3, there was no feature addition and the most important bugfix was related to currency handling for multi-store views scenarios.

We are planning to introduce release notes for our new product, Checkout V2: https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout#installation-steps

Thanks
Best
Christian
