### ISSUE TITLE
Not always all payment methods hidden

### ISSUE THREAD

**Issue by HenKun** [amzn/amazon-payments-magento-2-plugin#972]
#### What I expected

When logged in to Amazon, all payment methods in checkout disappear, only Amazon widget is shown

#### What happened instead

Some payment methods sometimes are stil shown, e.g. "Braintree Local Payments", "Iways PayPal Plus".
Those are payment methods that need a little longer to render than others.

#### Steps to reproduce the issue

Go to checkout and login to Amazon

### Debugged reason

The magic happens in `vendor/amzn/amazon-pay-module/view/frontend/web/js/view/payment/list.js` in method `_hidePaymentMethodsOnLoad`. There it is waited for `#amazon_payment` to be rendered. Afterwards all payment methods are checked if they should be removed and then `removeRenderer` is called in parent class `vendor/magento/module-checkout/view/frontend/web/js/view/payment/list.js`. Note, at this point `createRenderer` is successfully called for all payment methods. However, `removeRenderer` relies on finished DOM rendering to be able to remove the payment method from displaying. See line 219 `items = this.getRegion(group.displayArea);` for reference. So, although `createRenderer` was called for all payment methods, `items` does not contain all methods, i.e not those methods that are slow in rendering. 
The result is that the slow payment methods are finished rendering after the Amazon Pay module did try to remove them. They show up.

Note that this fails silently, without any JS error in console, due to the simple iteration in `vendor/magento/module-checkout/view/frontend/web/js/view/payment/list.js` on line 222. Just nothing happens when the method to remove is not found in `items`

#### Your setup

* Magento version: 2.4.1
* Amazon Pay Extension Version: 4.1.3 (patched)
* Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @HenKun ,
thanks for reporting this issue. We will look into it and provide a feedback by next week

Thanks
Best
Christian

**Comment by christianzichichi** [comment]
Hi @HenKun,
Can you provide a test environment where we can reproduce the error with the third party modules enabled? You can contact us at payments-cp-devel@amazon.com

Thanks
Best
Christian

**Comment by HenKun** [comment]
@christianzichichi I will provide you with a test environment for all of the three issues I filed during the next days. Thanks for having a look at it.

**Comment by christianzichichi** [comment]
Hi @HenKun ,
has this issue been solved?

Thanks
Best
Christian

**Comment by christianzichichi** [comment]
Closing for now. Please reopen if the issue appears again. Thanks.

Christian
