### ISSUE TITLE
Amazon Payment method not selectable

### ISSUE THREAD

**Issue by HenKun** [amzn/amazon-payments-magento-2-plugin#974]
#### What I expected

After logging in to Amazon one can choose shipping address as well as Payment method within Amazon Pay Widget

#### What happened instead

Often (not always) I cannot choose the payment method: 

![image](https://user-images.githubusercontent.com/18382633/99902251-a6de6a80-2cbc-11eb-9c60-1723b2e6a08e.png)

```
Bitte wählen Sie eine Adresse aus Ihrem Amazon-Adressbuch, bevor Sie eine Zahlungsweise wählen.
```

Even if I change the address, the error stays the same:

![image](https://user-images.githubusercontent.com/18382633/99902262-cb3a4700-2cbc-11eb-8ae6-e867c4277983.png)

There is neither an error in exception.log, system.log or paywithamazon.log, nor a related issue in JS console.
Note that this happens independent of if the errors in #973 and #972 occur (which I also filed).
Also, no network requests seem to fail.

Only way around is to reload the checkout page and hope that the payment method is then selectable.

#### Steps to reproduce the issue

Login to Amazon and visit checkout

#### Your setup

* Magento version: 2.4.1
* Amazon Pay Extension Version: 4.1.3 (patched)
* Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @HenKun ,
for this issue and https://github.com/amzn/amazon-payments-magento-2-plugin/issues/973, we would need more details from you in order to proceed with the investigation. Can you contact us at payments-cp-devel@amazon.com and provide a staging URL where these 2 issues occur?

Thanks
Best
Christian

**Comment by christianzichichi** [comment]
closing this out as the issue has been solved for the merchant
