### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#98]
Also we set the language to "German" in the extension (but also before this) the amazon Explanation is is english on the cart page?

How can we translate this?

Screen attached.
![bildschirmfoto 2017-07-31 um 16 15 41](https://user-images.githubusercontent.com/16196483/28781886-e1d26a4e-760b-11e7-8b36-6a07a1a40e72.png)

**Comment by danielneu** [comment]
This is strange. Did you compile Magento for this locale?

The translation is in place: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/feb11d0733c4f8201c12b928f6d44fd706e5d7a9/src/Payment/i18n/de_DE.csv#L16

I will have to find some time to check this in detail.

Best wishes 
Daniel

**Comment by andidhouse** [comment]
Hi Daniel,

yes - complied of course. In the checkout the translation works - see screen attached.

![bildschirmfoto 2017-07-31 um 16 34 31](https://user-images.githubusercontent.com/16196483/28782695-388af6ba-760e-11e7-8285-f4ff2fd5b943.png)

**Comment by danielneu** [comment]
Could be this is missing a 'translation="true"'? 
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/dea774e933d9e395a2fc29651979772d2d610112/src/Payment/view/frontend/templates/minicart-button.phtml#L42

Best wishes 
Daniel

**Comment by andidhouse** [comment]
Can you check the other places also? It seems like the login has the same problem.

**Comment by danielneu** [comment]
I will need some time to setup a test instance, git a German Magento, ... 

If it is urgent, I would suggest changing this:
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/dea774e933d9e395a2fc29651979772d2d610112/src/Payment/view/frontend/templates/minicart-button.phtml#L42

To look like this:

<div class="field-tooltip-content" data-target="dropdown" aria-hidden="true"><?php /* @escapeNotVerified */  echo __('Are you an Amazon customer? Pay now with address and payment details stored in your Amazon account.'); ?></div>

The same for the matching location for Login.

This could resolve your issue faster than waiting for me, in case it is urgent.

Best wishes 
Daniel
