### ISSUE TITLE
Amazon Logo loads on every page! - This time: footer

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#99]
I really get a little bit angry with the payment provider all wanting to promote their payment best in every online shop.

Why the hell is amazon pay creating a new footer under the normal magento2 footer with its logo loading from another website?

Payment provider should really stop implementing those things right now - it is a payment option and should not do anything else then creating a new payment method!

How to get rid of this?

![bildschirmfoto 2017-08-01 um 15 34 42](https://user-images.githubusercontent.com/16196483/28827877-47109af2-76cf-11e7-939a-d1eddf02cbd7.png)

**Comment by danielneu** [comment]
Hi,

simply remove this block.

https://github.com/amzn/amazon-payments-magento-2-plugin/blob/feb11d0733c4f8201c12b928f6d44fd706e5d7a9/src/Core/view/frontend/layout/default.xml#L20-L24

I'll look into removing or a better placement for the next release.

Best wishes 
Daniel

**Comment by andidhouse** [comment]
HI Daniel,
thanks first.

A better place would be an option to say include anything in the frontend Yes/No in your extension. I think it is not good that a payment extension changes the storefront for design in any case!
