### ISSUE TITLE
Payment Transaction Failed - Email not coming

### ISSUE THREAD

**Issue by Techytt** [amzn/amazon-payments-magento-2-plugin#999]
-- Email notification should come for failed transaction.

-- Not getting email notification

-- Place order with decline credit card detail. 

* Magento version: 2.4.1
* Amazon Pay Extension Version: 
* Magento Edition: Community / Enterprise / Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by christianzichichi** [comment]
Hi @Techytt ,
can you clarify the following:
- Amazon Pay version
- Authorization Mode
- Payment Action

Thanks
Best

Christian

**Comment by christianzichichi** [comment]
@Techytt 

are you referencing this feature by any chance: https://docs.magento.com/user-guide/sales/checkout-payment-failed-emails.html ?

This not something we are currently offering in our plugin

Thanks
Best

Christian

**Comment by Techytt** [comment]
Yes @christianzichichi I am referring to this feature only: https://docs.magento.com/user-guide/sales/checkout-payment-failed-emails.html
Is there any future plan for support of this feature?

**Comment by christianzichichi** [comment]
Hi @Techytt ,
there is no plan to integrate this feature yet. What is the use case you are trying to cover with it?

Thanks
Best
Christian

**Comment by christianzichichi** [comment]
As we haven't received any feedback in a while, I'm going to close this issue out for the moment. Feel free to reopen it in case you have any other issue with our extension. We'd also suggest to move to our new extension (https://github.com/amzn/amazon-payments-magento-2-plugin), recently published on the Magento Marketplace: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html. New User guide: https://amzn.github.io/amazon-payments-magento-2-plugin/

Thanks
Best

Christian
